/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.sql.Blob;

import java.util.Date;

/**
 * The base model interface for the Attachment service. Represents a row in the &quot;attachment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.AttachmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.AttachmentImpl}.
 * </p>
 *
 * @author rknowsys
 * @see Attachment
 * @see com.rknowsys.eapp.hrm.model.impl.AttachmentImpl
 * @see com.rknowsys.eapp.hrm.model.impl.AttachmentModelImpl
 * @generated
 */
public interface AttachmentModel extends BaseModel<Attachment>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a attachment model instance should use the {@link Attachment} interface instead.
	 */

	/**
	 * Returns the primary key of this attachment.
	 *
	 * @return the primary key of this attachment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this attachment.
	 *
	 * @param primaryKey the primary key of this attachment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the attachment ID of this attachment.
	 *
	 * @return the attachment ID of this attachment
	 */
	public long getAttachmentId();

	/**
	 * Sets the attachment ID of this attachment.
	 *
	 * @param attachmentId the attachment ID of this attachment
	 */
	public void setAttachmentId(long attachmentId);

	/**
	 * Returns the employee ID of this attachment.
	 *
	 * @return the employee ID of this attachment
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this attachment.
	 *
	 * @param employeeId the employee ID of this attachment
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this attachment.
	 *
	 * @return the group ID of this attachment
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this attachment.
	 *
	 * @param groupId the group ID of this attachment
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this attachment.
	 *
	 * @return the company ID of this attachment
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this attachment.
	 *
	 * @param companyId the company ID of this attachment
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this attachment.
	 *
	 * @return the user ID of this attachment
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this attachment.
	 *
	 * @param userId the user ID of this attachment
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this attachment.
	 *
	 * @return the user uuid of this attachment
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this attachment.
	 *
	 * @param userUuid the user uuid of this attachment
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this attachment.
	 *
	 * @return the user name of this attachment
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this attachment.
	 *
	 * @param userName the user name of this attachment
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this attachment.
	 *
	 * @return the create date of this attachment
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this attachment.
	 *
	 * @param createDate the create date of this attachment
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this attachment.
	 *
	 * @return the modified date of this attachment
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this attachment.
	 *
	 * @param modifiedDate the modified date of this attachment
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the comment of this attachment.
	 *
	 * @return the comment of this attachment
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this attachment.
	 *
	 * @param comment the comment of this attachment
	 */
	public void setComment(String comment);

	/**
	 * Returns the file of this attachment.
	 *
	 * @return the file of this attachment
	 */
	public Blob getFile();

	/**
	 * Sets the file of this attachment.
	 *
	 * @param file the file of this attachment
	 */
	public void setFile(Blob file);

	/**
	 * Returns the attachment type of this attachment.
	 *
	 * @return the attachment type of this attachment
	 */
	public int getAttachmentType();

	/**
	 * Sets the attachment type of this attachment.
	 *
	 * @param attachmentType the attachment type of this attachment
	 */
	public void setAttachmentType(int attachmentType);

	/**
	 * Returns the size of this attachment.
	 *
	 * @return the size of this attachment
	 */
	public long getSize();

	/**
	 * Sets the size of this attachment.
	 *
	 * @param size the size of this attachment
	 */
	public void setSize(long size);

	/**
	 * Returns the file type of this attachment.
	 *
	 * @return the file type of this attachment
	 */
	@AutoEscape
	public String getFileType();

	/**
	 * Sets the file type of this attachment.
	 *
	 * @param fileType the file type of this attachment
	 */
	public void setFileType(String fileType);

	/**
	 * Returns the file name of this attachment.
	 *
	 * @return the file name of this attachment
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this attachment.
	 *
	 * @param fileName the file name of this attachment
	 */
	public void setFileName(String fileName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Attachment attachment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Attachment> toCacheModel();

	@Override
	public Attachment toEscapedModel();

	@Override
	public Attachment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}