/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ContactDetails service. Represents a row in the &quot;hrm_ContactDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.ContactDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.ContactDetailsImpl}.
 * </p>
 *
 * @author rknowsys
 * @see ContactDetails
 * @see com.rknowsys.eapp.hrm.model.impl.ContactDetailsImpl
 * @see com.rknowsys.eapp.hrm.model.impl.ContactDetailsModelImpl
 * @generated
 */
public interface ContactDetailsModel extends BaseModel<ContactDetails>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contact details model instance should use the {@link ContactDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this contact details.
	 *
	 * @return the primary key of this contact details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contact details.
	 *
	 * @param primaryKey the primary key of this contact details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this contact details.
	 *
	 * @return the ID of this contact details
	 */
	public long getId();

	/**
	 * Sets the ID of this contact details.
	 *
	 * @param id the ID of this contact details
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this contact details.
	 *
	 * @return the group ID of this contact details
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this contact details.
	 *
	 * @param groupId the group ID of this contact details
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this contact details.
	 *
	 * @return the company ID of this contact details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this contact details.
	 *
	 * @param companyId the company ID of this contact details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this contact details.
	 *
	 * @return the user ID of this contact details
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this contact details.
	 *
	 * @param userId the user ID of this contact details
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this contact details.
	 *
	 * @return the user uuid of this contact details
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this contact details.
	 *
	 * @param userUuid the user uuid of this contact details
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this contact details.
	 *
	 * @return the user name of this contact details
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this contact details.
	 *
	 * @param userName the user name of this contact details
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this contact details.
	 *
	 * @return the create date of this contact details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this contact details.
	 *
	 * @param createDate the create date of this contact details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this contact details.
	 *
	 * @return the modified date of this contact details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this contact details.
	 *
	 * @param modifiedDate the modified date of this contact details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the address street1 of this contact details.
	 *
	 * @return the address street1 of this contact details
	 */
	@AutoEscape
	public String getAddressStreet1();

	/**
	 * Sets the address street1 of this contact details.
	 *
	 * @param addressStreet1 the address street1 of this contact details
	 */
	public void setAddressStreet1(String addressStreet1);

	/**
	 * Returns the address street2 of this contact details.
	 *
	 * @return the address street2 of this contact details
	 */
	@AutoEscape
	public String getAddressStreet2();

	/**
	 * Sets the address street2 of this contact details.
	 *
	 * @param addressStreet2 the address street2 of this contact details
	 */
	public void setAddressStreet2(String addressStreet2);

	/**
	 * Returns the city of this contact details.
	 *
	 * @return the city of this contact details
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this contact details.
	 *
	 * @param city the city of this contact details
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this contact details.
	 *
	 * @return the state of this contact details
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this contact details.
	 *
	 * @param state the state of this contact details
	 */
	public void setState(String state);

	/**
	 * Returns the postal code of this contact details.
	 *
	 * @return the postal code of this contact details
	 */
	@AutoEscape
	public String getPostalCode();

	/**
	 * Sets the postal code of this contact details.
	 *
	 * @param postalCode the postal code of this contact details
	 */
	public void setPostalCode(String postalCode);

	/**
	 * Returns the country of this contact details.
	 *
	 * @return the country of this contact details
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this contact details.
	 *
	 * @param country the country of this contact details
	 */
	public void setCountry(String country);

	/**
	 * Returns the home telephone of this contact details.
	 *
	 * @return the home telephone of this contact details
	 */
	@AutoEscape
	public String getHomeTelephone();

	/**
	 * Sets the home telephone of this contact details.
	 *
	 * @param homeTelephone the home telephone of this contact details
	 */
	public void setHomeTelephone(String homeTelephone);

	/**
	 * Returns the mobile of this contact details.
	 *
	 * @return the mobile of this contact details
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this contact details.
	 *
	 * @param mobile the mobile of this contact details
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the work telephone of this contact details.
	 *
	 * @return the work telephone of this contact details
	 */
	@AutoEscape
	public String getWorkTelephone();

	/**
	 * Sets the work telephone of this contact details.
	 *
	 * @param workTelephone the work telephone of this contact details
	 */
	public void setWorkTelephone(String workTelephone);

	/**
	 * Returns the work email of this contact details.
	 *
	 * @return the work email of this contact details
	 */
	@AutoEscape
	public String getWorkEmail();

	/**
	 * Sets the work email of this contact details.
	 *
	 * @param workEmail the work email of this contact details
	 */
	public void setWorkEmail(String workEmail);

	/**
	 * Returns the other email of this contact details.
	 *
	 * @return the other email of this contact details
	 */
	@AutoEscape
	public String getOtherEmail();

	/**
	 * Sets the other email of this contact details.
	 *
	 * @param otherEmail the other email of this contact details
	 */
	public void setOtherEmail(String otherEmail);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ContactDetails contactDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ContactDetails> toCacheModel();

	@Override
	public ContactDetails toEscapedModel();

	@Override
	public ContactDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}