/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Dependent service. Represents a row in the &quot;hrm_Dependent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.DependentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.DependentImpl}.
 * </p>
 *
 * @author rknowsys
 * @see Dependent
 * @see com.rknowsys.eapp.hrm.model.impl.DependentImpl
 * @see com.rknowsys.eapp.hrm.model.impl.DependentModelImpl
 * @generated
 */
public interface DependentModel extends BaseModel<Dependent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dependent model instance should use the {@link Dependent} interface instead.
	 */

	/**
	 * Returns the primary key of this dependent.
	 *
	 * @return the primary key of this dependent
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dependent.
	 *
	 * @param primaryKey the primary key of this dependent
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dependent ID of this dependent.
	 *
	 * @return the dependent ID of this dependent
	 */
	public long getDependentId();

	/**
	 * Sets the dependent ID of this dependent.
	 *
	 * @param dependentId the dependent ID of this dependent
	 */
	public void setDependentId(long dependentId);

	/**
	 * Returns the employee ID of this dependent.
	 *
	 * @return the employee ID of this dependent
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this dependent.
	 *
	 * @param employeeId the employee ID of this dependent
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this dependent.
	 *
	 * @return the group ID of this dependent
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dependent.
	 *
	 * @param groupId the group ID of this dependent
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this dependent.
	 *
	 * @return the company ID of this dependent
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this dependent.
	 *
	 * @param companyId the company ID of this dependent
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this dependent.
	 *
	 * @return the user ID of this dependent
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dependent.
	 *
	 * @param userId the user ID of this dependent
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dependent.
	 *
	 * @return the user uuid of this dependent
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dependent.
	 *
	 * @param userUuid the user uuid of this dependent
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this dependent.
	 *
	 * @return the create date of this dependent
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dependent.
	 *
	 * @param createDate the create date of this dependent
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dependent.
	 *
	 * @return the modified date of this dependent
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dependent.
	 *
	 * @param modifiedDate the modified date of this dependent
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this dependent.
	 *
	 * @return the name of this dependent
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this dependent.
	 *
	 * @param name the name of this dependent
	 */
	public void setName(String name);

	/**
	 * Returns the relationship of this dependent.
	 *
	 * @return the relationship of this dependent
	 */
	@AutoEscape
	public String getRelationship();

	/**
	 * Sets the relationship of this dependent.
	 *
	 * @param relationship the relationship of this dependent
	 */
	public void setRelationship(String relationship);

	/**
	 * Returns the date of birth of this dependent.
	 *
	 * @return the date of birth of this dependent
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this dependent.
	 *
	 * @param dateOfBirth the date of birth of this dependent
	 */
	public void setDateOfBirth(Date dateOfBirth);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Dependent dependent);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Dependent> toCacheModel();

	@Override
	public Dependent toEscapedModel();

	@Override
	public Dependent toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}