/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Document service. Represents a row in the &quot;document&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.DocumentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.DocumentImpl}.
 * </p>
 *
 * @author rknowsys
 * @see Document
 * @see com.rknowsys.eapp.hrm.model.impl.DocumentImpl
 * @see com.rknowsys.eapp.hrm.model.impl.DocumentModelImpl
 * @generated
 */
public interface DocumentModel extends BaseModel<Document> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document model instance should use the {@link Document} interface instead.
	 */

	/**
	 * Returns the primary key of this document.
	 *
	 * @return the primary key of this document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document.
	 *
	 * @param primaryKey the primary key of this document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this document.
	 *
	 * @return the ID of this document
	 */
	public long getId();

	/**
	 * Sets the ID of this document.
	 *
	 * @param id the ID of this document
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this document.
	 *
	 * @return the company ID of this document
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this document.
	 *
	 * @param companyId the company ID of this document
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this document.
	 *
	 * @return the group ID of this document
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this document.
	 *
	 * @param groupId the group ID of this document
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this document.
	 *
	 * @return the create date of this document
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this document.
	 *
	 * @param createDate the create date of this document
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this document.
	 *
	 * @return the modified date of this document
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this document.
	 *
	 * @param modifiedDate the modified date of this document
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this document.
	 *
	 * @return the user ID of this document
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this document.
	 *
	 * @param userId the user ID of this document
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this document.
	 *
	 * @return the user uuid of this document
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this document.
	 *
	 * @param userUuid the user uuid of this document
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the doc topic of this document.
	 *
	 * @return the doc topic of this document
	 */
	@AutoEscape
	public String getDocTopic();

	/**
	 * Sets the doc topic of this document.
	 *
	 * @param docTopic the doc topic of this document
	 */
	public void setDocTopic(String docTopic);

	/**
	 * Returns the doc category of this document.
	 *
	 * @return the doc category of this document
	 */
	@AutoEscape
	public String getDocCategory();

	/**
	 * Sets the doc category of this document.
	 *
	 * @param docCategory the doc category of this document
	 */
	public void setDocCategory(String docCategory);

	/**
	 * Returns the description of this document.
	 *
	 * @return the description of this document
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this document.
	 *
	 * @param description the description of this document
	 */
	public void setDescription(String description);

	/**
	 * Returns the publish to of this document.
	 *
	 * @return the publish to of this document
	 */
	@AutoEscape
	public String getPublishTo();

	/**
	 * Sets the publish to of this document.
	 *
	 * @param publishTo the publish to of this document
	 */
	public void setPublishTo(String publishTo);

	/**
	 * Returns the publish date of this document.
	 *
	 * @return the publish date of this document
	 */
	public Date getPublishDate();

	/**
	 * Sets the publish date of this document.
	 *
	 * @param publishDate the publish date of this document
	 */
	public void setPublishDate(Date publishDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Document document);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Document> toCacheModel();

	@Override
	public Document toEscapedModel();

	@Override
	public Document toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}