/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Education service. Represents a row in the &quot;education&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.EducationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.EducationImpl}.
 * </p>
 *
 * @author rknowsys
 * @see Education
 * @see com.rknowsys.eapp.hrm.model.impl.EducationImpl
 * @see com.rknowsys.eapp.hrm.model.impl.EducationModelImpl
 * @generated
 */
public interface EducationModel extends BaseModel<Education> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a education model instance should use the {@link Education} interface instead.
	 */

	/**
	 * Returns the primary key of this education.
	 *
	 * @return the primary key of this education
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this education.
	 *
	 * @param primaryKey the primary key of this education
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the education ID of this education.
	 *
	 * @return the education ID of this education
	 */
	public long getEducationId();

	/**
	 * Sets the education ID of this education.
	 *
	 * @param educationId the education ID of this education
	 */
	public void setEducationId(long educationId);

	/**
	 * Returns the company ID of this education.
	 *
	 * @return the company ID of this education
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this education.
	 *
	 * @param companyId the company ID of this education
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this education.
	 *
	 * @return the group ID of this education
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this education.
	 *
	 * @param groupId the group ID of this education
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this education.
	 *
	 * @return the create date of this education
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this education.
	 *
	 * @param createDate the create date of this education
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this education.
	 *
	 * @return the modified date of this education
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this education.
	 *
	 * @param modifiedDate the modified date of this education
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this education.
	 *
	 * @return the user ID of this education
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this education.
	 *
	 * @param userId the user ID of this education
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this education.
	 *
	 * @return the user uuid of this education
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this education.
	 *
	 * @param userUuid the user uuid of this education
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the edu level of this education.
	 *
	 * @return the edu level of this education
	 */
	@AutoEscape
	public String getEduLevel();

	/**
	 * Sets the edu level of this education.
	 *
	 * @param eduLevel the edu level of this education
	 */
	public void setEduLevel(String eduLevel);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Education education);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Education> toCacheModel();

	@Override
	public Education toEscapedModel();

	@Override
	public Education toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}