/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmergencyContact service. Represents a row in the &quot;emergency_contact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.EmergencyContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.EmergencyContactImpl}.
 * </p>
 *
 * @author rknowsys
 * @see EmergencyContact
 * @see com.rknowsys.eapp.hrm.model.impl.EmergencyContactImpl
 * @see com.rknowsys.eapp.hrm.model.impl.EmergencyContactModelImpl
 * @generated
 */
public interface EmergencyContactModel extends BaseModel<EmergencyContact> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a EmergencyContact model instance should use the {@link EmergencyContact} interface instead.
	 */

	/**
	 * Returns the primary key of this EmergencyContact.
	 *
	 * @return the primary key of this EmergencyContact
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this EmergencyContact.
	 *
	 * @param primaryKey the primary key of this EmergencyContact
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the emergency contact ID of this EmergencyContact.
	 *
	 * @return the emergency contact ID of this EmergencyContact
	 */
	public long getEmergencyContactId();

	/**
	 * Sets the emergency contact ID of this EmergencyContact.
	 *
	 * @param emergencyContactId the emergency contact ID of this EmergencyContact
	 */
	public void setEmergencyContactId(long emergencyContactId);

	/**
	 * Returns the employee ID of this EmergencyContact.
	 *
	 * @return the employee ID of this EmergencyContact
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this EmergencyContact.
	 *
	 * @param employeeId the employee ID of this EmergencyContact
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this EmergencyContact.
	 *
	 * @return the group ID of this EmergencyContact
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this EmergencyContact.
	 *
	 * @param groupId the group ID of this EmergencyContact
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this EmergencyContact.
	 *
	 * @return the company ID of this EmergencyContact
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this EmergencyContact.
	 *
	 * @param companyId the company ID of this EmergencyContact
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this EmergencyContact.
	 *
	 * @return the user ID of this EmergencyContact
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this EmergencyContact.
	 *
	 * @param userId the user ID of this EmergencyContact
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this EmergencyContact.
	 *
	 * @return the user uuid of this EmergencyContact
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this EmergencyContact.
	 *
	 * @param userUuid the user uuid of this EmergencyContact
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this EmergencyContact.
	 *
	 * @return the create date of this EmergencyContact
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this EmergencyContact.
	 *
	 * @param createDate the create date of this EmergencyContact
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this EmergencyContact.
	 *
	 * @return the modified date of this EmergencyContact
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this EmergencyContact.
	 *
	 * @param modifiedDate the modified date of this EmergencyContact
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this EmergencyContact.
	 *
	 * @return the name of this EmergencyContact
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this EmergencyContact.
	 *
	 * @param name the name of this EmergencyContact
	 */
	public void setName(String name);

	/**
	 * Returns the relationship of this EmergencyContact.
	 *
	 * @return the relationship of this EmergencyContact
	 */
	@AutoEscape
	public String getRelationship();

	/**
	 * Sets the relationship of this EmergencyContact.
	 *
	 * @param relationship the relationship of this EmergencyContact
	 */
	public void setRelationship(String relationship);

	/**
	 * Returns the home telephone of this EmergencyContact.
	 *
	 * @return the home telephone of this EmergencyContact
	 */
	@AutoEscape
	public String getHomeTelephone();

	/**
	 * Sets the home telephone of this EmergencyContact.
	 *
	 * @param homeTelephone the home telephone of this EmergencyContact
	 */
	public void setHomeTelephone(String homeTelephone);

	/**
	 * Returns the mobile of this EmergencyContact.
	 *
	 * @return the mobile of this EmergencyContact
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this EmergencyContact.
	 *
	 * @param mobile the mobile of this EmergencyContact
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the work telephone of this EmergencyContact.
	 *
	 * @return the work telephone of this EmergencyContact
	 */
	@AutoEscape
	public String getWorkTelephone();

	/**
	 * Sets the work telephone of this EmergencyContact.
	 *
	 * @param workTelephone the work telephone of this EmergencyContact
	 */
	public void setWorkTelephone(String workTelephone);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmergencyContact emergencyContact);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmergencyContact> toCacheModel();

	@Override
	public EmergencyContact toEscapedModel();

	@Override
	public EmergencyContact toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}