/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmpEmergencyContact service. Represents a row in the &quot;emp_emergency_contact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.EmpEmergencyContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.EmpEmergencyContactImpl}.
 * </p>
 *
 * @author rknowsys
 * @see EmpEmergencyContact
 * @see com.rknowsys.eapp.hrm.model.impl.EmpEmergencyContactImpl
 * @see com.rknowsys.eapp.hrm.model.impl.EmpEmergencyContactModelImpl
 * @generated
 */
public interface EmpEmergencyContactModel extends BaseModel<EmpEmergencyContact> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a EmpEmergencyContact model instance should use the {@link EmpEmergencyContact} interface instead.
	 */

	/**
	 * Returns the primary key of this EmpEmergencyContact.
	 *
	 * @return the primary key of this EmpEmergencyContact
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this EmpEmergencyContact.
	 *
	 * @param primaryKey the primary key of this EmpEmergencyContact
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the emp emergency contact ID of this EmpEmergencyContact.
	 *
	 * @return the emp emergency contact ID of this EmpEmergencyContact
	 */
	public long getEmpEmergencyContactId();

	/**
	 * Sets the emp emergency contact ID of this EmpEmergencyContact.
	 *
	 * @param empEmergencyContactId the emp emergency contact ID of this EmpEmergencyContact
	 */
	public void setEmpEmergencyContactId(long empEmergencyContactId);

	/**
	 * Returns the employee ID of this EmpEmergencyContact.
	 *
	 * @return the employee ID of this EmpEmergencyContact
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this EmpEmergencyContact.
	 *
	 * @param employeeId the employee ID of this EmpEmergencyContact
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this EmpEmergencyContact.
	 *
	 * @return the group ID of this EmpEmergencyContact
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this EmpEmergencyContact.
	 *
	 * @param groupId the group ID of this EmpEmergencyContact
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this EmpEmergencyContact.
	 *
	 * @return the company ID of this EmpEmergencyContact
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this EmpEmergencyContact.
	 *
	 * @param companyId the company ID of this EmpEmergencyContact
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this EmpEmergencyContact.
	 *
	 * @return the user ID of this EmpEmergencyContact
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this EmpEmergencyContact.
	 *
	 * @param userId the user ID of this EmpEmergencyContact
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this EmpEmergencyContact.
	 *
	 * @return the user uuid of this EmpEmergencyContact
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this EmpEmergencyContact.
	 *
	 * @param userUuid the user uuid of this EmpEmergencyContact
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this EmpEmergencyContact.
	 *
	 * @return the create date of this EmpEmergencyContact
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this EmpEmergencyContact.
	 *
	 * @param createDate the create date of this EmpEmergencyContact
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this EmpEmergencyContact.
	 *
	 * @return the modified date of this EmpEmergencyContact
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this EmpEmergencyContact.
	 *
	 * @param modifiedDate the modified date of this EmpEmergencyContact
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this EmpEmergencyContact.
	 *
	 * @return the name of this EmpEmergencyContact
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this EmpEmergencyContact.
	 *
	 * @param name the name of this EmpEmergencyContact
	 */
	public void setName(String name);

	/**
	 * Returns the relationship of this EmpEmergencyContact.
	 *
	 * @return the relationship of this EmpEmergencyContact
	 */
	@AutoEscape
	public String getRelationship();

	/**
	 * Sets the relationship of this EmpEmergencyContact.
	 *
	 * @param relationship the relationship of this EmpEmergencyContact
	 */
	public void setRelationship(String relationship);

	/**
	 * Returns the home telephone of this EmpEmergencyContact.
	 *
	 * @return the home telephone of this EmpEmergencyContact
	 */
	@AutoEscape
	public String getHomeTelephone();

	/**
	 * Sets the home telephone of this EmpEmergencyContact.
	 *
	 * @param homeTelephone the home telephone of this EmpEmergencyContact
	 */
	public void setHomeTelephone(String homeTelephone);

	/**
	 * Returns the mobile of this EmpEmergencyContact.
	 *
	 * @return the mobile of this EmpEmergencyContact
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this EmpEmergencyContact.
	 *
	 * @param mobile the mobile of this EmpEmergencyContact
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the work telephone of this EmpEmergencyContact.
	 *
	 * @return the work telephone of this EmpEmergencyContact
	 */
	@AutoEscape
	public String getWorkTelephone();

	/**
	 * Sets the work telephone of this EmpEmergencyContact.
	 *
	 * @param workTelephone the work telephone of this EmpEmergencyContact
	 */
	public void setWorkTelephone(String workTelephone);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmpEmergencyContact empEmergencyContact);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmpEmergencyContact> toCacheModel();

	@Override
	public EmpEmergencyContact toEscapedModel();

	@Override
	public EmpEmergencyContact toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}