/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmpEducation service. Represents a row in the &quot;emp_education&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.EmpEducationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.EmpEducationImpl}.
 * </p>
 *
 * @author rknowsys
 * @see EmpEducation
 * @see com.rknowsys.eapp.hrm.model.impl.EmpEducationImpl
 * @see com.rknowsys.eapp.hrm.model.impl.EmpEducationModelImpl
 * @generated
 */
public interface EmpEducationModel extends BaseModel<EmpEducation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emp education model instance should use the {@link EmpEducation} interface instead.
	 */

	/**
	 * Returns the primary key of this emp education.
	 *
	 * @return the primary key of this emp education
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this emp education.
	 *
	 * @param primaryKey the primary key of this emp education
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the emp education ID of this emp education.
	 *
	 * @return the emp education ID of this emp education
	 */
	public long getEmpEducationId();

	/**
	 * Sets the emp education ID of this emp education.
	 *
	 * @param empEducationId the emp education ID of this emp education
	 */
	public void setEmpEducationId(long empEducationId);

	/**
	 * Returns the employee ID of this emp education.
	 *
	 * @return the employee ID of this emp education
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this emp education.
	 *
	 * @param employeeId the employee ID of this emp education
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this emp education.
	 *
	 * @return the group ID of this emp education
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this emp education.
	 *
	 * @param groupId the group ID of this emp education
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this emp education.
	 *
	 * @return the company ID of this emp education
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this emp education.
	 *
	 * @param companyId the company ID of this emp education
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this emp education.
	 *
	 * @return the create date of this emp education
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this emp education.
	 *
	 * @param createDate the create date of this emp education
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this emp education.
	 *
	 * @return the modified date of this emp education
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this emp education.
	 *
	 * @param modifiedDate the modified date of this emp education
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this emp education.
	 *
	 * @return the user ID of this emp education
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this emp education.
	 *
	 * @param userId the user ID of this emp education
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this emp education.
	 *
	 * @return the user uuid of this emp education
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this emp education.
	 *
	 * @param userUuid the user uuid of this emp education
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the education ID of this emp education.
	 *
	 * @return the education ID of this emp education
	 */
	public long getEducationId();

	/**
	 * Sets the education ID of this emp education.
	 *
	 * @param educationId the education ID of this emp education
	 */
	public void setEducationId(long educationId);

	/**
	 * Returns the institute of this emp education.
	 *
	 * @return the institute of this emp education
	 */
	@AutoEscape
	public String getInstitute();

	/**
	 * Sets the institute of this emp education.
	 *
	 * @param institute the institute of this emp education
	 */
	public void setInstitute(String institute);

	/**
	 * Returns the major of this emp education.
	 *
	 * @return the major of this emp education
	 */
	@AutoEscape
	public String getMajor();

	/**
	 * Sets the major of this emp education.
	 *
	 * @param major the major of this emp education
	 */
	public void setMajor(String major);

	/**
	 * Returns the year of this emp education.
	 *
	 * @return the year of this emp education
	 */
	@AutoEscape
	public String getYear();

	/**
	 * Sets the year of this emp education.
	 *
	 * @param year the year of this emp education
	 */
	public void setYear(String year);

	/**
	 * Returns the start date of this emp education.
	 *
	 * @return the start date of this emp education
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this emp education.
	 *
	 * @param startDate the start date of this emp education
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this emp education.
	 *
	 * @return the end date of this emp education
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this emp education.
	 *
	 * @param endDate the end date of this emp education
	 */
	public void setEndDate(Date endDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmpEducation empEducation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmpEducation> toCacheModel();

	@Override
	public EmpEducation toEscapedModel();

	@Override
	public EmpEducation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}