/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmpLanguage service. Represents a row in the &quot;emp_language&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.EmpLanguageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.EmpLanguageImpl}.
 * </p>
 *
 * @author rknowsys
 * @see EmpLanguage
 * @see com.rknowsys.eapp.hrm.model.impl.EmpLanguageImpl
 * @see com.rknowsys.eapp.hrm.model.impl.EmpLanguageModelImpl
 * @generated
 */
public interface EmpLanguageModel extends BaseModel<EmpLanguage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emp language model instance should use the {@link EmpLanguage} interface instead.
	 */

	/**
	 * Returns the primary key of this emp language.
	 *
	 * @return the primary key of this emp language
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this emp language.
	 *
	 * @param primaryKey the primary key of this emp language
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the emp language ID of this emp language.
	 *
	 * @return the emp language ID of this emp language
	 */
	public long getEmpLanguageId();

	/**
	 * Sets the emp language ID of this emp language.
	 *
	 * @param empLanguageId the emp language ID of this emp language
	 */
	public void setEmpLanguageId(long empLanguageId);

	/**
	 * Returns the employee ID of this emp language.
	 *
	 * @return the employee ID of this emp language
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this emp language.
	 *
	 * @param employeeId the employee ID of this emp language
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this emp language.
	 *
	 * @return the group ID of this emp language
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this emp language.
	 *
	 * @param groupId the group ID of this emp language
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this emp language.
	 *
	 * @return the company ID of this emp language
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this emp language.
	 *
	 * @param companyId the company ID of this emp language
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this emp language.
	 *
	 * @return the create date of this emp language
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this emp language.
	 *
	 * @param createDate the create date of this emp language
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this emp language.
	 *
	 * @return the modified date of this emp language
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this emp language.
	 *
	 * @param modifiedDate the modified date of this emp language
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this emp language.
	 *
	 * @return the user ID of this emp language
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this emp language.
	 *
	 * @param userId the user ID of this emp language
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this emp language.
	 *
	 * @return the user uuid of this emp language
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this emp language.
	 *
	 * @param userUuid the user uuid of this emp language
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the language ID of this emp language.
	 *
	 * @return the language ID of this emp language
	 */
	public long getLanguageId();

	/**
	 * Sets the language ID of this emp language.
	 *
	 * @param languageId the language ID of this emp language
	 */
	public void setLanguageId(long languageId);

	/**
	 * Returns the language skill of this emp language.
	 *
	 * @return the language skill of this emp language
	 */
	@AutoEscape
	public String getLanguageSkill();

	/**
	 * Sets the language skill of this emp language.
	 *
	 * @param languageSkill the language skill of this emp language
	 */
	public void setLanguageSkill(String languageSkill);

	/**
	 * Returns the language fluency of this emp language.
	 *
	 * @return the language fluency of this emp language
	 */
	@AutoEscape
	public String getLanguageFluency();

	/**
	 * Sets the language fluency of this emp language.
	 *
	 * @param languageFluency the language fluency of this emp language
	 */
	public void setLanguageFluency(String languageFluency);

	/**
	 * Returns the comments of this emp language.
	 *
	 * @return the comments of this emp language
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this emp language.
	 *
	 * @param comments the comments of this emp language
	 */
	public void setComments(String comments);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmpLanguage empLanguage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmpLanguage> toCacheModel();

	@Override
	public EmpLanguage toEscapedModel();

	@Override
	public EmpLanguage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}