/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmpLicense service. Represents a row in the &quot;emp_license&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.EmpLicenseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.EmpLicenseImpl}.
 * </p>
 *
 * @author rknowsys
 * @see EmpLicense
 * @see com.rknowsys.eapp.hrm.model.impl.EmpLicenseImpl
 * @see com.rknowsys.eapp.hrm.model.impl.EmpLicenseModelImpl
 * @generated
 */
public interface EmpLicenseModel extends BaseModel<EmpLicense> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emp license model instance should use the {@link EmpLicense} interface instead.
	 */

	/**
	 * Returns the primary key of this emp license.
	 *
	 * @return the primary key of this emp license
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this emp license.
	 *
	 * @param primaryKey the primary key of this emp license
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the emp license ID of this emp license.
	 *
	 * @return the emp license ID of this emp license
	 */
	public long getEmpLicenseId();

	/**
	 * Sets the emp license ID of this emp license.
	 *
	 * @param empLicenseId the emp license ID of this emp license
	 */
	public void setEmpLicenseId(long empLicenseId);

	/**
	 * Returns the employee ID of this emp license.
	 *
	 * @return the employee ID of this emp license
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this emp license.
	 *
	 * @param employeeId the employee ID of this emp license
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this emp license.
	 *
	 * @return the group ID of this emp license
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this emp license.
	 *
	 * @param groupId the group ID of this emp license
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this emp license.
	 *
	 * @return the company ID of this emp license
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this emp license.
	 *
	 * @param companyId the company ID of this emp license
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this emp license.
	 *
	 * @return the create date of this emp license
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this emp license.
	 *
	 * @param createDate the create date of this emp license
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this emp license.
	 *
	 * @return the modified date of this emp license
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this emp license.
	 *
	 * @param modifiedDate the modified date of this emp license
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this emp license.
	 *
	 * @return the user ID of this emp license
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this emp license.
	 *
	 * @param userId the user ID of this emp license
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this emp license.
	 *
	 * @return the user uuid of this emp license
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this emp license.
	 *
	 * @param userUuid the user uuid of this emp license
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the license ID of this emp license.
	 *
	 * @return the license ID of this emp license
	 */
	public long getLicenseId();

	/**
	 * Sets the license ID of this emp license.
	 *
	 * @param licenseId the license ID of this emp license
	 */
	public void setLicenseId(long licenseId);

	/**
	 * Returns the license number of this emp license.
	 *
	 * @return the license number of this emp license
	 */
	@AutoEscape
	public String getLicenseNumber();

	/**
	 * Sets the license number of this emp license.
	 *
	 * @param licenseNumber the license number of this emp license
	 */
	public void setLicenseNumber(String licenseNumber);

	/**
	 * Returns the issued date of this emp license.
	 *
	 * @return the issued date of this emp license
	 */
	public Date getIssuedDate();

	/**
	 * Sets the issued date of this emp license.
	 *
	 * @param issuedDate the issued date of this emp license
	 */
	public void setIssuedDate(Date issuedDate);

	/**
	 * Returns the expiry date of this emp license.
	 *
	 * @return the expiry date of this emp license
	 */
	public Date getExpiryDate();

	/**
	 * Sets the expiry date of this emp license.
	 *
	 * @param expiryDate the expiry date of this emp license
	 */
	public void setExpiryDate(Date expiryDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmpLicense empLicense);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmpLicense> toCacheModel();

	@Override
	public EmpLicense toEscapedModel();

	@Override
	public EmpLicense toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}