/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.EmployeeImpl}.
 * </p>
 *
 * @author rknowsys
 * @see Employee
 * @see com.rknowsys.eapp.hrm.model.impl.EmployeeImpl
 * @see com.rknowsys.eapp.hrm.model.impl.EmployeeModelImpl
 * @generated
 */
public interface EmployeeModel extends BaseModel<Employee> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Employee model instance should use the {@link Employee} interface instead.
	 */

	/**
	 * Returns the primary key of this Employee.
	 *
	 * @return the primary key of this Employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Employee.
	 *
	 * @param primaryKey the primary key of this Employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee ID of this Employee.
	 *
	 * @return the employee ID of this Employee
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this Employee.
	 *
	 * @param employeeId the employee ID of this Employee
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the location ID of this Employee.
	 *
	 * @return the location ID of this Employee
	 */
	public long getLocationId();

	/**
	 * Sets the location ID of this Employee.
	 *
	 * @param locationId the location ID of this Employee
	 */
	public void setLocationId(long locationId);

	/**
	 * Returns the assigned user ID of this Employee.
	 *
	 * @return the assigned user ID of this Employee
	 */
	public long getAssignedUserId();

	/**
	 * Sets the assigned user ID of this Employee.
	 *
	 * @param assignedUserId the assigned user ID of this Employee
	 */
	public void setAssignedUserId(long assignedUserId);

	/**
	 * Returns the assigned user uuid of this Employee.
	 *
	 * @return the assigned user uuid of this Employee
	 * @throws SystemException if a system exception occurred
	 */
	public String getAssignedUserUuid() throws SystemException;

	/**
	 * Sets the assigned user uuid of this Employee.
	 *
	 * @param assignedUserUuid the assigned user uuid of this Employee
	 */
	public void setAssignedUserUuid(String assignedUserUuid);

	/**
	 * Returns the image ID of this Employee.
	 *
	 * @return the image ID of this Employee
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this Employee.
	 *
	 * @param imageId the image ID of this Employee
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the group ID of this Employee.
	 *
	 * @return the group ID of this Employee
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this Employee.
	 *
	 * @param groupId the group ID of this Employee
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this Employee.
	 *
	 * @return the company ID of this Employee
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this Employee.
	 *
	 * @param companyId the company ID of this Employee
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this Employee.
	 *
	 * @return the user ID of this Employee
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this Employee.
	 *
	 * @param userId the user ID of this Employee
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this Employee.
	 *
	 * @return the user uuid of this Employee
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this Employee.
	 *
	 * @param userUuid the user uuid of this Employee
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this Employee.
	 *
	 * @return the create date of this Employee
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this Employee.
	 *
	 * @param createDate the create date of this Employee
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this Employee.
	 *
	 * @return the modified date of this Employee
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this Employee.
	 *
	 * @param modifiedDate the modified date of this Employee
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Employee employee);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Employee> toCacheModel();

	@Override
	public Employee toEscapedModel();

	@Override
	public Employee toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}