/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.EmployeeImpl}.
 * </p>
 *
 * @author rknowsys
 * @see Employee
 * @see com.rknowsys.eapp.hrm.model.impl.EmployeeImpl
 * @see com.rknowsys.eapp.hrm.model.impl.EmployeeModelImpl
 * @generated
 */
public interface EmployeeModel extends BaseModel<Employee> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Employee model instance should use the {@link Employee} interface instead.
	 */

	/**
	 * Returns the primary key of this Employee.
	 *
	 * @return the primary key of this Employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Employee.
	 *
	 * @param primaryKey the primary key of this Employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee ID of this Employee.
	 *
	 * @return the employee ID of this Employee
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this Employee.
	 *
	 * @param employeeId the employee ID of this Employee
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the contact details ID of this Employee.
	 *
	 * @return the contact details ID of this Employee
	 */
	public long getContactDetailsId();

	/**
	 * Sets the contact details ID of this Employee.
	 *
	 * @param contactDetailsId the contact details ID of this Employee
	 */
	public void setContactDetailsId(long contactDetailsId);

	/**
	 * Returns the job ID of this Employee.
	 *
	 * @return the job ID of this Employee
	 */
	public long getJobId();

	/**
	 * Sets the job ID of this Employee.
	 *
	 * @param jobId the job ID of this Employee
	 */
	public void setJobId(long jobId);

	/**
	 * Returns the shift ID of this Employee.
	 *
	 * @return the shift ID of this Employee
	 */
	public long getShiftId();

	/**
	 * Sets the shift ID of this Employee.
	 *
	 * @param shiftId the shift ID of this Employee
	 */
	public void setShiftId(long shiftId);

	/**
	 * Returns the license ID of this Employee.
	 *
	 * @return the license ID of this Employee
	 */
	public long getLicenseId();

	/**
	 * Sets the license ID of this Employee.
	 *
	 * @param licenseId the license ID of this Employee
	 */
	public void setLicenseId(long licenseId);

	/**
	 * Returns the group ID of this Employee.
	 *
	 * @return the group ID of this Employee
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this Employee.
	 *
	 * @param groupId the group ID of this Employee
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this Employee.
	 *
	 * @return the company ID of this Employee
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this Employee.
	 *
	 * @param companyId the company ID of this Employee
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this Employee.
	 *
	 * @return the user ID of this Employee
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this Employee.
	 *
	 * @param userId the user ID of this Employee
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this Employee.
	 *
	 * @return the user uuid of this Employee
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this Employee.
	 *
	 * @param userUuid the user uuid of this Employee
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this Employee.
	 *
	 * @return the create date of this Employee
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this Employee.
	 *
	 * @param createDate the create date of this Employee
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this Employee.
	 *
	 * @return the modified date of this Employee
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this Employee.
	 *
	 * @param modifiedDate the modified date of this Employee
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this Employee.
	 *
	 * @return the first name of this Employee
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this Employee.
	 *
	 * @param firstName the first name of this Employee
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this Employee.
	 *
	 * @return the last name of this Employee
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this Employee.
	 *
	 * @param lastName the last name of this Employee
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the middle name of this Employee.
	 *
	 * @return the middle name of this Employee
	 */
	@AutoEscape
	public String getMiddleName();

	/**
	 * Sets the middle name of this Employee.
	 *
	 * @param middleName the middle name of this Employee
	 */
	public void setMiddleName(String middleName);

	/**
	 * Returns the gender of this Employee.
	 *
	 * @return the gender of this Employee
	 */
	public int getGender();

	/**
	 * Sets the gender of this Employee.
	 *
	 * @param gender the gender of this Employee
	 */
	public void setGender(int gender);

	/**
	 * Returns the marital status of this Employee.
	 *
	 * @return the marital status of this Employee
	 */
	public int getMaritalStatus();

	/**
	 * Sets the marital status of this Employee.
	 *
	 * @param maritalStatus the marital status of this Employee
	 */
	public void setMaritalStatus(int maritalStatus);

	/**
	 * Returns the nationality ID of this Employee.
	 *
	 * @return the nationality ID of this Employee
	 */
	public long getNationalityId();

	/**
	 * Sets the nationality ID of this Employee.
	 *
	 * @param nationalityId the nationality ID of this Employee
	 */
	public void setNationalityId(long nationalityId);

	/**
	 * Returns the date of birth of this Employee.
	 *
	 * @return the date of birth of this Employee
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this Employee.
	 *
	 * @param dateOfBirth the date of birth of this Employee
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the other ID of this Employee.
	 *
	 * @return the other ID of this Employee
	 */
	@AutoEscape
	public String getOtherId();

	/**
	 * Sets the other ID of this Employee.
	 *
	 * @param otherId the other ID of this Employee
	 */
	public void setOtherId(String otherId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Employee employee);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Employee> toCacheModel();

	@Override
	public Employee toEscapedModel();

	@Override
	public Employee toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}