/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmpMembership service. Represents a row in the &quot;emp_membership&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.EmpMembershipModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.EmpMembershipImpl}.
 * </p>
 *
 * @author rknowsys
 * @see EmpMembership
 * @see com.rknowsys.eapp.hrm.model.impl.EmpMembershipImpl
 * @see com.rknowsys.eapp.hrm.model.impl.EmpMembershipModelImpl
 * @generated
 */
public interface EmpMembershipModel extends BaseModel<EmpMembership> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emp membership model instance should use the {@link EmpMembership} interface instead.
	 */

	/**
	 * Returns the primary key of this emp membership.
	 *
	 * @return the primary key of this emp membership
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this emp membership.
	 *
	 * @param primaryKey the primary key of this emp membership
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the emp membership ID of this emp membership.
	 *
	 * @return the emp membership ID of this emp membership
	 */
	public long getEmpMembershipId();

	/**
	 * Sets the emp membership ID of this emp membership.
	 *
	 * @param empMembershipId the emp membership ID of this emp membership
	 */
	public void setEmpMembershipId(long empMembershipId);

	/**
	 * Returns the employee ID of this emp membership.
	 *
	 * @return the employee ID of this emp membership
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this emp membership.
	 *
	 * @param employeeId the employee ID of this emp membership
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this emp membership.
	 *
	 * @return the group ID of this emp membership
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this emp membership.
	 *
	 * @param groupId the group ID of this emp membership
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this emp membership.
	 *
	 * @return the company ID of this emp membership
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this emp membership.
	 *
	 * @param companyId the company ID of this emp membership
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this emp membership.
	 *
	 * @return the create date of this emp membership
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this emp membership.
	 *
	 * @param createDate the create date of this emp membership
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this emp membership.
	 *
	 * @return the modified date of this emp membership
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this emp membership.
	 *
	 * @param modifiedDate the modified date of this emp membership
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this emp membership.
	 *
	 * @return the user ID of this emp membership
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this emp membership.
	 *
	 * @param userId the user ID of this emp membership
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this emp membership.
	 *
	 * @return the user uuid of this emp membership
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this emp membership.
	 *
	 * @param userUuid the user uuid of this emp membership
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the membership ID of this emp membership.
	 *
	 * @return the membership ID of this emp membership
	 */
	public long getMembershipId();

	/**
	 * Sets the membership ID of this emp membership.
	 *
	 * @param membershipId the membership ID of this emp membership
	 */
	public void setMembershipId(long membershipId);

	/**
	 * Returns the subscription paid by of this emp membership.
	 *
	 * @return the subscription paid by of this emp membership
	 */
	@AutoEscape
	public String getSubscriptionPaidBy();

	/**
	 * Sets the subscription paid by of this emp membership.
	 *
	 * @param subscriptionPaidBy the subscription paid by of this emp membership
	 */
	public void setSubscriptionPaidBy(String subscriptionPaidBy);

	/**
	 * Returns the subscription amt of this emp membership.
	 *
	 * @return the subscription amt of this emp membership
	 */
	public long getSubscriptionAmt();

	/**
	 * Sets the subscription amt of this emp membership.
	 *
	 * @param subscriptionAmt the subscription amt of this emp membership
	 */
	public void setSubscriptionAmt(long subscriptionAmt);

	/**
	 * Returns the currency of this emp membership.
	 *
	 * @return the currency of this emp membership
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this emp membership.
	 *
	 * @param currency the currency of this emp membership
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the commence date of this emp membership.
	 *
	 * @return the commence date of this emp membership
	 */
	public Date getCommenceDate();

	/**
	 * Sets the commence date of this emp membership.
	 *
	 * @param commenceDate the commence date of this emp membership
	 */
	public void setCommenceDate(Date commenceDate);

	/**
	 * Returns the renewal date of this emp membership.
	 *
	 * @return the renewal date of this emp membership
	 */
	public Date getRenewalDate();

	/**
	 * Sets the renewal date of this emp membership.
	 *
	 * @param renewalDate the renewal date of this emp membership
	 */
	public void setRenewalDate(Date renewalDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmpMembership empMembership);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmpMembership> toCacheModel();

	@Override
	public EmpMembership toEscapedModel();

	@Override
	public EmpMembership toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}