/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmpSubordinate service. Represents a row in the &quot;emp_subordinate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.EmpSubordinateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.EmpSubordinateImpl}.
 * </p>
 *
 * @author rknowsys
 * @see EmpSubordinate
 * @see com.rknowsys.eapp.hrm.model.impl.EmpSubordinateImpl
 * @see com.rknowsys.eapp.hrm.model.impl.EmpSubordinateModelImpl
 * @generated
 */
public interface EmpSubordinateModel extends BaseModel<EmpSubordinate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a EmpSubordinate model instance should use the {@link EmpSubordinate} interface instead.
	 */

	/**
	 * Returns the primary key of this EmpSubordinate.
	 *
	 * @return the primary key of this EmpSubordinate
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this EmpSubordinate.
	 *
	 * @param primaryKey the primary key of this EmpSubordinate
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the emp subordinate ID of this EmpSubordinate.
	 *
	 * @return the emp subordinate ID of this EmpSubordinate
	 */
	public long getEmpSubordinateId();

	/**
	 * Sets the emp subordinate ID of this EmpSubordinate.
	 *
	 * @param empSubordinateId the emp subordinate ID of this EmpSubordinate
	 */
	public void setEmpSubordinateId(long empSubordinateId);

	/**
	 * Returns the employee ID of this EmpSubordinate.
	 *
	 * @return the employee ID of this EmpSubordinate
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this EmpSubordinate.
	 *
	 * @param employeeId the employee ID of this EmpSubordinate
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this EmpSubordinate.
	 *
	 * @return the group ID of this EmpSubordinate
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this EmpSubordinate.
	 *
	 * @param groupId the group ID of this EmpSubordinate
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this EmpSubordinate.
	 *
	 * @return the company ID of this EmpSubordinate
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this EmpSubordinate.
	 *
	 * @param companyId the company ID of this EmpSubordinate
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this EmpSubordinate.
	 *
	 * @return the user ID of this EmpSubordinate
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this EmpSubordinate.
	 *
	 * @param userId the user ID of this EmpSubordinate
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this EmpSubordinate.
	 *
	 * @return the user uuid of this EmpSubordinate
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this EmpSubordinate.
	 *
	 * @param userUuid the user uuid of this EmpSubordinate
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this EmpSubordinate.
	 *
	 * @return the create date of this EmpSubordinate
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this EmpSubordinate.
	 *
	 * @param createDate the create date of this EmpSubordinate
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this EmpSubordinate.
	 *
	 * @return the modified date of this EmpSubordinate
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this EmpSubordinate.
	 *
	 * @param modifiedDate the modified date of this EmpSubordinate
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the reporter employee ID of this EmpSubordinate.
	 *
	 * @return the reporter employee ID of this EmpSubordinate
	 */
	public long getReporterEmployeeId();

	/**
	 * Sets the reporter employee ID of this EmpSubordinate.
	 *
	 * @param reporterEmployeeId the reporter employee ID of this EmpSubordinate
	 */
	public void setReporterEmployeeId(long reporterEmployeeId);

	/**
	 * Returns the reporting method of this EmpSubordinate.
	 *
	 * @return the reporting method of this EmpSubordinate
	 */
	public long getReportingMethod();

	/**
	 * Sets the reporting method of this EmpSubordinate.
	 *
	 * @param reportingMethod the reporting method of this EmpSubordinate
	 */
	public void setReportingMethod(long reportingMethod);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmpSubordinate empSubordinate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmpSubordinate> toCacheModel();

	@Override
	public EmpSubordinate toEscapedModel();

	@Override
	public EmpSubordinate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}