/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmpSkill service. Represents a row in the &quot;emp_skill&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.EmpSkillModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.EmpSkillImpl}.
 * </p>
 *
 * @author rknowsys
 * @see EmpSkill
 * @see com.rknowsys.eapp.hrm.model.impl.EmpSkillImpl
 * @see com.rknowsys.eapp.hrm.model.impl.EmpSkillModelImpl
 * @generated
 */
public interface EmpSkillModel extends BaseModel<EmpSkill> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emp skill model instance should use the {@link EmpSkill} interface instead.
	 */

	/**
	 * Returns the primary key of this emp skill.
	 *
	 * @return the primary key of this emp skill
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this emp skill.
	 *
	 * @param primaryKey the primary key of this emp skill
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the emp skill ID of this emp skill.
	 *
	 * @return the emp skill ID of this emp skill
	 */
	public long getEmpSkillId();

	/**
	 * Sets the emp skill ID of this emp skill.
	 *
	 * @param empSkillId the emp skill ID of this emp skill
	 */
	public void setEmpSkillId(long empSkillId);

	/**
	 * Returns the employee ID of this emp skill.
	 *
	 * @return the employee ID of this emp skill
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this emp skill.
	 *
	 * @param employeeId the employee ID of this emp skill
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this emp skill.
	 *
	 * @return the group ID of this emp skill
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this emp skill.
	 *
	 * @param groupId the group ID of this emp skill
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this emp skill.
	 *
	 * @return the company ID of this emp skill
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this emp skill.
	 *
	 * @param companyId the company ID of this emp skill
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this emp skill.
	 *
	 * @return the create date of this emp skill
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this emp skill.
	 *
	 * @param createDate the create date of this emp skill
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this emp skill.
	 *
	 * @return the modified date of this emp skill
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this emp skill.
	 *
	 * @param modifiedDate the modified date of this emp skill
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this emp skill.
	 *
	 * @return the user ID of this emp skill
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this emp skill.
	 *
	 * @param userId the user ID of this emp skill
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this emp skill.
	 *
	 * @return the user uuid of this emp skill
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this emp skill.
	 *
	 * @param userUuid the user uuid of this emp skill
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the skill ID of this emp skill.
	 *
	 * @return the skill ID of this emp skill
	 */
	public long getSkillId();

	/**
	 * Sets the skill ID of this emp skill.
	 *
	 * @param skillId the skill ID of this emp skill
	 */
	public void setSkillId(long skillId);

	/**
	 * Returns the years of this emp skill.
	 *
	 * @return the years of this emp skill
	 */
	@AutoEscape
	public String getYears();

	/**
	 * Sets the years of this emp skill.
	 *
	 * @param years the years of this emp skill
	 */
	public void setYears(String years);

	/**
	 * Returns the comments of this emp skill.
	 *
	 * @return the comments of this emp skill
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this emp skill.
	 *
	 * @param comments the comments of this emp skill
	 */
	public void setComments(String comments);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmpSkill empSkill);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmpSkill> toCacheModel();

	@Override
	public EmpSkill toEscapedModel();

	@Override
	public EmpSkill toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}