/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the JobCategory service. Represents a row in the &quot;job_category&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.JobCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.JobCategoryImpl}.
 * </p>
 *
 * @author rknowsys
 * @see JobCategory
 * @see com.rknowsys.eapp.hrm.model.impl.JobCategoryImpl
 * @see com.rknowsys.eapp.hrm.model.impl.JobCategoryModelImpl
 * @generated
 */
public interface JobCategoryModel extends BaseModel<JobCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a job category model instance should use the {@link JobCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this job category.
	 *
	 * @return the primary key of this job category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this job category.
	 *
	 * @param primaryKey the primary key of this job category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the job category ID of this job category.
	 *
	 * @return the job category ID of this job category
	 */
	public long getJobCategoryId();

	/**
	 * Sets the job category ID of this job category.
	 *
	 * @param jobCategoryId the job category ID of this job category
	 */
	public void setJobCategoryId(long jobCategoryId);

	/**
	 * Returns the company ID of this job category.
	 *
	 * @return the company ID of this job category
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this job category.
	 *
	 * @param companyId the company ID of this job category
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this job category.
	 *
	 * @return the group ID of this job category
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this job category.
	 *
	 * @param groupId the group ID of this job category
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this job category.
	 *
	 * @return the create date of this job category
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this job category.
	 *
	 * @param createDate the create date of this job category
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this job category.
	 *
	 * @return the modified date of this job category
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this job category.
	 *
	 * @param modifiedDate the modified date of this job category
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this job category.
	 *
	 * @return the user ID of this job category
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this job category.
	 *
	 * @param userId the user ID of this job category
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this job category.
	 *
	 * @return the user uuid of this job category
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this job category.
	 *
	 * @param userUuid the user uuid of this job category
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the jobcategory of this job category.
	 *
	 * @return the jobcategory of this job category
	 */
	@AutoEscape
	public String getJobcategory();

	/**
	 * Sets the jobcategory of this job category.
	 *
	 * @param jobcategory the jobcategory of this job category
	 */
	public void setJobcategory(String jobcategory);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JobCategory jobCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JobCategory> toCacheModel();

	@Override
	public JobCategory toEscapedModel();

	@Override
	public JobCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}