/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.sql.Blob;

import java.util.Date;

/**
 * The base model interface for the Job service. Represents a row in the &quot;hrm_Job&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.JobModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.JobImpl}.
 * </p>
 *
 * @author rknowsys
 * @see Job
 * @see com.rknowsys.eapp.hrm.model.impl.JobImpl
 * @see com.rknowsys.eapp.hrm.model.impl.JobModelImpl
 * @generated
 */
public interface JobModel extends BaseModel<Job> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a job model instance should use the {@link Job} interface instead.
	 */

	/**
	 * Returns the primary key of this job.
	 *
	 * @return the primary key of this job
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this job.
	 *
	 * @param primaryKey the primary key of this job
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the job ID of this job.
	 *
	 * @return the job ID of this job
	 */
	public long getJobId();

	/**
	 * Sets the job ID of this job.
	 *
	 * @param jobId the job ID of this job
	 */
	public void setJobId(long jobId);

	/**
	 * Returns the job title ID of this job.
	 *
	 * @return the job title ID of this job
	 */
	public long getJobTitleId();

	/**
	 * Sets the job title ID of this job.
	 *
	 * @param jobTitleId the job title ID of this job
	 */
	public void setJobTitleId(long jobTitleId);

	/**
	 * Returns the job category ID of this job.
	 *
	 * @return the job category ID of this job
	 */
	public long getJobCategoryId();

	/**
	 * Sets the job category ID of this job.
	 *
	 * @param jobCategoryId the job category ID of this job
	 */
	public void setJobCategoryId(long jobCategoryId);

	/**
	 * Returns the sub unit ID of this job.
	 *
	 * @return the sub unit ID of this job
	 */
	public long getSubUnitId();

	/**
	 * Sets the sub unit ID of this job.
	 *
	 * @param subUnitId the sub unit ID of this job
	 */
	public void setSubUnitId(long subUnitId);

	/**
	 * Returns the location ID of this job.
	 *
	 * @return the location ID of this job
	 */
	public long getLocationId();

	/**
	 * Sets the location ID of this job.
	 *
	 * @param locationId the location ID of this job
	 */
	public void setLocationId(long locationId);

	/**
	 * Returns the employment status ID of this job.
	 *
	 * @return the employment status ID of this job
	 */
	public long getEmploymentStatusId();

	/**
	 * Sets the employment status ID of this job.
	 *
	 * @param employmentStatusId the employment status ID of this job
	 */
	public void setEmploymentStatusId(long employmentStatusId);

	/**
	 * Returns the group ID of this job.
	 *
	 * @return the group ID of this job
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this job.
	 *
	 * @param groupId the group ID of this job
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this job.
	 *
	 * @return the company ID of this job
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this job.
	 *
	 * @param companyId the company ID of this job
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this job.
	 *
	 * @return the user ID of this job
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this job.
	 *
	 * @param userId the user ID of this job
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this job.
	 *
	 * @return the user uuid of this job
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this job.
	 *
	 * @param userUuid the user uuid of this job
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this job.
	 *
	 * @return the create date of this job
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this job.
	 *
	 * @param createDate the create date of this job
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this job.
	 *
	 * @return the modified date of this job
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this job.
	 *
	 * @param modifiedDate the modified date of this job
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the joined date of this job.
	 *
	 * @return the joined date of this job
	 */
	public Date getJoinedDate();

	/**
	 * Sets the joined date of this job.
	 *
	 * @param joinedDate the joined date of this job
	 */
	public void setJoinedDate(Date joinedDate);

	/**
	 * Returns the employment contract start date of this job.
	 *
	 * @return the employment contract start date of this job
	 */
	public Date getEmploymentContractStartDate();

	/**
	 * Sets the employment contract start date of this job.
	 *
	 * @param employmentContractStartDate the employment contract start date of this job
	 */
	public void setEmploymentContractStartDate(Date employmentContractStartDate);

	/**
	 * Returns the employment contract end date of this job.
	 *
	 * @return the employment contract end date of this job
	 */
	public Date getEmploymentContractEndDate();

	/**
	 * Sets the employment contract end date of this job.
	 *
	 * @param employmentContractEndDate the employment contract end date of this job
	 */
	public void setEmploymentContractEndDate(Date employmentContractEndDate);

	/**
	 * Returns the contract details of this job.
	 *
	 * @return the contract details of this job
	 */
	public Blob getContractDetails();

	/**
	 * Sets the contract details of this job.
	 *
	 * @param contractDetails the contract details of this job
	 */
	public void setContractDetails(Blob contractDetails);

	/**
	 * Returns the employee ID of this job.
	 *
	 * @return the employee ID of this job
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this job.
	 *
	 * @param employeeId the employee ID of this job
	 */
	public void setEmployeeId(long employeeId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Job job);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Job> toCacheModel();

	@Override
	public Job toEscapedModel();

	@Override
	public Job toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}