/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the JobTitle service. Represents a row in the &quot;job_title&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.JobTitleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.JobTitleImpl}.
 * </p>
 *
 * @author rknowsys
 * @see JobTitle
 * @see com.rknowsys.eapp.hrm.model.impl.JobTitleImpl
 * @see com.rknowsys.eapp.hrm.model.impl.JobTitleModelImpl
 * @generated
 */
public interface JobTitleModel extends BaseModel<JobTitle> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a job title model instance should use the {@link JobTitle} interface instead.
	 */

	/**
	 * Returns the primary key of this job title.
	 *
	 * @return the primary key of this job title
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this job title.
	 *
	 * @param primaryKey the primary key of this job title
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the job title ID of this job title.
	 *
	 * @return the job title ID of this job title
	 */
	public long getJobTitleId();

	/**
	 * Sets the job title ID of this job title.
	 *
	 * @param jobTitleId the job title ID of this job title
	 */
	public void setJobTitleId(long jobTitleId);

	/**
	 * Returns the company ID of this job title.
	 *
	 * @return the company ID of this job title
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this job title.
	 *
	 * @param companyId the company ID of this job title
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this job title.
	 *
	 * @return the group ID of this job title
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this job title.
	 *
	 * @param groupId the group ID of this job title
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this job title.
	 *
	 * @return the create date of this job title
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this job title.
	 *
	 * @param createDate the create date of this job title
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this job title.
	 *
	 * @return the modified date of this job title
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this job title.
	 *
	 * @param modifiedDate the modified date of this job title
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this job title.
	 *
	 * @return the user ID of this job title
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this job title.
	 *
	 * @param userId the user ID of this job title
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this job title.
	 *
	 * @return the user uuid of this job title
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this job title.
	 *
	 * @param userUuid the user uuid of this job title
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the title of this job title.
	 *
	 * @return the title of this job title
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this job title.
	 *
	 * @param title the title of this job title
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this job title.
	 *
	 * @return the description of this job title
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this job title.
	 *
	 * @param description the description of this job title
	 */
	public void setDescription(String description);

	/**
	 * Returns the notes of this job title.
	 *
	 * @return the notes of this job title
	 */
	@AutoEscape
	public String getNotes();

	/**
	 * Sets the notes of this job title.
	 *
	 * @param notes the notes of this job title
	 */
	public void setNotes(String notes);

	/**
	 * Returns the specification of this job title.
	 *
	 * @return the specification of this job title
	 */
	@AutoEscape
	public String getSpecification();

	/**
	 * Sets the specification of this job title.
	 *
	 * @param specification the specification of this job title
	 */
	public void setSpecification(String specification);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JobTitle jobTitle);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JobTitle> toCacheModel();

	@Override
	public JobTitle toEscapedModel();

	@Override
	public JobTitle toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}