/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the JobTitles service. Represents a row in the &quot;job_titles&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.JobTitlesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.JobTitlesImpl}.
 * </p>
 *
 * @author rknowsys
 * @see JobTitles
 * @see com.rknowsys.eapp.hrm.model.impl.JobTitlesImpl
 * @see com.rknowsys.eapp.hrm.model.impl.JobTitlesModelImpl
 * @generated
 */
public interface JobTitlesModel extends BaseModel<JobTitles> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a job titles model instance should use the {@link JobTitles} interface instead.
	 */

	/**
	 * Returns the primary key of this job titles.
	 *
	 * @return the primary key of this job titles
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this job titles.
	 *
	 * @param primaryKey the primary key of this job titles
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this job titles.
	 *
	 * @return the ID of this job titles
	 */
	public long getId();

	/**
	 * Sets the ID of this job titles.
	 *
	 * @param id the ID of this job titles
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this job titles.
	 *
	 * @return the company ID of this job titles
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this job titles.
	 *
	 * @param companyId the company ID of this job titles
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this job titles.
	 *
	 * @return the group ID of this job titles
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this job titles.
	 *
	 * @param groupId the group ID of this job titles
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this job titles.
	 *
	 * @return the create date of this job titles
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this job titles.
	 *
	 * @param createDate the create date of this job titles
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this job titles.
	 *
	 * @return the modified date of this job titles
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this job titles.
	 *
	 * @param modifiedDate the modified date of this job titles
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this job titles.
	 *
	 * @return the user ID of this job titles
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this job titles.
	 *
	 * @param userId the user ID of this job titles
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this job titles.
	 *
	 * @return the user uuid of this job titles
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this job titles.
	 *
	 * @param userUuid the user uuid of this job titles
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the title of this job titles.
	 *
	 * @return the title of this job titles
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this job titles.
	 *
	 * @param title the title of this job titles
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this job titles.
	 *
	 * @return the description of this job titles
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this job titles.
	 *
	 * @param description the description of this job titles
	 */
	public void setDescription(String description);

	/**
	 * Returns the notes of this job titles.
	 *
	 * @return the notes of this job titles
	 */
	@AutoEscape
	public String getNotes();

	/**
	 * Sets the notes of this job titles.
	 *
	 * @param notes the notes of this job titles
	 */
	public void setNotes(String notes);

	/**
	 * Returns the specification of this job titles.
	 *
	 * @return the specification of this job titles
	 */
	@AutoEscape
	public String getSpecification();

	/**
	 * Sets the specification of this job titles.
	 *
	 * @param specification the specification of this job titles
	 */
	public void setSpecification(String specification);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JobTitles jobTitles);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JobTitles> toCacheModel();

	@Override
	public JobTitles toEscapedModel();

	@Override
	public JobTitles toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}