/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LeaveGeneral service. Represents a row in the &quot;leave_general&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.LeaveGeneralModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.LeaveGeneralImpl}.
 * </p>
 *
 * @author rknowsys
 * @see LeaveGeneral
 * @see com.rknowsys.eapp.hrm.model.impl.LeaveGeneralImpl
 * @see com.rknowsys.eapp.hrm.model.impl.LeaveGeneralModelImpl
 * @generated
 */
public interface LeaveGeneralModel extends BaseModel<LeaveGeneral> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave general model instance should use the {@link LeaveGeneral} interface instead.
	 */

	/**
	 * Returns the primary key of this leave general.
	 *
	 * @return the primary key of this leave general
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leave general.
	 *
	 * @param primaryKey the primary key of this leave general
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the leave general ID of this leave general.
	 *
	 * @return the leave general ID of this leave general
	 */
	public long getLeaveGeneralId();

	/**
	 * Sets the leave general ID of this leave general.
	 *
	 * @param leaveGeneralId the leave general ID of this leave general
	 */
	public void setLeaveGeneralId(long leaveGeneralId);

	/**
	 * Returns the company ID of this leave general.
	 *
	 * @return the company ID of this leave general
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this leave general.
	 *
	 * @param companyId the company ID of this leave general
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this leave general.
	 *
	 * @return the group ID of this leave general
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this leave general.
	 *
	 * @param groupId the group ID of this leave general
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this leave general.
	 *
	 * @return the create date of this leave general
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this leave general.
	 *
	 * @param createDate the create date of this leave general
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this leave general.
	 *
	 * @return the modified date of this leave general
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this leave general.
	 *
	 * @param modifiedDate the modified date of this leave general
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this leave general.
	 *
	 * @return the user ID of this leave general
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this leave general.
	 *
	 * @param userId the user ID of this leave general
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this leave general.
	 *
	 * @return the user uuid of this leave general
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this leave general.
	 *
	 * @param userUuid the user uuid of this leave general
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the leave type ID of this leave general.
	 *
	 * @return the leave type ID of this leave general
	 */
	public long getLeaveTypeId();

	/**
	 * Sets the leave type ID of this leave general.
	 *
	 * @param leaveTypeId the leave type ID of this leave general
	 */
	public void setLeaveTypeId(long leaveTypeId);

	/**
	 * Returns the leave period type ID of this leave general.
	 *
	 * @return the leave period type ID of this leave general
	 */
	public int getLeavePeriodTypeId();

	/**
	 * Sets the leave period type ID of this leave general.
	 *
	 * @param leavePeriodTypeId the leave period type ID of this leave general
	 */
	public void setLeavePeriodTypeId(int leavePeriodTypeId);

	/**
	 * Returns the start month of this leave general.
	 *
	 * @return the start month of this leave general
	 */
	public int getStartMonth();

	/**
	 * Sets the start month of this leave general.
	 *
	 * @param startMonth the start month of this leave general
	 */
	public void setStartMonth(int startMonth);

	/**
	 * Returns the start day of month of this leave general.
	 *
	 * @return the start day of month of this leave general
	 */
	public int getStartDayOfMonth();

	/**
	 * Sets the start day of month of this leave general.
	 *
	 * @param startDayOfMonth the start day of month of this leave general
	 */
	public void setStartDayOfMonth(int startDayOfMonth);

	/**
	 * Returns the duration of this leave general.
	 *
	 * @return the duration of this leave general
	 */
	@AutoEscape
	public String getDuration();

	/**
	 * Sets the duration of this leave general.
	 *
	 * @param duration the duration of this leave general
	 */
	public void setDuration(String duration);

	/**
	 * Returns the if employees can apply of this leave general.
	 *
	 * @return the if employees can apply of this leave general
	 */
	public boolean getIfEmployeesCanApply();

	/**
	 * Returns <code>true</code> if this leave general is if employees can apply.
	 *
	 * @return <code>true</code> if this leave general is if employees can apply; <code>false</code> otherwise
	 */
	public boolean isIfEmployeesCanApply();

	/**
	 * Sets whether this leave general is if employees can apply.
	 *
	 * @param ifEmployeesCanApply the if employees can apply of this leave general
	 */
	public void setIfEmployeesCanApply(boolean ifEmployeesCanApply);

	/**
	 * Returns the if admin can assign of this leave general.
	 *
	 * @return the if admin can assign of this leave general
	 */
	public boolean getIfAdminCanAssign();

	/**
	 * Returns <code>true</code> if this leave general is if admin can assign.
	 *
	 * @return <code>true</code> if this leave general is if admin can assign; <code>false</code> otherwise
	 */
	public boolean isIfAdminCanAssign();

	/**
	 * Sets whether this leave general is if admin can assign.
	 *
	 * @param ifAdminCanAssign the if admin can assign of this leave general
	 */
	public void setIfAdminCanAssign(boolean ifAdminCanAssign);

	/**
	 * Returns the if admin can manage entitlements of this leave general.
	 *
	 * @return the if admin can manage entitlements of this leave general
	 */
	public boolean getIfAdminCanManageEntitlements();

	/**
	 * Returns <code>true</code> if this leave general is if admin can manage entitlements.
	 *
	 * @return <code>true</code> if this leave general is if admin can manage entitlements; <code>false</code> otherwise
	 */
	public boolean isIfAdminCanManageEntitlements();

	/**
	 * Sets whether this leave general is if admin can manage entitlements.
	 *
	 * @param ifAdminCanManageEntitlements the if admin can manage entitlements of this leave general
	 */
	public void setIfAdminCanManageEntitlements(
		boolean ifAdminCanManageEntitlements);

	/**
	 * Returns the if leave accruable of this leave general.
	 *
	 * @return the if leave accruable of this leave general
	 */
	public boolean getIfLeaveAccruable();

	/**
	 * Returns <code>true</code> if this leave general is if leave accruable.
	 *
	 * @return <code>true</code> if this leave general is if leave accruable; <code>false</code> otherwise
	 */
	public boolean isIfLeaveAccruable();

	/**
	 * Sets whether this leave general is if leave accruable.
	 *
	 * @param ifLeaveAccruable the if leave accruable of this leave general
	 */
	public void setIfLeaveAccruable(boolean ifLeaveAccruable);

	/**
	 * Returns the if carry forwardable of this leave general.
	 *
	 * @return the if carry forwardable of this leave general
	 */
	public boolean getIfCarryForwardable();

	/**
	 * Returns <code>true</code> if this leave general is if carry forwardable.
	 *
	 * @return <code>true</code> if this leave general is if carry forwardable; <code>false</code> otherwise
	 */
	public boolean isIfCarryForwardable();

	/**
	 * Sets whether this leave general is if carry forwardable.
	 *
	 * @param ifCarryForwardable the if carry forwardable of this leave general
	 */
	public void setIfCarryForwardable(boolean ifCarryForwardable);

	/**
	 * Returns the show project balance of this leave general.
	 *
	 * @return the show project balance of this leave general
	 */
	public boolean getShowProjectBalance();

	/**
	 * Returns <code>true</code> if this leave general is show project balance.
	 *
	 * @return <code>true</code> if this leave general is show project balance; <code>false</code> otherwise
	 */
	public boolean isShowProjectBalance();

	/**
	 * Sets whether this leave general is show project balance.
	 *
	 * @param showProjectBalance the show project balance of this leave general
	 */
	public void setShowProjectBalance(boolean showProjectBalance);

	/**
	 * Returns the enable attachment of this leave general.
	 *
	 * @return the enable attachment of this leave general
	 */
	public boolean getEnableAttachment();

	/**
	 * Returns <code>true</code> if this leave general is enable attachment.
	 *
	 * @return <code>true</code> if this leave general is enable attachment; <code>false</code> otherwise
	 */
	public boolean isEnableAttachment();

	/**
	 * Sets whether this leave general is enable attachment.
	 *
	 * @param enableAttachment the enable attachment of this leave general
	 */
	public void setEnableAttachment(boolean enableAttachment);

	/**
	 * Returns the is attachment mandatory of this leave general.
	 *
	 * @return the is attachment mandatory of this leave general
	 */
	public boolean getIsAttachmentMandatory();

	/**
	 * Returns <code>true</code> if this leave general is is attachment mandatory.
	 *
	 * @return <code>true</code> if this leave general is is attachment mandatory; <code>false</code> otherwise
	 */
	public boolean isIsAttachmentMandatory();

	/**
	 * Sets whether this leave general is is attachment mandatory.
	 *
	 * @param isAttachmentMandatory the is attachment mandatory of this leave general
	 */
	public void setIsAttachmentMandatory(boolean isAttachmentMandatory);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.rknowsys.eapp.hrm.model.LeaveGeneral leaveGeneral);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rknowsys.eapp.hrm.model.LeaveGeneral> toCacheModel();

	@Override
	public com.rknowsys.eapp.hrm.model.LeaveGeneral toEscapedModel();

	@Override
	public com.rknowsys.eapp.hrm.model.LeaveGeneral toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}