/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LeaveTypeApplicability service. Represents a row in the &quot;leave_type_applicability&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.LeaveTypeApplicabilityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.LeaveTypeApplicabilityImpl}.
 * </p>
 *
 * @author rknowsys
 * @see LeaveTypeApplicability
 * @see com.rknowsys.eapp.hrm.model.impl.LeaveTypeApplicabilityImpl
 * @see com.rknowsys.eapp.hrm.model.impl.LeaveTypeApplicabilityModelImpl
 * @generated
 */
public interface LeaveTypeApplicabilityModel extends BaseModel<LeaveTypeApplicability> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave type applicability model instance should use the {@link LeaveTypeApplicability} interface instead.
	 */

	/**
	 * Returns the primary key of this leave type applicability.
	 *
	 * @return the primary key of this leave type applicability
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leave type applicability.
	 *
	 * @param primaryKey the primary key of this leave type applicability
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the leave type applicability ID of this leave type applicability.
	 *
	 * @return the leave type applicability ID of this leave type applicability
	 */
	public long getLeaveTypeApplicabilityId();

	/**
	 * Sets the leave type applicability ID of this leave type applicability.
	 *
	 * @param leaveTypeApplicabilityId the leave type applicability ID of this leave type applicability
	 */
	public void setLeaveTypeApplicabilityId(long leaveTypeApplicabilityId);

	/**
	 * Returns the company ID of this leave type applicability.
	 *
	 * @return the company ID of this leave type applicability
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this leave type applicability.
	 *
	 * @param companyId the company ID of this leave type applicability
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this leave type applicability.
	 *
	 * @return the group ID of this leave type applicability
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this leave type applicability.
	 *
	 * @param groupId the group ID of this leave type applicability
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this leave type applicability.
	 *
	 * @return the create date of this leave type applicability
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this leave type applicability.
	 *
	 * @param createDate the create date of this leave type applicability
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this leave type applicability.
	 *
	 * @return the modified date of this leave type applicability
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this leave type applicability.
	 *
	 * @param modifiedDate the modified date of this leave type applicability
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this leave type applicability.
	 *
	 * @return the user ID of this leave type applicability
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this leave type applicability.
	 *
	 * @param userId the user ID of this leave type applicability
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this leave type applicability.
	 *
	 * @return the user uuid of this leave type applicability
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this leave type applicability.
	 *
	 * @param userUuid the user uuid of this leave type applicability
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the leave type ID of this leave type applicability.
	 *
	 * @return the leave type ID of this leave type applicability
	 */
	public long getLeaveTypeId();

	/**
	 * Sets the leave type ID of this leave type applicability.
	 *
	 * @param leaveTypeId the leave type ID of this leave type applicability
	 */
	public void setLeaveTypeId(long leaveTypeId);

	/**
	 * Returns the if years of service criterion applicable of this leave type applicability.
	 *
	 * @return the if years of service criterion applicable of this leave type applicability
	 */
	public boolean getIfYearsOfServiceCriterionApplicable();

	/**
	 * Returns <code>true</code> if this leave type applicability is if years of service criterion applicable.
	 *
	 * @return <code>true</code> if this leave type applicability is if years of service criterion applicable; <code>false</code> otherwise
	 */
	public boolean isIfYearsOfServiceCriterionApplicable();

	/**
	 * Sets whether this leave type applicability is if years of service criterion applicable.
	 *
	 * @param ifYearsOfServiceCriterionApplicable the if years of service criterion applicable of this leave type applicability
	 */
	public void setIfYearsOfServiceCriterionApplicable(
		boolean ifYearsOfServiceCriterionApplicable);

	/**
	 * Returns the min years of service of this leave type applicability.
	 *
	 * @return the min years of service of this leave type applicability
	 */
	@AutoEscape
	public String getMinYearsOfService();

	/**
	 * Sets the min years of service of this leave type applicability.
	 *
	 * @param minYearsOfService the min years of service of this leave type applicability
	 */
	public void setMinYearsOfService(String minYearsOfService);

	/**
	 * Returns the max years of service of this leave type applicability.
	 *
	 * @return the max years of service of this leave type applicability
	 */
	@AutoEscape
	public String getMaxYearsOfService();

	/**
	 * Sets the max years of service of this leave type applicability.
	 *
	 * @param maxYearsOfService the max years of service of this leave type applicability
	 */
	public void setMaxYearsOfService(String maxYearsOfService);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LeaveTypeApplicability leaveTypeApplicability);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LeaveTypeApplicability> toCacheModel();

	@Override
	public LeaveTypeApplicability toEscapedModel();

	@Override
	public LeaveTypeApplicability toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}