/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Locations service. Represents a row in the &quot;locations&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.LocationsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.LocationsImpl}.
 * </p>
 *
 * @author rknowsys
 * @see Locations
 * @see com.rknowsys.eapp.hrm.model.impl.LocationsImpl
 * @see com.rknowsys.eapp.hrm.model.impl.LocationsModelImpl
 * @generated
 */
public interface LocationsModel extends BaseModel<Locations> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a locations model instance should use the {@link Locations} interface instead.
	 */

	/**
	 * Returns the primary key of this locations.
	 *
	 * @return the primary key of this locations
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this locations.
	 *
	 * @param primaryKey the primary key of this locations
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this locations.
	 *
	 * @return the ID of this locations
	 */
	public long getId();

	/**
	 * Sets the ID of this locations.
	 *
	 * @param id the ID of this locations
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this locations.
	 *
	 * @return the company ID of this locations
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this locations.
	 *
	 * @param companyId the company ID of this locations
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this locations.
	 *
	 * @return the group ID of this locations
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this locations.
	 *
	 * @param groupId the group ID of this locations
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this locations.
	 *
	 * @return the create date of this locations
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this locations.
	 *
	 * @param createDate the create date of this locations
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this locations.
	 *
	 * @return the modified date of this locations
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this locations.
	 *
	 * @param modifiedDate the modified date of this locations
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this locations.
	 *
	 * @return the user ID of this locations
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this locations.
	 *
	 * @param userId the user ID of this locations
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this locations.
	 *
	 * @return the user uuid of this locations
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this locations.
	 *
	 * @param userUuid the user uuid of this locations
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the name of this locations.
	 *
	 * @return the name of this locations
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this locations.
	 *
	 * @param name the name of this locations
	 */
	public void setName(String name);

	/**
	 * Returns the country of this locations.
	 *
	 * @return the country of this locations
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this locations.
	 *
	 * @param country the country of this locations
	 */
	public void setCountry(String country);

	/**
	 * Returns the state of this locations.
	 *
	 * @return the state of this locations
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this locations.
	 *
	 * @param state the state of this locations
	 */
	public void setState(String state);

	/**
	 * Returns the city of this locations.
	 *
	 * @return the city of this locations
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this locations.
	 *
	 * @param city the city of this locations
	 */
	public void setCity(String city);

	/**
	 * Returns the address of this locations.
	 *
	 * @return the address of this locations
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this locations.
	 *
	 * @param address the address of this locations
	 */
	public void setAddress(String address);

	/**
	 * Returns the postalcode of this locations.
	 *
	 * @return the postalcode of this locations
	 */
	@AutoEscape
	public String getPostalcode();

	/**
	 * Sets the postalcode of this locations.
	 *
	 * @param postalcode the postalcode of this locations
	 */
	public void setPostalcode(String postalcode);

	/**
	 * Returns the phone of this locations.
	 *
	 * @return the phone of this locations
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this locations.
	 *
	 * @param phone the phone of this locations
	 */
	public void setPhone(String phone);

	/**
	 * Returns the fax of this locations.
	 *
	 * @return the fax of this locations
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this locations.
	 *
	 * @param fax the fax of this locations
	 */
	public void setFax(String fax);

	/**
	 * Returns the notes of this locations.
	 *
	 * @return the notes of this locations
	 */
	@AutoEscape
	public String getNotes();

	/**
	 * Sets the notes of this locations.
	 *
	 * @param notes the notes of this locations
	 */
	public void setNotes(String notes);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Locations locations);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Locations> toCacheModel();

	@Override
	public Locations toEscapedModel();

	@Override
	public Locations toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}