/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the News service. Represents a row in the &quot;news&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.NewsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.NewsImpl}.
 * </p>
 *
 * @author rknowsys
 * @see News
 * @see com.rknowsys.eapp.hrm.model.impl.NewsImpl
 * @see com.rknowsys.eapp.hrm.model.impl.NewsModelImpl
 * @generated
 */
public interface NewsModel extends BaseModel<News> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a news model instance should use the {@link News} interface instead.
	 */

	/**
	 * Returns the primary key of this news.
	 *
	 * @return the primary key of this news
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this news.
	 *
	 * @param primaryKey the primary key of this news
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the news ID of this news.
	 *
	 * @return the news ID of this news
	 */
	public long getNewsId();

	/**
	 * Sets the news ID of this news.
	 *
	 * @param newsId the news ID of this news
	 */
	public void setNewsId(long newsId);

	/**
	 * Returns the company ID of this news.
	 *
	 * @return the company ID of this news
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this news.
	 *
	 * @param companyId the company ID of this news
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this news.
	 *
	 * @return the group ID of this news
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this news.
	 *
	 * @param groupId the group ID of this news
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this news.
	 *
	 * @return the create date of this news
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this news.
	 *
	 * @param createDate the create date of this news
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this news.
	 *
	 * @return the modified date of this news
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this news.
	 *
	 * @param modifiedDate the modified date of this news
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this news.
	 *
	 * @return the user ID of this news
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this news.
	 *
	 * @param userId the user ID of this news
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this news.
	 *
	 * @return the user uuid of this news
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this news.
	 *
	 * @param userUuid the user uuid of this news
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the topic of this news.
	 *
	 * @return the topic of this news
	 */
	@AutoEscape
	public String getTopic();

	/**
	 * Sets the topic of this news.
	 *
	 * @param topic the topic of this news
	 */
	public void setTopic(String topic);

	/**
	 * Returns the description of this news.
	 *
	 * @return the description of this news
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this news.
	 *
	 * @param description the description of this news
	 */
	public void setDescription(String description);

	/**
	 * Returns the publish to of this news.
	 *
	 * @return the publish to of this news
	 */
	@AutoEscape
	public String getPublishTo();

	/**
	 * Sets the publish to of this news.
	 *
	 * @param publishTo the publish to of this news
	 */
	public void setPublishTo(String publishTo);

	/**
	 * Returns the publish date of this news.
	 *
	 * @return the publish date of this news
	 */
	public Date getPublishDate();

	/**
	 * Sets the publish date of this news.
	 *
	 * @param publishDate the publish date of this news
	 */
	public void setPublishDate(Date publishDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(News news);

	@Override
	public int hashCode();

	@Override
	public CacheModel<News> toCacheModel();

	@Override
	public News toEscapedModel();

	@Override
	public News toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}