/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Organization service. Represents a row in the &quot;hrm_Organization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.OrganizationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.OrganizationImpl}.
 * </p>
 *
 * @author rknowsys
 * @see Organization
 * @see com.rknowsys.eapp.hrm.model.impl.OrganizationImpl
 * @see com.rknowsys.eapp.hrm.model.impl.OrganizationModelImpl
 * @generated
 */
public interface OrganizationModel extends BaseModel<Organization> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a organization model instance should use the {@link Organization} interface instead.
	 */

	/**
	 * Returns the primary key of this organization.
	 *
	 * @return the primary key of this organization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this organization.
	 *
	 * @param primaryKey the primary key of this organization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the organization ID of this organization.
	 *
	 * @return the organization ID of this organization
	 */
	public long getOrganizationId();

	/**
	 * Sets the organization ID of this organization.
	 *
	 * @param organizationId the organization ID of this organization
	 */
	public void setOrganizationId(long organizationId);

	/**
	 * Returns the group ID of this organization.
	 *
	 * @return the group ID of this organization
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this organization.
	 *
	 * @param groupId the group ID of this organization
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this organization.
	 *
	 * @return the company ID of this organization
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this organization.
	 *
	 * @param companyId the company ID of this organization
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this organization.
	 *
	 * @return the user ID of this organization
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this organization.
	 *
	 * @param userId the user ID of this organization
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this organization.
	 *
	 * @return the user uuid of this organization
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this organization.
	 *
	 * @param userUuid the user uuid of this organization
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this organization.
	 *
	 * @return the create date of this organization
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this organization.
	 *
	 * @param createDate the create date of this organization
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this organization.
	 *
	 * @return the modified date of this organization
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this organization.
	 *
	 * @param modifiedDate the modified date of this organization
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the organization name of this organization.
	 *
	 * @return the organization name of this organization
	 */
	@AutoEscape
	public String getOrganizationName();

	/**
	 * Sets the organization name of this organization.
	 *
	 * @param organizationName the organization name of this organization
	 */
	public void setOrganizationName(String organizationName);

	/**
	 * Returns the tax ID of this organization.
	 *
	 * @return the tax ID of this organization
	 */
	@AutoEscape
	public String getTaxId();

	/**
	 * Sets the tax ID of this organization.
	 *
	 * @param taxId the tax ID of this organization
	 */
	public void setTaxId(String taxId);

	/**
	 * Returns the number of employees of this organization.
	 *
	 * @return the number of employees of this organization
	 */
	public long getNumberOfEmployees();

	/**
	 * Sets the number of employees of this organization.
	 *
	 * @param numberOfEmployees the number of employees of this organization
	 */
	public void setNumberOfEmployees(long numberOfEmployees);

	/**
	 * Returns the registration number of this organization.
	 *
	 * @return the registration number of this organization
	 */
	@AutoEscape
	public String getRegistrationNumber();

	/**
	 * Sets the registration number of this organization.
	 *
	 * @param registrationNumber the registration number of this organization
	 */
	public void setRegistrationNumber(String registrationNumber);

	/**
	 * Returns the phone of this organization.
	 *
	 * @return the phone of this organization
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this organization.
	 *
	 * @param phone the phone of this organization
	 */
	public void setPhone(String phone);

	/**
	 * Returns the fax of this organization.
	 *
	 * @return the fax of this organization
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this organization.
	 *
	 * @param fax the fax of this organization
	 */
	public void setFax(String fax);

	/**
	 * Returns the email of this organization.
	 *
	 * @return the email of this organization
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this organization.
	 *
	 * @param email the email of this organization
	 */
	public void setEmail(String email);

	/**
	 * Returns the address street1 of this organization.
	 *
	 * @return the address street1 of this organization
	 */
	@AutoEscape
	public String getAddressStreet1();

	/**
	 * Sets the address street1 of this organization.
	 *
	 * @param addressStreet1 the address street1 of this organization
	 */
	public void setAddressStreet1(String addressStreet1);

	/**
	 * Returns the address street2 of this organization.
	 *
	 * @return the address street2 of this organization
	 */
	@AutoEscape
	public String getAddressStreet2();

	/**
	 * Sets the address street2 of this organization.
	 *
	 * @param addressStreet2 the address street2 of this organization
	 */
	public void setAddressStreet2(String addressStreet2);

	/**
	 * Returns the city of this organization.
	 *
	 * @return the city of this organization
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this organization.
	 *
	 * @param city the city of this organization
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this organization.
	 *
	 * @return the state of this organization
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this organization.
	 *
	 * @param state the state of this organization
	 */
	public void setState(String state);

	/**
	 * Returns the postal code of this organization.
	 *
	 * @return the postal code of this organization
	 */
	@AutoEscape
	public String getPostalCode();

	/**
	 * Sets the postal code of this organization.
	 *
	 * @param postalCode the postal code of this organization
	 */
	public void setPostalCode(String postalCode);

	/**
	 * Returns the nationality ID of this organization.
	 *
	 * @return the nationality ID of this organization
	 */
	public long getNationalityId();

	/**
	 * Sets the nationality ID of this organization.
	 *
	 * @param nationalityId the nationality ID of this organization
	 */
	public void setNationalityId(long nationalityId);

	/**
	 * Returns the note of this organization.
	 *
	 * @return the note of this organization
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this organization.
	 *
	 * @param note the note of this organization
	 */
	public void setNote(String note);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Organization organization);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Organization> toCacheModel();

	@Override
	public Organization toEscapedModel();

	@Override
	public Organization toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}