/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PayGradeCurrency service. Represents a row in the &quot;pay_grade_currency&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.PayGradeCurrencyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.PayGradeCurrencyImpl}.
 * </p>
 *
 * @author rknowsys
 * @see PayGradeCurrency
 * @see com.rknowsys.eapp.hrm.model.impl.PayGradeCurrencyImpl
 * @see com.rknowsys.eapp.hrm.model.impl.PayGradeCurrencyModelImpl
 * @generated
 */
public interface PayGradeCurrencyModel extends BaseModel<PayGradeCurrency> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pay grade currency model instance should use the {@link PayGradeCurrency} interface instead.
	 */

	/**
	 * Returns the primary key of this pay grade currency.
	 *
	 * @return the primary key of this pay grade currency
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pay grade currency.
	 *
	 * @param primaryKey the primary key of this pay grade currency
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the pay grade currency ID of this pay grade currency.
	 *
	 * @return the pay grade currency ID of this pay grade currency
	 */
	public long getPayGradeCurrencyId();

	/**
	 * Sets the pay grade currency ID of this pay grade currency.
	 *
	 * @param payGradeCurrencyId the pay grade currency ID of this pay grade currency
	 */
	public void setPayGradeCurrencyId(long payGradeCurrencyId);

	/**
	 * Returns the company ID of this pay grade currency.
	 *
	 * @return the company ID of this pay grade currency
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this pay grade currency.
	 *
	 * @param companyId the company ID of this pay grade currency
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this pay grade currency.
	 *
	 * @return the group ID of this pay grade currency
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this pay grade currency.
	 *
	 * @param groupId the group ID of this pay grade currency
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this pay grade currency.
	 *
	 * @return the create date of this pay grade currency
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this pay grade currency.
	 *
	 * @param createDate the create date of this pay grade currency
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this pay grade currency.
	 *
	 * @return the modified date of this pay grade currency
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this pay grade currency.
	 *
	 * @param modifiedDate the modified date of this pay grade currency
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this pay grade currency.
	 *
	 * @return the user ID of this pay grade currency
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this pay grade currency.
	 *
	 * @param userId the user ID of this pay grade currency
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this pay grade currency.
	 *
	 * @return the user uuid of this pay grade currency
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this pay grade currency.
	 *
	 * @param userUuid the user uuid of this pay grade currency
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the pay grade ID of this pay grade currency.
	 *
	 * @return the pay grade ID of this pay grade currency
	 */
	public long getPayGradeId();

	/**
	 * Sets the pay grade ID of this pay grade currency.
	 *
	 * @param payGradeId the pay grade ID of this pay grade currency
	 */
	public void setPayGradeId(long payGradeId);

	/**
	 * Returns the currency of this pay grade currency.
	 *
	 * @return the currency of this pay grade currency
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this pay grade currency.
	 *
	 * @param currency the currency of this pay grade currency
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the min salary of this pay grade currency.
	 *
	 * @return the min salary of this pay grade currency
	 */
	public long getMinSalary();

	/**
	 * Sets the min salary of this pay grade currency.
	 *
	 * @param minSalary the min salary of this pay grade currency
	 */
	public void setMinSalary(long minSalary);

	/**
	 * Returns the max salary of this pay grade currency.
	 *
	 * @return the max salary of this pay grade currency
	 */
	public long getMaxSalary();

	/**
	 * Sets the max salary of this pay grade currency.
	 *
	 * @param maxSalary the max salary of this pay grade currency
	 */
	public void setMaxSalary(long maxSalary);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rknowsys.eapp.hrm.model.PayGradeCurrency payGradeCurrency);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rknowsys.eapp.hrm.model.PayGradeCurrency> toCacheModel();

	@Override
	public com.rknowsys.eapp.hrm.model.PayGradeCurrency toEscapedModel();

	@Override
	public com.rknowsys.eapp.hrm.model.PayGradeCurrency toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}