/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Qualification service. Represents a row in the &quot;hrm_Qualification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.QualificationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.QualificationImpl}.
 * </p>
 *
 * @author rknowsys
 * @see Qualification
 * @see com.rknowsys.eapp.hrm.model.impl.QualificationImpl
 * @see com.rknowsys.eapp.hrm.model.impl.QualificationModelImpl
 * @generated
 */
public interface QualificationModel extends BaseModel<Qualification> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a qualification model instance should use the {@link Qualification} interface instead.
	 */

	/**
	 * Returns the primary key of this qualification.
	 *
	 * @return the primary key of this qualification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this qualification.
	 *
	 * @param primaryKey the primary key of this qualification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this qualification.
	 *
	 * @return the ID of this qualification
	 */
	public long getId();

	/**
	 * Sets the ID of this qualification.
	 *
	 * @param id the ID of this qualification
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this qualification.
	 *
	 * @return the group ID of this qualification
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this qualification.
	 *
	 * @param groupId the group ID of this qualification
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this qualification.
	 *
	 * @return the company ID of this qualification
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this qualification.
	 *
	 * @param companyId the company ID of this qualification
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this qualification.
	 *
	 * @return the user ID of this qualification
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this qualification.
	 *
	 * @param userId the user ID of this qualification
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this qualification.
	 *
	 * @return the user uuid of this qualification
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this qualification.
	 *
	 * @param userUuid the user uuid of this qualification
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this qualification.
	 *
	 * @return the create date of this qualification
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this qualification.
	 *
	 * @param createDate the create date of this qualification
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this qualification.
	 *
	 * @return the modified date of this qualification
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this qualification.
	 *
	 * @param modifiedDate the modified date of this qualification
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Qualification qualification);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Qualification> toCacheModel();

	@Override
	public Qualification toEscapedModel();

	@Override
	public Qualification toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}