/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SubUnit service. Represents a row in the &quot;sub_unit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.SubUnitModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.SubUnitImpl}.
 * </p>
 *
 * @author rknowsys
 * @see SubUnit
 * @see com.rknowsys.eapp.hrm.model.impl.SubUnitImpl
 * @see com.rknowsys.eapp.hrm.model.impl.SubUnitModelImpl
 * @generated
 */
public interface SubUnitModel extends BaseModel<SubUnit> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a SubUnit model instance should use the {@link SubUnit} interface instead.
	 */

	/**
	 * Returns the primary key of this SubUnit.
	 *
	 * @return the primary key of this SubUnit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this SubUnit.
	 *
	 * @param primaryKey the primary key of this SubUnit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sub unit ID of this SubUnit.
	 *
	 * @return the sub unit ID of this SubUnit
	 */
	public long getSubUnitId();

	/**
	 * Sets the sub unit ID of this SubUnit.
	 *
	 * @param subUnitId the sub unit ID of this SubUnit
	 */
	public void setSubUnitId(long subUnitId);

	/**
	 * Returns the name of this SubUnit.
	 *
	 * @return the name of this SubUnit
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this SubUnit.
	 *
	 * @param name the name of this SubUnit
	 */
	public void setName(String name);

	/**
	 * Returns the description of this SubUnit.
	 *
	 * @return the description of this SubUnit
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this SubUnit.
	 *
	 * @param description the description of this SubUnit
	 */
	public void setDescription(String description);

	/**
	 * Returns the group ID of this SubUnit.
	 *
	 * @return the group ID of this SubUnit
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this SubUnit.
	 *
	 * @param groupId the group ID of this SubUnit
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this SubUnit.
	 *
	 * @return the company ID of this SubUnit
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this SubUnit.
	 *
	 * @param companyId the company ID of this SubUnit
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this SubUnit.
	 *
	 * @return the user ID of this SubUnit
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this SubUnit.
	 *
	 * @param userId the user ID of this SubUnit
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this SubUnit.
	 *
	 * @return the user uuid of this SubUnit
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this SubUnit.
	 *
	 * @param userUuid the user uuid of this SubUnit
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this SubUnit.
	 *
	 * @return the create date of this SubUnit
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this SubUnit.
	 *
	 * @param createDate the create date of this SubUnit
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this SubUnit.
	 *
	 * @return the modified date of this SubUnit
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this SubUnit.
	 *
	 * @param modifiedDate the modified date of this SubUnit
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SubUnit subUnit);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SubUnit> toCacheModel();

	@Override
	public SubUnit toEscapedModel();

	@Override
	public SubUnit toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}