/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Supervisor service. Represents a row in the &quot;supervisor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.SupervisorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.SupervisorImpl}.
 * </p>
 *
 * @author rknowsys
 * @see Supervisor
 * @see com.rknowsys.eapp.hrm.model.impl.SupervisorImpl
 * @see com.rknowsys.eapp.hrm.model.impl.SupervisorModelImpl
 * @generated
 */
public interface SupervisorModel extends BaseModel<Supervisor>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Supervisor model instance should use the {@link Supervisor} interface instead.
	 */

	/**
	 * Returns the primary key of this Supervisor.
	 *
	 * @return the primary key of this Supervisor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Supervisor.
	 *
	 * @param primaryKey the primary key of this Supervisor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the supervisor ID of this Supervisor.
	 *
	 * @return the supervisor ID of this Supervisor
	 */
	public long getSupervisorId();

	/**
	 * Sets the supervisor ID of this Supervisor.
	 *
	 * @param supervisorId the supervisor ID of this Supervisor
	 */
	public void setSupervisorId(long supervisorId);

	/**
	 * Returns the employee ID of this Supervisor.
	 *
	 * @return the employee ID of this Supervisor
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this Supervisor.
	 *
	 * @param employeeId the employee ID of this Supervisor
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this Supervisor.
	 *
	 * @return the group ID of this Supervisor
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this Supervisor.
	 *
	 * @param groupId the group ID of this Supervisor
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this Supervisor.
	 *
	 * @return the company ID of this Supervisor
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this Supervisor.
	 *
	 * @param companyId the company ID of this Supervisor
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this Supervisor.
	 *
	 * @return the user ID of this Supervisor
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this Supervisor.
	 *
	 * @param userId the user ID of this Supervisor
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this Supervisor.
	 *
	 * @return the user uuid of this Supervisor
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this Supervisor.
	 *
	 * @param userUuid the user uuid of this Supervisor
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this Supervisor.
	 *
	 * @return the user name of this Supervisor
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this Supervisor.
	 *
	 * @param userName the user name of this Supervisor
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this Supervisor.
	 *
	 * @return the create date of this Supervisor
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this Supervisor.
	 *
	 * @param createDate the create date of this Supervisor
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this Supervisor.
	 *
	 * @return the modified date of this Supervisor
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this Supervisor.
	 *
	 * @param modifiedDate the modified date of this Supervisor
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the reporting method of this Supervisor.
	 *
	 * @return the reporting method of this Supervisor
	 */
	public long getReportingMethod();

	/**
	 * Sets the reporting method of this Supervisor.
	 *
	 * @param reportingMethod the reporting method of this Supervisor
	 */
	public void setReportingMethod(long reportingMethod);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Supervisor supervisor);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Supervisor> toCacheModel();

	@Override
	public Supervisor toEscapedModel();

	@Override
	public Supervisor toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}