/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WorkShiftUser service. Represents a row in the &quot;work_shift_user&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.WorkShiftUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.WorkShiftUserImpl}.
 * </p>
 *
 * @author rknowsys
 * @see WorkShiftUser
 * @see com.rknowsys.eapp.hrm.model.impl.WorkShiftUserImpl
 * @see com.rknowsys.eapp.hrm.model.impl.WorkShiftUserModelImpl
 * @generated
 */
public interface WorkShiftUserModel extends BaseModel<WorkShiftUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a work shift user model instance should use the {@link WorkShiftUser} interface instead.
	 */

	/**
	 * Returns the primary key of this work shift user.
	 *
	 * @return the primary key of this work shift user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this work shift user.
	 *
	 * @param primaryKey the primary key of this work shift user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the work shift user ID of this work shift user.
	 *
	 * @return the work shift user ID of this work shift user
	 */
	public long getWorkShiftUserId();

	/**
	 * Sets the work shift user ID of this work shift user.
	 *
	 * @param workShiftUserId the work shift user ID of this work shift user
	 */
	public void setWorkShiftUserId(long workShiftUserId);

	/**
	 * Returns the work shift user uuid of this work shift user.
	 *
	 * @return the work shift user uuid of this work shift user
	 * @throws SystemException if a system exception occurred
	 */
	public String getWorkShiftUserUuid() throws SystemException;

	/**
	 * Sets the work shift user uuid of this work shift user.
	 *
	 * @param workShiftUserUuid the work shift user uuid of this work shift user
	 */
	public void setWorkShiftUserUuid(String workShiftUserUuid);

	/**
	 * Returns the company ID of this work shift user.
	 *
	 * @return the company ID of this work shift user
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this work shift user.
	 *
	 * @param companyId the company ID of this work shift user
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this work shift user.
	 *
	 * @return the group ID of this work shift user
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this work shift user.
	 *
	 * @param groupId the group ID of this work shift user
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this work shift user.
	 *
	 * @return the create date of this work shift user
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this work shift user.
	 *
	 * @param createDate the create date of this work shift user
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this work shift user.
	 *
	 * @return the modified date of this work shift user
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this work shift user.
	 *
	 * @param modifiedDate the modified date of this work shift user
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this work shift user.
	 *
	 * @return the user ID of this work shift user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this work shift user.
	 *
	 * @param userId the user ID of this work shift user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this work shift user.
	 *
	 * @return the user uuid of this work shift user
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this work shift user.
	 *
	 * @param userUuid the user uuid of this work shift user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the emp ID of this work shift user.
	 *
	 * @return the emp ID of this work shift user
	 */
	public long getEmpId();

	/**
	 * Sets the emp ID of this work shift user.
	 *
	 * @param empId the emp ID of this work shift user
	 */
	public void setEmpId(long empId);

	/**
	 * Returns the shift ID of this work shift user.
	 *
	 * @return the shift ID of this work shift user
	 */
	public long getShiftId();

	/**
	 * Sets the shift ID of this work shift user.
	 *
	 * @param shiftId the shift ID of this work shift user
	 */
	public void setShiftId(long shiftId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WorkShiftUser workShiftUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WorkShiftUser> toCacheModel();

	@Override
	public WorkShiftUser toEscapedModel();

	@Override
	public WorkShiftUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}