/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WorkWeek service. Represents a row in the &quot;workweek&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.WorkWeekModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.WorkWeekImpl}.
 * </p>
 *
 * @author rknowsys
 * @see WorkWeek
 * @see com.rknowsys.eapp.hrm.model.impl.WorkWeekImpl
 * @see com.rknowsys.eapp.hrm.model.impl.WorkWeekModelImpl
 * @generated
 */
public interface WorkWeekModel extends BaseModel<WorkWeek>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a WorkWeek model instance should use the {@link WorkWeek} interface instead.
	 */

	/**
	 * Returns the primary key of this WorkWeek.
	 *
	 * @return the primary key of this WorkWeek
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this WorkWeek.
	 *
	 * @param primaryKey the primary key of this WorkWeek
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the work week ID of this WorkWeek.
	 *
	 * @return the work week ID of this WorkWeek
	 */
	public long getWorkWeekId();

	/**
	 * Sets the work week ID of this WorkWeek.
	 *
	 * @param workWeekId the work week ID of this WorkWeek
	 */
	public void setWorkWeekId(long workWeekId);

	/**
	 * Returns the nationality ID of this WorkWeek.
	 *
	 * @return the nationality ID of this WorkWeek
	 */
	public long getNationalityId();

	/**
	 * Sets the nationality ID of this WorkWeek.
	 *
	 * @param nationalityId the nationality ID of this WorkWeek
	 */
	public void setNationalityId(long nationalityId);

	/**
	 * Returns the monday work schedule of this WorkWeek.
	 *
	 * @return the monday work schedule of this WorkWeek
	 */
	public int getMondayWorkSchedule();

	/**
	 * Sets the monday work schedule of this WorkWeek.
	 *
	 * @param mondayWorkSchedule the monday work schedule of this WorkWeek
	 */
	public void setMondayWorkSchedule(int mondayWorkSchedule);

	/**
	 * Returns the tuesday work schedule of this WorkWeek.
	 *
	 * @return the tuesday work schedule of this WorkWeek
	 */
	public int getTuesdayWorkSchedule();

	/**
	 * Sets the tuesday work schedule of this WorkWeek.
	 *
	 * @param tuesdayWorkSchedule the tuesday work schedule of this WorkWeek
	 */
	public void setTuesdayWorkSchedule(int tuesdayWorkSchedule);

	/**
	 * Returns the wednesday work schedule of this WorkWeek.
	 *
	 * @return the wednesday work schedule of this WorkWeek
	 */
	public int getWednesdayWorkSchedule();

	/**
	 * Sets the wednesday work schedule of this WorkWeek.
	 *
	 * @param wednesdayWorkSchedule the wednesday work schedule of this WorkWeek
	 */
	public void setWednesdayWorkSchedule(int wednesdayWorkSchedule);

	/**
	 * Returns the thursday work schedule of this WorkWeek.
	 *
	 * @return the thursday work schedule of this WorkWeek
	 */
	public int getThursdayWorkSchedule();

	/**
	 * Sets the thursday work schedule of this WorkWeek.
	 *
	 * @param thursdayWorkSchedule the thursday work schedule of this WorkWeek
	 */
	public void setThursdayWorkSchedule(int thursdayWorkSchedule);

	/**
	 * Returns the friday work schedule of this WorkWeek.
	 *
	 * @return the friday work schedule of this WorkWeek
	 */
	public int getFridayWorkSchedule();

	/**
	 * Sets the friday work schedule of this WorkWeek.
	 *
	 * @param fridayWorkSchedule the friday work schedule of this WorkWeek
	 */
	public void setFridayWorkSchedule(int fridayWorkSchedule);

	/**
	 * Returns the saturday work schedule of this WorkWeek.
	 *
	 * @return the saturday work schedule of this WorkWeek
	 */
	public int getSaturdayWorkSchedule();

	/**
	 * Sets the saturday work schedule of this WorkWeek.
	 *
	 * @param saturdayWorkSchedule the saturday work schedule of this WorkWeek
	 */
	public void setSaturdayWorkSchedule(int saturdayWorkSchedule);

	/**
	 * Returns the sunday work schedule of this WorkWeek.
	 *
	 * @return the sunday work schedule of this WorkWeek
	 */
	public int getSundayWorkSchedule();

	/**
	 * Sets the sunday work schedule of this WorkWeek.
	 *
	 * @param sundayWorkSchedule the sunday work schedule of this WorkWeek
	 */
	public void setSundayWorkSchedule(int sundayWorkSchedule);

	/**
	 * Returns the group ID of this WorkWeek.
	 *
	 * @return the group ID of this WorkWeek
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this WorkWeek.
	 *
	 * @param groupId the group ID of this WorkWeek
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this WorkWeek.
	 *
	 * @return the company ID of this WorkWeek
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this WorkWeek.
	 *
	 * @param companyId the company ID of this WorkWeek
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this WorkWeek.
	 *
	 * @return the user ID of this WorkWeek
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this WorkWeek.
	 *
	 * @param userId the user ID of this WorkWeek
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this WorkWeek.
	 *
	 * @return the user uuid of this WorkWeek
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this WorkWeek.
	 *
	 * @param userUuid the user uuid of this WorkWeek
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this WorkWeek.
	 *
	 * @return the user name of this WorkWeek
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this WorkWeek.
	 *
	 * @param userName the user name of this WorkWeek
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this WorkWeek.
	 *
	 * @return the create date of this WorkWeek
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this WorkWeek.
	 *
	 * @param createDate the create date of this WorkWeek
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this WorkWeek.
	 *
	 * @return the modified date of this WorkWeek
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this WorkWeek.
	 *
	 * @param modifiedDate the modified date of this WorkWeek
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WorkWeek workWeek);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WorkWeek> toCacheModel();

	@Override
	public WorkWeek toEscapedModel();

	@Override
	public WorkWeek toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}