/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WorkExpCompany service. Represents a row in the &quot;work_exp_company&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.WorkExpCompanyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.WorkExpCompanyImpl}.
 * </p>
 *
 * @author rknowsys
 * @see WorkExpCompany
 * @see com.rknowsys.eapp.hrm.model.impl.WorkExpCompanyImpl
 * @see com.rknowsys.eapp.hrm.model.impl.WorkExpCompanyModelImpl
 * @generated
 */
public interface WorkExpCompanyModel extends BaseModel<WorkExpCompany> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a WorkExpCompany model instance should use the {@link WorkExpCompany} interface instead.
	 */

	/**
	 * Returns the primary key of this WorkExpCompany.
	 *
	 * @return the primary key of this WorkExpCompany
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this WorkExpCompany.
	 *
	 * @param primaryKey the primary key of this WorkExpCompany
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the work exp company ID of this WorkExpCompany.
	 *
	 * @return the work exp company ID of this WorkExpCompany
	 */
	public long getWorkExpCompanyId();

	/**
	 * Sets the work exp company ID of this WorkExpCompany.
	 *
	 * @param workExpCompanyId the work exp company ID of this WorkExpCompany
	 */
	public void setWorkExpCompanyId(long workExpCompanyId);

	/**
	 * Returns the employee ID of this WorkExpCompany.
	 *
	 * @return the employee ID of this WorkExpCompany
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this WorkExpCompany.
	 *
	 * @param employeeId the employee ID of this WorkExpCompany
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this WorkExpCompany.
	 *
	 * @return the group ID of this WorkExpCompany
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this WorkExpCompany.
	 *
	 * @param groupId the group ID of this WorkExpCompany
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this WorkExpCompany.
	 *
	 * @return the company ID of this WorkExpCompany
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this WorkExpCompany.
	 *
	 * @param companyId the company ID of this WorkExpCompany
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this WorkExpCompany.
	 *
	 * @return the user ID of this WorkExpCompany
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this WorkExpCompany.
	 *
	 * @param userId the user ID of this WorkExpCompany
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this WorkExpCompany.
	 *
	 * @return the user uuid of this WorkExpCompany
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this WorkExpCompany.
	 *
	 * @param userUuid the user uuid of this WorkExpCompany
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this WorkExpCompany.
	 *
	 * @return the create date of this WorkExpCompany
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this WorkExpCompany.
	 *
	 * @param createDate the create date of this WorkExpCompany
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this WorkExpCompany.
	 *
	 * @return the modified date of this WorkExpCompany
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this WorkExpCompany.
	 *
	 * @param modifiedDate the modified date of this WorkExpCompany
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the company of this WorkExpCompany.
	 *
	 * @return the company of this WorkExpCompany
	 */
	@AutoEscape
	public String getCompany();

	/**
	 * Sets the company of this WorkExpCompany.
	 *
	 * @param company the company of this WorkExpCompany
	 */
	public void setCompany(String company);

	/**
	 * Returns the job title of this WorkExpCompany.
	 *
	 * @return the job title of this WorkExpCompany
	 */
	@AutoEscape
	public String getJobTitle();

	/**
	 * Sets the job title of this WorkExpCompany.
	 *
	 * @param jobTitle the job title of this WorkExpCompany
	 */
	public void setJobTitle(String jobTitle);

	/**
	 * Returns the from date of this WorkExpCompany.
	 *
	 * @return the from date of this WorkExpCompany
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this WorkExpCompany.
	 *
	 * @param fromDate the from date of this WorkExpCompany
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the to date of this WorkExpCompany.
	 *
	 * @return the to date of this WorkExpCompany
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this WorkExpCompany.
	 *
	 * @param toDate the to date of this WorkExpCompany
	 */
	public void setToDate(Date toDate);

	/**
	 * Returns the comment of this WorkExpCompany.
	 *
	 * @return the comment of this WorkExpCompany
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this WorkExpCompany.
	 *
	 * @param comment the comment of this WorkExpCompany
	 */
	public void setComment(String comment);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WorkExpCompany workExpCompany);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WorkExpCompany> toCacheModel();

	@Override
	public WorkExpCompany toEscapedModel();

	@Override
	public WorkExpCompany toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}