/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WorkShift service. Represents a row in the &quot;work_shift&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rknowsys.eapp.hrm.model.impl.WorkShiftModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rknowsys.eapp.hrm.model.impl.WorkShiftImpl}.
 * </p>
 *
 * @author rknowsys
 * @see WorkShift
 * @see com.rknowsys.eapp.hrm.model.impl.WorkShiftImpl
 * @see com.rknowsys.eapp.hrm.model.impl.WorkShiftModelImpl
 * @generated
 */
public interface WorkShiftModel extends BaseModel<WorkShift> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a work shift model instance should use the {@link WorkShift} interface instead.
	 */

	/**
	 * Returns the primary key of this work shift.
	 *
	 * @return the primary key of this work shift
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this work shift.
	 *
	 * @param primaryKey the primary key of this work shift
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the shift ID of this work shift.
	 *
	 * @return the shift ID of this work shift
	 */
	public long getShiftId();

	/**
	 * Sets the shift ID of this work shift.
	 *
	 * @param shiftId the shift ID of this work shift
	 */
	public void setShiftId(long shiftId);

	/**
	 * Returns the company ID of this work shift.
	 *
	 * @return the company ID of this work shift
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this work shift.
	 *
	 * @param companyId the company ID of this work shift
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this work shift.
	 *
	 * @return the group ID of this work shift
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this work shift.
	 *
	 * @param groupId the group ID of this work shift
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the create date of this work shift.
	 *
	 * @return the create date of this work shift
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this work shift.
	 *
	 * @param createDate the create date of this work shift
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this work shift.
	 *
	 * @return the modified date of this work shift
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this work shift.
	 *
	 * @param modifiedDate the modified date of this work shift
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this work shift.
	 *
	 * @return the user ID of this work shift
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this work shift.
	 *
	 * @param userId the user ID of this work shift
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this work shift.
	 *
	 * @return the user uuid of this work shift
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this work shift.
	 *
	 * @param userUuid the user uuid of this work shift
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the shift name of this work shift.
	 *
	 * @return the shift name of this work shift
	 */
	@AutoEscape
	public String getShiftName();

	/**
	 * Sets the shift name of this work shift.
	 *
	 * @param shiftName the shift name of this work shift
	 */
	public void setShiftName(String shiftName);

	/**
	 * Returns the from work hrs of this work shift.
	 *
	 * @return the from work hrs of this work shift
	 */
	public long getFromWorkHrs();

	/**
	 * Sets the from work hrs of this work shift.
	 *
	 * @param fromWorkHrs the from work hrs of this work shift
	 */
	public void setFromWorkHrs(long fromWorkHrs);

	/**
	 * Returns the to work hrs of this work shift.
	 *
	 * @return the to work hrs of this work shift
	 */
	public long getToWorkHrs();

	/**
	 * Sets the to work hrs of this work shift.
	 *
	 * @param toWorkHrs the to work hrs of this work shift
	 */
	public void setToWorkHrs(long toWorkHrs);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WorkShift workShift);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WorkShift> toCacheModel();

	@Override
	public WorkShift toEscapedModel();

	@Override
	public WorkShift toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}