/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rknowsys.eapp.hrm.model.EmploymentStatus;
import com.rknowsys.eapp.hrm.model.EmploymentStatusModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the EmploymentStatus service. Represents a row in the &quot;employment_status&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rknowsys.eapp.hrm.model.EmploymentStatusModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmploymentStatusImpl}.
 * </p>
 *
 * @author rknowsys
 * @see EmploymentStatusImpl
 * @see com.rknowsys.eapp.hrm.model.EmploymentStatus
 * @see com.rknowsys.eapp.hrm.model.EmploymentStatusModel
 * @generated
 */
public class EmploymentStatusModelImpl extends BaseModelImpl<EmploymentStatus>
	implements EmploymentStatusModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employment status model instance should use the {@link com.rknowsys.eapp.hrm.model.EmploymentStatus} interface instead.
	 */
	public static final String TABLE_NAME = "employment_status";
	public static final Object[][] TABLE_COLUMNS = {
			{ "employmentStatusId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "employmentstatus", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table employment_status (employmentStatusId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,employmentstatus VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table employment_status";
	public static final String ORDER_BY_JPQL = " ORDER BY employmentStatus.employmentStatusId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY employment_status.employmentStatusId ASC";
	public static final String DATA_SOURCE = "hrmDataSource";
	public static final String SESSION_FACTORY = "hrmSessionFactory";
	public static final String TX_MANAGER = "hrmTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rknowsys.eapp.hrm.model.EmploymentStatus"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rknowsys.eapp.hrm.model.EmploymentStatus"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final String MAPPING_TABLE_HRM_APPLICABLE_EMPLOYMENT_STATUSES_NAME =
		"hrm_applicable_employment_statuses";
	public static final Object[][] MAPPING_TABLE_HRM_APPLICABLE_EMPLOYMENT_STATUSES_COLUMNS =
		{
			{ "leaveTypeApplicabilityId", Types.BIGINT },
			{ "employmentStatusId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_HRM_APPLICABLE_EMPLOYMENT_STATUSES_SQL_CREATE =
		"create table hrm_applicable_employment_statuses (employmentStatusId LONG not null,leaveTypeApplicabilityId LONG not null,primary key (employmentStatusId, leaveTypeApplicabilityId))";
	public static final boolean FINDER_CACHE_ENABLED_HRM_APPLICABLE_EMPLOYMENT_STATUSES =
		GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.hrm_applicable_employment_statuses"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rknowsys.eapp.hrm.model.EmploymentStatus"));

	public EmploymentStatusModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employmentStatusId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmploymentStatusId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employmentStatusId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmploymentStatus.class;
	}

	@Override
	public String getModelClassName() {
		return EmploymentStatus.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("employmentStatusId", getEmploymentStatusId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("employmentstatus", getEmploymentstatus());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long employmentStatusId = (Long)attributes.get("employmentStatusId");

		if (employmentStatusId != null) {
			setEmploymentStatusId(employmentStatusId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String employmentstatus = (String)attributes.get("employmentstatus");

		if (employmentstatus != null) {
			setEmploymentstatus(employmentstatus);
		}
	}

	@Override
	public long getEmploymentStatusId() {
		return _employmentStatusId;
	}

	@Override
	public void setEmploymentStatusId(long employmentStatusId) {
		_employmentStatusId = employmentStatusId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getEmploymentstatus() {
		if (_employmentstatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _employmentstatus;
		}
	}

	@Override
	public void setEmploymentstatus(String employmentstatus) {
		_employmentstatus = employmentstatus;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EmploymentStatus.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmploymentStatus toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EmploymentStatus)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmploymentStatusImpl employmentStatusImpl = new EmploymentStatusImpl();

		employmentStatusImpl.setEmploymentStatusId(getEmploymentStatusId());
		employmentStatusImpl.setGroupId(getGroupId());
		employmentStatusImpl.setCompanyId(getCompanyId());
		employmentStatusImpl.setUserId(getUserId());
		employmentStatusImpl.setCreateDate(getCreateDate());
		employmentStatusImpl.setModifiedDate(getModifiedDate());
		employmentStatusImpl.setEmploymentstatus(getEmploymentstatus());

		employmentStatusImpl.resetOriginalValues();

		return employmentStatusImpl;
	}

	@Override
	public int compareTo(EmploymentStatus employmentStatus) {
		long primaryKey = employmentStatus.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EmploymentStatus)) {
			return false;
		}

		EmploymentStatus employmentStatus = (EmploymentStatus)obj;

		long primaryKey = employmentStatus.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<EmploymentStatus> toCacheModel() {
		EmploymentStatusCacheModel employmentStatusCacheModel = new EmploymentStatusCacheModel();

		employmentStatusCacheModel.employmentStatusId = getEmploymentStatusId();

		employmentStatusCacheModel.groupId = getGroupId();

		employmentStatusCacheModel.companyId = getCompanyId();

		employmentStatusCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			employmentStatusCacheModel.createDate = createDate.getTime();
		}
		else {
			employmentStatusCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employmentStatusCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employmentStatusCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employmentStatusCacheModel.employmentstatus = getEmploymentstatus();

		String employmentstatus = employmentStatusCacheModel.employmentstatus;

		if ((employmentstatus != null) && (employmentstatus.length() == 0)) {
			employmentStatusCacheModel.employmentstatus = null;
		}

		return employmentStatusCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{employmentStatusId=");
		sb.append(getEmploymentStatusId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", employmentstatus=");
		sb.append(getEmploymentstatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.rknowsys.eapp.hrm.model.EmploymentStatus");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>employmentStatusId</column-name><column-value><![CDATA[");
		sb.append(getEmploymentStatusId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employmentstatus</column-name><column-value><![CDATA[");
		sb.append(getEmploymentstatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EmploymentStatus.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			EmploymentStatus.class
		};
	private long _employmentStatusId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private String _employmentstatus;
	private EmploymentStatus _escapedModel;
}