/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rknowsys.eapp.hrm.model.EmpLanguage;
import com.rknowsys.eapp.hrm.model.EmpLanguageModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the EmpLanguage service. Represents a row in the &quot;emp_language&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rknowsys.eapp.hrm.model.EmpLanguageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmpLanguageImpl}.
 * </p>
 *
 * @author rknowsys
 * @see EmpLanguageImpl
 * @see com.rknowsys.eapp.hrm.model.EmpLanguage
 * @see com.rknowsys.eapp.hrm.model.EmpLanguageModel
 * @generated
 */
public class EmpLanguageModelImpl extends BaseModelImpl<EmpLanguage>
	implements EmpLanguageModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a emp language model instance should use the {@link com.rknowsys.eapp.hrm.model.EmpLanguage} interface instead.
	 */
	public static final String TABLE_NAME = "emp_language";
	public static final Object[][] TABLE_COLUMNS = {
			{ "empLanguageId", Types.BIGINT },
			{ "employeeId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "userId", Types.BIGINT },
			{ "languageId", Types.BIGINT },
			{ "languageSkill", Types.VARCHAR },
			{ "languageFluency", Types.VARCHAR },
			{ "comments", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table emp_language (empLanguageId LONG not null primary key,employeeId LONG,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,userId LONG,languageId LONG,languageSkill VARCHAR(75) null,languageFluency VARCHAR(75) null,comments VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table emp_language";
	public static final String ORDER_BY_JPQL = " ORDER BY empLanguage.empLanguageId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY emp_language.empLanguageId ASC";
	public static final String DATA_SOURCE = "hrmDataSource";
	public static final String SESSION_FACTORY = "hrmSessionFactory";
	public static final String TX_MANAGER = "hrmTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rknowsys.eapp.hrm.model.EmpLanguage"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rknowsys.eapp.hrm.model.EmpLanguage"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rknowsys.eapp.hrm.model.EmpLanguage"),
			true);
	public static long EMPLOYEEID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long LANGUAGEID_COLUMN_BITMASK = 4L;
	public static long EMPLANGUAGEID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rknowsys.eapp.hrm.model.EmpLanguage"));

	public EmpLanguageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _empLanguageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmpLanguageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _empLanguageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmpLanguage.class;
	}

	@Override
	public String getModelClassName() {
		return EmpLanguage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("empLanguageId", getEmpLanguageId());
		attributes.put("employeeId", getEmployeeId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("userId", getUserId());
		attributes.put("languageId", getLanguageId());
		attributes.put("languageSkill", getLanguageSkill());
		attributes.put("languageFluency", getLanguageFluency());
		attributes.put("comments", getComments());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long empLanguageId = (Long)attributes.get("empLanguageId");

		if (empLanguageId != null) {
			setEmpLanguageId(empLanguageId);
		}

		Long employeeId = (Long)attributes.get("employeeId");

		if (employeeId != null) {
			setEmployeeId(employeeId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long languageId = (Long)attributes.get("languageId");

		if (languageId != null) {
			setLanguageId(languageId);
		}

		String languageSkill = (String)attributes.get("languageSkill");

		if (languageSkill != null) {
			setLanguageSkill(languageSkill);
		}

		String languageFluency = (String)attributes.get("languageFluency");

		if (languageFluency != null) {
			setLanguageFluency(languageFluency);
		}

		String comments = (String)attributes.get("comments");

		if (comments != null) {
			setComments(comments);
		}
	}

	@Override
	public long getEmpLanguageId() {
		return _empLanguageId;
	}

	@Override
	public void setEmpLanguageId(long empLanguageId) {
		_empLanguageId = empLanguageId;
	}

	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		_columnBitmask |= EMPLOYEEID_COLUMN_BITMASK;

		if (!_setOriginalEmployeeId) {
			_setOriginalEmployeeId = true;

			_originalEmployeeId = _employeeId;
		}

		_employeeId = employeeId;
	}

	public long getOriginalEmployeeId() {
		return _originalEmployeeId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public long getLanguageId() {
		return _languageId;
	}

	@Override
	public void setLanguageId(long languageId) {
		_columnBitmask |= LANGUAGEID_COLUMN_BITMASK;

		if (!_setOriginalLanguageId) {
			_setOriginalLanguageId = true;

			_originalLanguageId = _languageId;
		}

		_languageId = languageId;
	}

	public long getOriginalLanguageId() {
		return _originalLanguageId;
	}

	@Override
	public String getLanguageSkill() {
		if (_languageSkill == null) {
			return StringPool.BLANK;
		}
		else {
			return _languageSkill;
		}
	}

	@Override
	public void setLanguageSkill(String languageSkill) {
		_languageSkill = languageSkill;
	}

	@Override
	public String getLanguageFluency() {
		if (_languageFluency == null) {
			return StringPool.BLANK;
		}
		else {
			return _languageFluency;
		}
	}

	@Override
	public void setLanguageFluency(String languageFluency) {
		_languageFluency = languageFluency;
	}

	@Override
	public String getComments() {
		if (_comments == null) {
			return StringPool.BLANK;
		}
		else {
			return _comments;
		}
	}

	@Override
	public void setComments(String comments) {
		_comments = comments;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EmpLanguage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmpLanguage toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EmpLanguage)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmpLanguageImpl empLanguageImpl = new EmpLanguageImpl();

		empLanguageImpl.setEmpLanguageId(getEmpLanguageId());
		empLanguageImpl.setEmployeeId(getEmployeeId());
		empLanguageImpl.setGroupId(getGroupId());
		empLanguageImpl.setCompanyId(getCompanyId());
		empLanguageImpl.setCreateDate(getCreateDate());
		empLanguageImpl.setModifiedDate(getModifiedDate());
		empLanguageImpl.setUserId(getUserId());
		empLanguageImpl.setLanguageId(getLanguageId());
		empLanguageImpl.setLanguageSkill(getLanguageSkill());
		empLanguageImpl.setLanguageFluency(getLanguageFluency());
		empLanguageImpl.setComments(getComments());

		empLanguageImpl.resetOriginalValues();

		return empLanguageImpl;
	}

	@Override
	public int compareTo(EmpLanguage empLanguage) {
		long primaryKey = empLanguage.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EmpLanguage)) {
			return false;
		}

		EmpLanguage empLanguage = (EmpLanguage)obj;

		long primaryKey = empLanguage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		EmpLanguageModelImpl empLanguageModelImpl = this;

		empLanguageModelImpl._originalEmployeeId = empLanguageModelImpl._employeeId;

		empLanguageModelImpl._setOriginalEmployeeId = false;

		empLanguageModelImpl._originalGroupId = empLanguageModelImpl._groupId;

		empLanguageModelImpl._setOriginalGroupId = false;

		empLanguageModelImpl._originalLanguageId = empLanguageModelImpl._languageId;

		empLanguageModelImpl._setOriginalLanguageId = false;

		empLanguageModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EmpLanguage> toCacheModel() {
		EmpLanguageCacheModel empLanguageCacheModel = new EmpLanguageCacheModel();

		empLanguageCacheModel.empLanguageId = getEmpLanguageId();

		empLanguageCacheModel.employeeId = getEmployeeId();

		empLanguageCacheModel.groupId = getGroupId();

		empLanguageCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			empLanguageCacheModel.createDate = createDate.getTime();
		}
		else {
			empLanguageCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			empLanguageCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			empLanguageCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		empLanguageCacheModel.userId = getUserId();

		empLanguageCacheModel.languageId = getLanguageId();

		empLanguageCacheModel.languageSkill = getLanguageSkill();

		String languageSkill = empLanguageCacheModel.languageSkill;

		if ((languageSkill != null) && (languageSkill.length() == 0)) {
			empLanguageCacheModel.languageSkill = null;
		}

		empLanguageCacheModel.languageFluency = getLanguageFluency();

		String languageFluency = empLanguageCacheModel.languageFluency;

		if ((languageFluency != null) && (languageFluency.length() == 0)) {
			empLanguageCacheModel.languageFluency = null;
		}

		empLanguageCacheModel.comments = getComments();

		String comments = empLanguageCacheModel.comments;

		if ((comments != null) && (comments.length() == 0)) {
			empLanguageCacheModel.comments = null;
		}

		return empLanguageCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{empLanguageId=");
		sb.append(getEmpLanguageId());
		sb.append(", employeeId=");
		sb.append(getEmployeeId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", languageId=");
		sb.append(getLanguageId());
		sb.append(", languageSkill=");
		sb.append(getLanguageSkill());
		sb.append(", languageFluency=");
		sb.append(getLanguageFluency());
		sb.append(", comments=");
		sb.append(getComments());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.rknowsys.eapp.hrm.model.EmpLanguage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>empLanguageId</column-name><column-value><![CDATA[");
		sb.append(getEmpLanguageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employeeId</column-name><column-value><![CDATA[");
		sb.append(getEmployeeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>languageId</column-name><column-value><![CDATA[");
		sb.append(getLanguageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>languageSkill</column-name><column-value><![CDATA[");
		sb.append(getLanguageSkill());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>languageFluency</column-name><column-value><![CDATA[");
		sb.append(getLanguageFluency());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>comments</column-name><column-value><![CDATA[");
		sb.append(getComments());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EmpLanguage.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			EmpLanguage.class
		};
	private long _empLanguageId;
	private long _employeeId;
	private long _originalEmployeeId;
	private boolean _setOriginalEmployeeId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private long _userId;
	private String _userUuid;
	private long _languageId;
	private long _originalLanguageId;
	private boolean _setOriginalLanguageId;
	private String _languageSkill;
	private String _languageFluency;
	private String _comments;
	private long _columnBitmask;
	private EmpLanguage _escapedModel;
}