/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rknowsys.eapp.hrm.model.EmpSupervisor;
import com.rknowsys.eapp.hrm.model.EmpSupervisorModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the EmpSupervisor service. Represents a row in the &quot;emp_supervisor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rknowsys.eapp.hrm.model.EmpSupervisorModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmpSupervisorImpl}.
 * </p>
 *
 * @author rknowsys
 * @see EmpSupervisorImpl
 * @see com.rknowsys.eapp.hrm.model.EmpSupervisor
 * @see com.rknowsys.eapp.hrm.model.EmpSupervisorModel
 * @generated
 */
public class EmpSupervisorModelImpl extends BaseModelImpl<EmpSupervisor>
	implements EmpSupervisorModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a EmpSupervisor model instance should use the {@link com.rknowsys.eapp.hrm.model.EmpSupervisor} interface instead.
	 */
	public static final String TABLE_NAME = "emp_supervisor";
	public static final Object[][] TABLE_COLUMNS = {
			{ "empSupervisorId", Types.BIGINT },
			{ "employeeId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "reporterEmployeeId", Types.BIGINT },
			{ "reportingMethod", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table emp_supervisor (empSupervisorId LONG not null primary key,employeeId LONG,groupId LONG,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,reporterEmployeeId LONG,reportingMethod LONG)";
	public static final String TABLE_SQL_DROP = "drop table emp_supervisor";
	public static final String ORDER_BY_JPQL = " ORDER BY empSupervisor.empSupervisorId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY emp_supervisor.empSupervisorId ASC";
	public static final String DATA_SOURCE = "hrmDataSource";
	public static final String SESSION_FACTORY = "hrmSessionFactory";
	public static final String TX_MANAGER = "hrmTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rknowsys.eapp.hrm.model.EmpSupervisor"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rknowsys.eapp.hrm.model.EmpSupervisor"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rknowsys.eapp.hrm.model.EmpSupervisor"));

	public EmpSupervisorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _empSupervisorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmpSupervisorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _empSupervisorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmpSupervisor.class;
	}

	@Override
	public String getModelClassName() {
		return EmpSupervisor.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("empSupervisorId", getEmpSupervisorId());
		attributes.put("employeeId", getEmployeeId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("reporterEmployeeId", getReporterEmployeeId());
		attributes.put("reportingMethod", getReportingMethod());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long empSupervisorId = (Long)attributes.get("empSupervisorId");

		if (empSupervisorId != null) {
			setEmpSupervisorId(empSupervisorId);
		}

		Long employeeId = (Long)attributes.get("employeeId");

		if (employeeId != null) {
			setEmployeeId(employeeId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long reporterEmployeeId = (Long)attributes.get("reporterEmployeeId");

		if (reporterEmployeeId != null) {
			setReporterEmployeeId(reporterEmployeeId);
		}

		Long reportingMethod = (Long)attributes.get("reportingMethod");

		if (reportingMethod != null) {
			setReportingMethod(reportingMethod);
		}
	}

	@Override
	public long getEmpSupervisorId() {
		return _empSupervisorId;
	}

	@Override
	public void setEmpSupervisorId(long empSupervisorId) {
		_empSupervisorId = empSupervisorId;
	}

	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		_employeeId = employeeId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getReporterEmployeeId() {
		return _reporterEmployeeId;
	}

	@Override
	public void setReporterEmployeeId(long reporterEmployeeId) {
		_reporterEmployeeId = reporterEmployeeId;
	}

	@Override
	public long getReportingMethod() {
		return _reportingMethod;
	}

	@Override
	public void setReportingMethod(long reportingMethod) {
		_reportingMethod = reportingMethod;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EmpSupervisor.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmpSupervisor toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EmpSupervisor)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmpSupervisorImpl empSupervisorImpl = new EmpSupervisorImpl();

		empSupervisorImpl.setEmpSupervisorId(getEmpSupervisorId());
		empSupervisorImpl.setEmployeeId(getEmployeeId());
		empSupervisorImpl.setGroupId(getGroupId());
		empSupervisorImpl.setCompanyId(getCompanyId());
		empSupervisorImpl.setUserId(getUserId());
		empSupervisorImpl.setCreateDate(getCreateDate());
		empSupervisorImpl.setModifiedDate(getModifiedDate());
		empSupervisorImpl.setReporterEmployeeId(getReporterEmployeeId());
		empSupervisorImpl.setReportingMethod(getReportingMethod());

		empSupervisorImpl.resetOriginalValues();

		return empSupervisorImpl;
	}

	@Override
	public int compareTo(EmpSupervisor empSupervisor) {
		long primaryKey = empSupervisor.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EmpSupervisor)) {
			return false;
		}

		EmpSupervisor empSupervisor = (EmpSupervisor)obj;

		long primaryKey = empSupervisor.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<EmpSupervisor> toCacheModel() {
		EmpSupervisorCacheModel empSupervisorCacheModel = new EmpSupervisorCacheModel();

		empSupervisorCacheModel.empSupervisorId = getEmpSupervisorId();

		empSupervisorCacheModel.employeeId = getEmployeeId();

		empSupervisorCacheModel.groupId = getGroupId();

		empSupervisorCacheModel.companyId = getCompanyId();

		empSupervisorCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			empSupervisorCacheModel.createDate = createDate.getTime();
		}
		else {
			empSupervisorCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			empSupervisorCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			empSupervisorCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		empSupervisorCacheModel.reporterEmployeeId = getReporterEmployeeId();

		empSupervisorCacheModel.reportingMethod = getReportingMethod();

		return empSupervisorCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{empSupervisorId=");
		sb.append(getEmpSupervisorId());
		sb.append(", employeeId=");
		sb.append(getEmployeeId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", reporterEmployeeId=");
		sb.append(getReporterEmployeeId());
		sb.append(", reportingMethod=");
		sb.append(getReportingMethod());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.rknowsys.eapp.hrm.model.EmpSupervisor");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>empSupervisorId</column-name><column-value><![CDATA[");
		sb.append(getEmpSupervisorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employeeId</column-name><column-value><![CDATA[");
		sb.append(getEmployeeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>reporterEmployeeId</column-name><column-value><![CDATA[");
		sb.append(getReporterEmployeeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>reportingMethod</column-name><column-value><![CDATA[");
		sb.append(getReportingMethod());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EmpSupervisor.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			EmpSupervisor.class
		};
	private long _empSupervisorId;
	private long _employeeId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private long _reporterEmployeeId;
	private long _reportingMethod;
	private EmpSupervisor _escapedModel;
}