/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rknowsys.eapp.hrm.model.EmpSalaryComponent;
import com.rknowsys.eapp.hrm.model.EmpSalaryComponentModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the EmpSalaryComponent service. Represents a row in the &quot;emp_salary_component&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rknowsys.eapp.hrm.model.EmpSalaryComponentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmpSalaryComponentImpl}.
 * </p>
 *
 * @author rknowsys
 * @see EmpSalaryComponentImpl
 * @see com.rknowsys.eapp.hrm.model.EmpSalaryComponent
 * @see com.rknowsys.eapp.hrm.model.EmpSalaryComponentModel
 * @generated
 */
public class EmpSalaryComponentModelImpl extends BaseModelImpl<EmpSalaryComponent>
	implements EmpSalaryComponentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a emp salary component model instance should use the {@link com.rknowsys.eapp.hrm.model.EmpSalaryComponent} interface instead.
	 */
	public static final String TABLE_NAME = "emp_salary_component";
	public static final Object[][] TABLE_COLUMNS = {
			{ "empSalaryEarningId", Types.BIGINT },
			{ "empSalaryId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "userId", Types.BIGINT },
			{ "salaryComponentId", Types.BIGINT },
			{ "amount", Types.BIGINT },
			{ "effectiveDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table emp_salary_component (empSalaryEarningId LONG not null primary key,empSalaryId LONG,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,userId LONG,salaryComponentId LONG,amount LONG,effectiveDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table emp_salary_component";
	public static final String ORDER_BY_JPQL = " ORDER BY empSalaryComponent.empSalaryEarningId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY emp_salary_component.empSalaryEarningId ASC";
	public static final String DATA_SOURCE = "hrmDataSource";
	public static final String SESSION_FACTORY = "hrmSessionFactory";
	public static final String TX_MANAGER = "hrmTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rknowsys.eapp.hrm.model.EmpSalaryComponent"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rknowsys.eapp.hrm.model.EmpSalaryComponent"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rknowsys.eapp.hrm.model.EmpSalaryComponent"),
			true);
	public static long EMPSALARYEARNINGID_COLUMN_BITMASK = 1L;
	public static long EMPSALARYID_COLUMN_BITMASK = 2L;
	public static long GROUPID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rknowsys.eapp.hrm.model.EmpSalaryComponent"));

	public EmpSalaryComponentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _empSalaryEarningId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmpSalaryEarningId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _empSalaryEarningId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmpSalaryComponent.class;
	}

	@Override
	public String getModelClassName() {
		return EmpSalaryComponent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("empSalaryEarningId", getEmpSalaryEarningId());
		attributes.put("empSalaryId", getEmpSalaryId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("userId", getUserId());
		attributes.put("salaryComponentId", getSalaryComponentId());
		attributes.put("amount", getAmount());
		attributes.put("effectiveDate", getEffectiveDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long empSalaryEarningId = (Long)attributes.get("empSalaryEarningId");

		if (empSalaryEarningId != null) {
			setEmpSalaryEarningId(empSalaryEarningId);
		}

		Long empSalaryId = (Long)attributes.get("empSalaryId");

		if (empSalaryId != null) {
			setEmpSalaryId(empSalaryId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long salaryComponentId = (Long)attributes.get("salaryComponentId");

		if (salaryComponentId != null) {
			setSalaryComponentId(salaryComponentId);
		}

		Long amount = (Long)attributes.get("amount");

		if (amount != null) {
			setAmount(amount);
		}

		Date effectiveDate = (Date)attributes.get("effectiveDate");

		if (effectiveDate != null) {
			setEffectiveDate(effectiveDate);
		}
	}

	@Override
	public long getEmpSalaryEarningId() {
		return _empSalaryEarningId;
	}

	@Override
	public void setEmpSalaryEarningId(long empSalaryEarningId) {
		_columnBitmask |= EMPSALARYEARNINGID_COLUMN_BITMASK;

		if (!_setOriginalEmpSalaryEarningId) {
			_setOriginalEmpSalaryEarningId = true;

			_originalEmpSalaryEarningId = _empSalaryEarningId;
		}

		_empSalaryEarningId = empSalaryEarningId;
	}

	public long getOriginalEmpSalaryEarningId() {
		return _originalEmpSalaryEarningId;
	}

	@Override
	public long getEmpSalaryId() {
		return _empSalaryId;
	}

	@Override
	public void setEmpSalaryId(long empSalaryId) {
		_columnBitmask |= EMPSALARYID_COLUMN_BITMASK;

		if (!_setOriginalEmpSalaryId) {
			_setOriginalEmpSalaryId = true;

			_originalEmpSalaryId = _empSalaryId;
		}

		_empSalaryId = empSalaryId;
	}

	public long getOriginalEmpSalaryId() {
		return _originalEmpSalaryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public long getSalaryComponentId() {
		return _salaryComponentId;
	}

	@Override
	public void setSalaryComponentId(long salaryComponentId) {
		_salaryComponentId = salaryComponentId;
	}

	@Override
	public long getAmount() {
		return _amount;
	}

	@Override
	public void setAmount(long amount) {
		_amount = amount;
	}

	@Override
	public Date getEffectiveDate() {
		return _effectiveDate;
	}

	@Override
	public void setEffectiveDate(Date effectiveDate) {
		_effectiveDate = effectiveDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EmpSalaryComponent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmpSalaryComponent toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EmpSalaryComponent)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmpSalaryComponentImpl empSalaryComponentImpl = new EmpSalaryComponentImpl();

		empSalaryComponentImpl.setEmpSalaryEarningId(getEmpSalaryEarningId());
		empSalaryComponentImpl.setEmpSalaryId(getEmpSalaryId());
		empSalaryComponentImpl.setGroupId(getGroupId());
		empSalaryComponentImpl.setCompanyId(getCompanyId());
		empSalaryComponentImpl.setCreateDate(getCreateDate());
		empSalaryComponentImpl.setModifiedDate(getModifiedDate());
		empSalaryComponentImpl.setUserId(getUserId());
		empSalaryComponentImpl.setSalaryComponentId(getSalaryComponentId());
		empSalaryComponentImpl.setAmount(getAmount());
		empSalaryComponentImpl.setEffectiveDate(getEffectiveDate());

		empSalaryComponentImpl.resetOriginalValues();

		return empSalaryComponentImpl;
	}

	@Override
	public int compareTo(EmpSalaryComponent empSalaryComponent) {
		long primaryKey = empSalaryComponent.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EmpSalaryComponent)) {
			return false;
		}

		EmpSalaryComponent empSalaryComponent = (EmpSalaryComponent)obj;

		long primaryKey = empSalaryComponent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		EmpSalaryComponentModelImpl empSalaryComponentModelImpl = this;

		empSalaryComponentModelImpl._originalEmpSalaryEarningId = empSalaryComponentModelImpl._empSalaryEarningId;

		empSalaryComponentModelImpl._setOriginalEmpSalaryEarningId = false;

		empSalaryComponentModelImpl._originalEmpSalaryId = empSalaryComponentModelImpl._empSalaryId;

		empSalaryComponentModelImpl._setOriginalEmpSalaryId = false;

		empSalaryComponentModelImpl._originalGroupId = empSalaryComponentModelImpl._groupId;

		empSalaryComponentModelImpl._setOriginalGroupId = false;

		empSalaryComponentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EmpSalaryComponent> toCacheModel() {
		EmpSalaryComponentCacheModel empSalaryComponentCacheModel = new EmpSalaryComponentCacheModel();

		empSalaryComponentCacheModel.empSalaryEarningId = getEmpSalaryEarningId();

		empSalaryComponentCacheModel.empSalaryId = getEmpSalaryId();

		empSalaryComponentCacheModel.groupId = getGroupId();

		empSalaryComponentCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			empSalaryComponentCacheModel.createDate = createDate.getTime();
		}
		else {
			empSalaryComponentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			empSalaryComponentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			empSalaryComponentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		empSalaryComponentCacheModel.userId = getUserId();

		empSalaryComponentCacheModel.salaryComponentId = getSalaryComponentId();

		empSalaryComponentCacheModel.amount = getAmount();

		Date effectiveDate = getEffectiveDate();

		if (effectiveDate != null) {
			empSalaryComponentCacheModel.effectiveDate = effectiveDate.getTime();
		}
		else {
			empSalaryComponentCacheModel.effectiveDate = Long.MIN_VALUE;
		}

		return empSalaryComponentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{empSalaryEarningId=");
		sb.append(getEmpSalaryEarningId());
		sb.append(", empSalaryId=");
		sb.append(getEmpSalaryId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", salaryComponentId=");
		sb.append(getSalaryComponentId());
		sb.append(", amount=");
		sb.append(getAmount());
		sb.append(", effectiveDate=");
		sb.append(getEffectiveDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.rknowsys.eapp.hrm.model.EmpSalaryComponent");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>empSalaryEarningId</column-name><column-value><![CDATA[");
		sb.append(getEmpSalaryEarningId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>empSalaryId</column-name><column-value><![CDATA[");
		sb.append(getEmpSalaryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>salaryComponentId</column-name><column-value><![CDATA[");
		sb.append(getSalaryComponentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>amount</column-name><column-value><![CDATA[");
		sb.append(getAmount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>effectiveDate</column-name><column-value><![CDATA[");
		sb.append(getEffectiveDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EmpSalaryComponent.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			EmpSalaryComponent.class
		};
	private long _empSalaryEarningId;
	private long _originalEmpSalaryEarningId;
	private boolean _setOriginalEmpSalaryEarningId;
	private long _empSalaryId;
	private long _originalEmpSalaryId;
	private boolean _setOriginalEmpSalaryId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private long _userId;
	private String _userUuid;
	private long _salaryComponentId;
	private long _amount;
	private Date _effectiveDate;
	private long _columnBitmask;
	private EmpSalaryComponent _escapedModel;
}