/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rknowsys.eapp.hrm.model.LeaveCarryForwardPolicy;
import com.rknowsys.eapp.hrm.model.LeaveCarryForwardPolicyModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LeaveCarryForwardPolicy service. Represents a row in the &quot;leave_carry_forward_policy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rknowsys.eapp.hrm.model.LeaveCarryForwardPolicyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveCarryForwardPolicyImpl}.
 * </p>
 *
 * @author rknowsys
 * @see LeaveCarryForwardPolicyImpl
 * @see com.rknowsys.eapp.hrm.model.LeaveCarryForwardPolicy
 * @see com.rknowsys.eapp.hrm.model.LeaveCarryForwardPolicyModel
 * @generated
 */
public class LeaveCarryForwardPolicyModelImpl extends BaseModelImpl<LeaveCarryForwardPolicy>
	implements LeaveCarryForwardPolicyModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave carry forward policy model instance should use the {@link com.rknowsys.eapp.hrm.model.LeaveCarryForwardPolicy} interface instead.
	 */
	public static final String TABLE_NAME = "leave_carry_forward_policy";
	public static final Object[][] TABLE_COLUMNS = {
			{ "leaveCarryForwardPolicyId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "userId", Types.BIGINT },
			{ "leaveTypeId", Types.BIGINT },
			{ "expiryDuration", Types.INTEGER },
			{ "expiryDurationUOM", Types.VARCHAR },
			{ "isMaxCarryForwardLimitApplicable", Types.BOOLEAN },
			{ "maxCarryForwardLimit", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table leave_carry_forward_policy (leaveCarryForwardPolicyId LONG not null primary key,companyId LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,userId LONG,leaveTypeId LONG,expiryDuration INTEGER,expiryDurationUOM VARCHAR(75) null,isMaxCarryForwardLimitApplicable BOOLEAN,maxCarryForwardLimit VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table leave_carry_forward_policy";
	public static final String ORDER_BY_JPQL = " ORDER BY leaveCarryForwardPolicy.leaveCarryForwardPolicyId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY leave_carry_forward_policy.leaveCarryForwardPolicyId ASC";
	public static final String DATA_SOURCE = "hrmDataSource";
	public static final String SESSION_FACTORY = "hrmSessionFactory";
	public static final String TX_MANAGER = "hrmTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rknowsys.eapp.hrm.model.LeaveCarryForwardPolicy"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rknowsys.eapp.hrm.model.LeaveCarryForwardPolicy"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rknowsys.eapp.hrm.model.LeaveCarryForwardPolicy"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long LEAVETYPEID_COLUMN_BITMASK = 2L;
	public static long LEAVECARRYFORWARDPOLICYID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rknowsys.eapp.hrm.model.LeaveCarryForwardPolicy"));

	public LeaveCarryForwardPolicyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveCarryForwardPolicyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveCarryForwardPolicyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveCarryForwardPolicyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveCarryForwardPolicy.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveCarryForwardPolicy.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("leaveCarryForwardPolicyId",
			getLeaveCarryForwardPolicyId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("userId", getUserId());
		attributes.put("leaveTypeId", getLeaveTypeId());
		attributes.put("expiryDuration", getExpiryDuration());
		attributes.put("expiryDurationUOM", getExpiryDurationUOM());
		attributes.put("isMaxCarryForwardLimitApplicable",
			getIsMaxCarryForwardLimitApplicable());
		attributes.put("maxCarryForwardLimit", getMaxCarryForwardLimit());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long leaveCarryForwardPolicyId = (Long)attributes.get(
				"leaveCarryForwardPolicyId");

		if (leaveCarryForwardPolicyId != null) {
			setLeaveCarryForwardPolicyId(leaveCarryForwardPolicyId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long leaveTypeId = (Long)attributes.get("leaveTypeId");

		if (leaveTypeId != null) {
			setLeaveTypeId(leaveTypeId);
		}

		Integer expiryDuration = (Integer)attributes.get("expiryDuration");

		if (expiryDuration != null) {
			setExpiryDuration(expiryDuration);
		}

		String expiryDurationUOM = (String)attributes.get("expiryDurationUOM");

		if (expiryDurationUOM != null) {
			setExpiryDurationUOM(expiryDurationUOM);
		}

		Boolean isMaxCarryForwardLimitApplicable = (Boolean)attributes.get(
				"isMaxCarryForwardLimitApplicable");

		if (isMaxCarryForwardLimitApplicable != null) {
			setIsMaxCarryForwardLimitApplicable(isMaxCarryForwardLimitApplicable);
		}

		String maxCarryForwardLimit = (String)attributes.get(
				"maxCarryForwardLimit");

		if (maxCarryForwardLimit != null) {
			setMaxCarryForwardLimit(maxCarryForwardLimit);
		}
	}

	@Override
	public long getLeaveCarryForwardPolicyId() {
		return _leaveCarryForwardPolicyId;
	}

	@Override
	public void setLeaveCarryForwardPolicyId(long leaveCarryForwardPolicyId) {
		_leaveCarryForwardPolicyId = leaveCarryForwardPolicyId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public long getLeaveTypeId() {
		return _leaveTypeId;
	}

	@Override
	public void setLeaveTypeId(long leaveTypeId) {
		_columnBitmask |= LEAVETYPEID_COLUMN_BITMASK;

		if (!_setOriginalLeaveTypeId) {
			_setOriginalLeaveTypeId = true;

			_originalLeaveTypeId = _leaveTypeId;
		}

		_leaveTypeId = leaveTypeId;
	}

	public long getOriginalLeaveTypeId() {
		return _originalLeaveTypeId;
	}

	@Override
	public int getExpiryDuration() {
		return _expiryDuration;
	}

	@Override
	public void setExpiryDuration(int expiryDuration) {
		_expiryDuration = expiryDuration;
	}

	@Override
	public String getExpiryDurationUOM() {
		if (_expiryDurationUOM == null) {
			return StringPool.BLANK;
		}
		else {
			return _expiryDurationUOM;
		}
	}

	@Override
	public void setExpiryDurationUOM(String expiryDurationUOM) {
		_expiryDurationUOM = expiryDurationUOM;
	}

	@Override
	public boolean getIsMaxCarryForwardLimitApplicable() {
		return _isMaxCarryForwardLimitApplicable;
	}

	@Override
	public boolean isIsMaxCarryForwardLimitApplicable() {
		return _isMaxCarryForwardLimitApplicable;
	}

	@Override
	public void setIsMaxCarryForwardLimitApplicable(
		boolean isMaxCarryForwardLimitApplicable) {
		_isMaxCarryForwardLimitApplicable = isMaxCarryForwardLimitApplicable;
	}

	@Override
	public String getMaxCarryForwardLimit() {
		if (_maxCarryForwardLimit == null) {
			return StringPool.BLANK;
		}
		else {
			return _maxCarryForwardLimit;
		}
	}

	@Override
	public void setMaxCarryForwardLimit(String maxCarryForwardLimit) {
		_maxCarryForwardLimit = maxCarryForwardLimit;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			LeaveCarryForwardPolicy.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LeaveCarryForwardPolicy toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LeaveCarryForwardPolicy)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveCarryForwardPolicyImpl leaveCarryForwardPolicyImpl = new LeaveCarryForwardPolicyImpl();

		leaveCarryForwardPolicyImpl.setLeaveCarryForwardPolicyId(getLeaveCarryForwardPolicyId());
		leaveCarryForwardPolicyImpl.setCompanyId(getCompanyId());
		leaveCarryForwardPolicyImpl.setGroupId(getGroupId());
		leaveCarryForwardPolicyImpl.setCreateDate(getCreateDate());
		leaveCarryForwardPolicyImpl.setModifiedDate(getModifiedDate());
		leaveCarryForwardPolicyImpl.setUserId(getUserId());
		leaveCarryForwardPolicyImpl.setLeaveTypeId(getLeaveTypeId());
		leaveCarryForwardPolicyImpl.setExpiryDuration(getExpiryDuration());
		leaveCarryForwardPolicyImpl.setExpiryDurationUOM(getExpiryDurationUOM());
		leaveCarryForwardPolicyImpl.setIsMaxCarryForwardLimitApplicable(getIsMaxCarryForwardLimitApplicable());
		leaveCarryForwardPolicyImpl.setMaxCarryForwardLimit(getMaxCarryForwardLimit());

		leaveCarryForwardPolicyImpl.resetOriginalValues();

		return leaveCarryForwardPolicyImpl;
	}

	@Override
	public int compareTo(LeaveCarryForwardPolicy leaveCarryForwardPolicy) {
		long primaryKey = leaveCarryForwardPolicy.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LeaveCarryForwardPolicy)) {
			return false;
		}

		LeaveCarryForwardPolicy leaveCarryForwardPolicy = (LeaveCarryForwardPolicy)obj;

		long primaryKey = leaveCarryForwardPolicy.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		LeaveCarryForwardPolicyModelImpl leaveCarryForwardPolicyModelImpl = this;

		leaveCarryForwardPolicyModelImpl._originalGroupId = leaveCarryForwardPolicyModelImpl._groupId;

		leaveCarryForwardPolicyModelImpl._setOriginalGroupId = false;

		leaveCarryForwardPolicyModelImpl._originalLeaveTypeId = leaveCarryForwardPolicyModelImpl._leaveTypeId;

		leaveCarryForwardPolicyModelImpl._setOriginalLeaveTypeId = false;

		leaveCarryForwardPolicyModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveCarryForwardPolicy> toCacheModel() {
		LeaveCarryForwardPolicyCacheModel leaveCarryForwardPolicyCacheModel = new LeaveCarryForwardPolicyCacheModel();

		leaveCarryForwardPolicyCacheModel.leaveCarryForwardPolicyId = getLeaveCarryForwardPolicyId();

		leaveCarryForwardPolicyCacheModel.companyId = getCompanyId();

		leaveCarryForwardPolicyCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveCarryForwardPolicyCacheModel.createDate = createDate.getTime();
		}
		else {
			leaveCarryForwardPolicyCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveCarryForwardPolicyCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leaveCarryForwardPolicyCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leaveCarryForwardPolicyCacheModel.userId = getUserId();

		leaveCarryForwardPolicyCacheModel.leaveTypeId = getLeaveTypeId();

		leaveCarryForwardPolicyCacheModel.expiryDuration = getExpiryDuration();

		leaveCarryForwardPolicyCacheModel.expiryDurationUOM = getExpiryDurationUOM();

		String expiryDurationUOM = leaveCarryForwardPolicyCacheModel.expiryDurationUOM;

		if ((expiryDurationUOM != null) && (expiryDurationUOM.length() == 0)) {
			leaveCarryForwardPolicyCacheModel.expiryDurationUOM = null;
		}

		leaveCarryForwardPolicyCacheModel.isMaxCarryForwardLimitApplicable = getIsMaxCarryForwardLimitApplicable();

		leaveCarryForwardPolicyCacheModel.maxCarryForwardLimit = getMaxCarryForwardLimit();

		String maxCarryForwardLimit = leaveCarryForwardPolicyCacheModel.maxCarryForwardLimit;

		if ((maxCarryForwardLimit != null) &&
				(maxCarryForwardLimit.length() == 0)) {
			leaveCarryForwardPolicyCacheModel.maxCarryForwardLimit = null;
		}

		return leaveCarryForwardPolicyCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{leaveCarryForwardPolicyId=");
		sb.append(getLeaveCarryForwardPolicyId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", leaveTypeId=");
		sb.append(getLeaveTypeId());
		sb.append(", expiryDuration=");
		sb.append(getExpiryDuration());
		sb.append(", expiryDurationUOM=");
		sb.append(getExpiryDurationUOM());
		sb.append(", isMaxCarryForwardLimitApplicable=");
		sb.append(getIsMaxCarryForwardLimitApplicable());
		sb.append(", maxCarryForwardLimit=");
		sb.append(getMaxCarryForwardLimit());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.rknowsys.eapp.hrm.model.LeaveCarryForwardPolicy");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>leaveCarryForwardPolicyId</column-name><column-value><![CDATA[");
		sb.append(getLeaveCarryForwardPolicyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>leaveTypeId</column-name><column-value><![CDATA[");
		sb.append(getLeaveTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>expiryDuration</column-name><column-value><![CDATA[");
		sb.append(getExpiryDuration());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>expiryDurationUOM</column-name><column-value><![CDATA[");
		sb.append(getExpiryDurationUOM());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isMaxCarryForwardLimitApplicable</column-name><column-value><![CDATA[");
		sb.append(getIsMaxCarryForwardLimitApplicable());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maxCarryForwardLimit</column-name><column-value><![CDATA[");
		sb.append(getMaxCarryForwardLimit());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LeaveCarryForwardPolicy.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			LeaveCarryForwardPolicy.class
		};
	private long _leaveCarryForwardPolicyId;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private Date _createDate;
	private Date _modifiedDate;
	private long _userId;
	private String _userUuid;
	private long _leaveTypeId;
	private long _originalLeaveTypeId;
	private boolean _setOriginalLeaveTypeId;
	private int _expiryDuration;
	private String _expiryDurationUOM;
	private boolean _isMaxCarryForwardLimitApplicable;
	private String _maxCarryForwardLimit;
	private long _columnBitmask;
	private LeaveCarryForwardPolicy _escapedModel;
}