/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rknowsys.eapp.hrm.model.LeaveRestriction;
import com.rknowsys.eapp.hrm.model.LeaveRestrictionModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LeaveRestriction service. Represents a row in the &quot;leave_restriction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rknowsys.eapp.hrm.model.LeaveRestrictionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveRestrictionImpl}.
 * </p>
 *
 * @author rknowsys
 * @see LeaveRestrictionImpl
 * @see com.rknowsys.eapp.hrm.model.LeaveRestriction
 * @see com.rknowsys.eapp.hrm.model.LeaveRestrictionModel
 * @generated
 */
public class LeaveRestrictionModelImpl extends BaseModelImpl<LeaveRestriction>
	implements LeaveRestrictionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave restriction model instance should use the {@link com.rknowsys.eapp.hrm.model.LeaveRestriction} interface instead.
	 */
	public static final String TABLE_NAME = "leave_restriction";
	public static final Object[][] TABLE_COLUMNS = {
			{ "leaveRestrictionId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "userId", Types.BIGINT },
			{ "leaveTypeId", Types.BIGINT },
			{ "cannotExceedBalance", Types.BOOLEAN },
			{ "cannotApplyForPartialDay", Types.BOOLEAN },
			{ "ifATermsQuestion", Types.BOOLEAN },
			{ "termsQuestion", Types.VARCHAR },
			{ "errorTextIfTermsDeclined", Types.VARCHAR },
			{ "isMinimumServicePeriodApplicable", Types.BOOLEAN },
			{ "minimumServicePeriod", Types.VARCHAR },
			{ "isMaxConsecutiveLeavesApplicable", Types.BOOLEAN },
			{ "maxConsecutiveLeaves", Types.VARCHAR },
			{ "isSmallChildCriterionApplicable", Types.BOOLEAN },
			{ "maxSmallChildAgeApplicable", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table leave_restriction (leaveRestrictionId LONG not null primary key,companyId LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,userId LONG,leaveTypeId LONG,cannotExceedBalance BOOLEAN,cannotApplyForPartialDay BOOLEAN,ifATermsQuestion BOOLEAN,termsQuestion VARCHAR(75) null,errorTextIfTermsDeclined VARCHAR(75) null,isMinimumServicePeriodApplicable BOOLEAN,minimumServicePeriod VARCHAR(75) null,isMaxConsecutiveLeavesApplicable BOOLEAN,maxConsecutiveLeaves VARCHAR(75) null,isSmallChildCriterionApplicable BOOLEAN,maxSmallChildAgeApplicable VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table leave_restriction";
	public static final String ORDER_BY_JPQL = " ORDER BY leaveRestriction.leaveRestrictionId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY leave_restriction.leaveRestrictionId ASC";
	public static final String DATA_SOURCE = "hrmDataSource";
	public static final String SESSION_FACTORY = "hrmSessionFactory";
	public static final String TX_MANAGER = "hrmTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rknowsys.eapp.hrm.model.LeaveRestriction"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rknowsys.eapp.hrm.model.LeaveRestriction"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rknowsys.eapp.hrm.model.LeaveRestriction"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long LEAVETYPEID_COLUMN_BITMASK = 2L;
	public static long LEAVERESTRICTIONID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rknowsys.eapp.hrm.model.LeaveRestriction"));

	public LeaveRestrictionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveRestrictionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveRestrictionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveRestrictionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveRestriction.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveRestriction.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("leaveRestrictionId", getLeaveRestrictionId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("userId", getUserId());
		attributes.put("leaveTypeId", getLeaveTypeId());
		attributes.put("cannotExceedBalance", getCannotExceedBalance());
		attributes.put("cannotApplyForPartialDay", getCannotApplyForPartialDay());
		attributes.put("ifATermsQuestion", getIfATermsQuestion());
		attributes.put("termsQuestion", getTermsQuestion());
		attributes.put("errorTextIfTermsDeclined", getErrorTextIfTermsDeclined());
		attributes.put("isMinimumServicePeriodApplicable",
			getIsMinimumServicePeriodApplicable());
		attributes.put("minimumServicePeriod", getMinimumServicePeriod());
		attributes.put("isMaxConsecutiveLeavesApplicable",
			getIsMaxConsecutiveLeavesApplicable());
		attributes.put("maxConsecutiveLeaves", getMaxConsecutiveLeaves());
		attributes.put("isSmallChildCriterionApplicable",
			getIsSmallChildCriterionApplicable());
		attributes.put("maxSmallChildAgeApplicable",
			getMaxSmallChildAgeApplicable());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long leaveRestrictionId = (Long)attributes.get("leaveRestrictionId");

		if (leaveRestrictionId != null) {
			setLeaveRestrictionId(leaveRestrictionId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long leaveTypeId = (Long)attributes.get("leaveTypeId");

		if (leaveTypeId != null) {
			setLeaveTypeId(leaveTypeId);
		}

		Boolean cannotExceedBalance = (Boolean)attributes.get(
				"cannotExceedBalance");

		if (cannotExceedBalance != null) {
			setCannotExceedBalance(cannotExceedBalance);
		}

		Boolean cannotApplyForPartialDay = (Boolean)attributes.get(
				"cannotApplyForPartialDay");

		if (cannotApplyForPartialDay != null) {
			setCannotApplyForPartialDay(cannotApplyForPartialDay);
		}

		Boolean ifATermsQuestion = (Boolean)attributes.get("ifATermsQuestion");

		if (ifATermsQuestion != null) {
			setIfATermsQuestion(ifATermsQuestion);
		}

		String termsQuestion = (String)attributes.get("termsQuestion");

		if (termsQuestion != null) {
			setTermsQuestion(termsQuestion);
		}

		String errorTextIfTermsDeclined = (String)attributes.get(
				"errorTextIfTermsDeclined");

		if (errorTextIfTermsDeclined != null) {
			setErrorTextIfTermsDeclined(errorTextIfTermsDeclined);
		}

		Boolean isMinimumServicePeriodApplicable = (Boolean)attributes.get(
				"isMinimumServicePeriodApplicable");

		if (isMinimumServicePeriodApplicable != null) {
			setIsMinimumServicePeriodApplicable(isMinimumServicePeriodApplicable);
		}

		String minimumServicePeriod = (String)attributes.get(
				"minimumServicePeriod");

		if (minimumServicePeriod != null) {
			setMinimumServicePeriod(minimumServicePeriod);
		}

		Boolean isMaxConsecutiveLeavesApplicable = (Boolean)attributes.get(
				"isMaxConsecutiveLeavesApplicable");

		if (isMaxConsecutiveLeavesApplicable != null) {
			setIsMaxConsecutiveLeavesApplicable(isMaxConsecutiveLeavesApplicable);
		}

		String maxConsecutiveLeaves = (String)attributes.get(
				"maxConsecutiveLeaves");

		if (maxConsecutiveLeaves != null) {
			setMaxConsecutiveLeaves(maxConsecutiveLeaves);
		}

		Boolean isSmallChildCriterionApplicable = (Boolean)attributes.get(
				"isSmallChildCriterionApplicable");

		if (isSmallChildCriterionApplicable != null) {
			setIsSmallChildCriterionApplicable(isSmallChildCriterionApplicable);
		}

		String maxSmallChildAgeApplicable = (String)attributes.get(
				"maxSmallChildAgeApplicable");

		if (maxSmallChildAgeApplicable != null) {
			setMaxSmallChildAgeApplicable(maxSmallChildAgeApplicable);
		}
	}

	@Override
	public long getLeaveRestrictionId() {
		return _leaveRestrictionId;
	}

	@Override
	public void setLeaveRestrictionId(long leaveRestrictionId) {
		_leaveRestrictionId = leaveRestrictionId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public long getLeaveTypeId() {
		return _leaveTypeId;
	}

	@Override
	public void setLeaveTypeId(long leaveTypeId) {
		_columnBitmask |= LEAVETYPEID_COLUMN_BITMASK;

		if (!_setOriginalLeaveTypeId) {
			_setOriginalLeaveTypeId = true;

			_originalLeaveTypeId = _leaveTypeId;
		}

		_leaveTypeId = leaveTypeId;
	}

	public long getOriginalLeaveTypeId() {
		return _originalLeaveTypeId;
	}

	@Override
	public boolean getCannotExceedBalance() {
		return _cannotExceedBalance;
	}

	@Override
	public boolean isCannotExceedBalance() {
		return _cannotExceedBalance;
	}

	@Override
	public void setCannotExceedBalance(boolean cannotExceedBalance) {
		_cannotExceedBalance = cannotExceedBalance;
	}

	@Override
	public boolean getCannotApplyForPartialDay() {
		return _cannotApplyForPartialDay;
	}

	@Override
	public boolean isCannotApplyForPartialDay() {
		return _cannotApplyForPartialDay;
	}

	@Override
	public void setCannotApplyForPartialDay(boolean cannotApplyForPartialDay) {
		_cannotApplyForPartialDay = cannotApplyForPartialDay;
	}

	@Override
	public boolean getIfATermsQuestion() {
		return _ifATermsQuestion;
	}

	@Override
	public boolean isIfATermsQuestion() {
		return _ifATermsQuestion;
	}

	@Override
	public void setIfATermsQuestion(boolean ifATermsQuestion) {
		_ifATermsQuestion = ifATermsQuestion;
	}

	@Override
	public String getTermsQuestion() {
		if (_termsQuestion == null) {
			return StringPool.BLANK;
		}
		else {
			return _termsQuestion;
		}
	}

	@Override
	public void setTermsQuestion(String termsQuestion) {
		_termsQuestion = termsQuestion;
	}

	@Override
	public String getErrorTextIfTermsDeclined() {
		if (_errorTextIfTermsDeclined == null) {
			return StringPool.BLANK;
		}
		else {
			return _errorTextIfTermsDeclined;
		}
	}

	@Override
	public void setErrorTextIfTermsDeclined(String errorTextIfTermsDeclined) {
		_errorTextIfTermsDeclined = errorTextIfTermsDeclined;
	}

	@Override
	public boolean getIsMinimumServicePeriodApplicable() {
		return _isMinimumServicePeriodApplicable;
	}

	@Override
	public boolean isIsMinimumServicePeriodApplicable() {
		return _isMinimumServicePeriodApplicable;
	}

	@Override
	public void setIsMinimumServicePeriodApplicable(
		boolean isMinimumServicePeriodApplicable) {
		_isMinimumServicePeriodApplicable = isMinimumServicePeriodApplicable;
	}

	@Override
	public String getMinimumServicePeriod() {
		if (_minimumServicePeriod == null) {
			return StringPool.BLANK;
		}
		else {
			return _minimumServicePeriod;
		}
	}

	@Override
	public void setMinimumServicePeriod(String minimumServicePeriod) {
		_minimumServicePeriod = minimumServicePeriod;
	}

	@Override
	public boolean getIsMaxConsecutiveLeavesApplicable() {
		return _isMaxConsecutiveLeavesApplicable;
	}

	@Override
	public boolean isIsMaxConsecutiveLeavesApplicable() {
		return _isMaxConsecutiveLeavesApplicable;
	}

	@Override
	public void setIsMaxConsecutiveLeavesApplicable(
		boolean isMaxConsecutiveLeavesApplicable) {
		_isMaxConsecutiveLeavesApplicable = isMaxConsecutiveLeavesApplicable;
	}

	@Override
	public String getMaxConsecutiveLeaves() {
		if (_maxConsecutiveLeaves == null) {
			return StringPool.BLANK;
		}
		else {
			return _maxConsecutiveLeaves;
		}
	}

	@Override
	public void setMaxConsecutiveLeaves(String maxConsecutiveLeaves) {
		_maxConsecutiveLeaves = maxConsecutiveLeaves;
	}

	@Override
	public boolean getIsSmallChildCriterionApplicable() {
		return _isSmallChildCriterionApplicable;
	}

	@Override
	public boolean isIsSmallChildCriterionApplicable() {
		return _isSmallChildCriterionApplicable;
	}

	@Override
	public void setIsSmallChildCriterionApplicable(
		boolean isSmallChildCriterionApplicable) {
		_isSmallChildCriterionApplicable = isSmallChildCriterionApplicable;
	}

	@Override
	public String getMaxSmallChildAgeApplicable() {
		if (_maxSmallChildAgeApplicable == null) {
			return StringPool.BLANK;
		}
		else {
			return _maxSmallChildAgeApplicable;
		}
	}

	@Override
	public void setMaxSmallChildAgeApplicable(String maxSmallChildAgeApplicable) {
		_maxSmallChildAgeApplicable = maxSmallChildAgeApplicable;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			LeaveRestriction.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LeaveRestriction toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LeaveRestriction)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveRestrictionImpl leaveRestrictionImpl = new LeaveRestrictionImpl();

		leaveRestrictionImpl.setLeaveRestrictionId(getLeaveRestrictionId());
		leaveRestrictionImpl.setCompanyId(getCompanyId());
		leaveRestrictionImpl.setGroupId(getGroupId());
		leaveRestrictionImpl.setCreateDate(getCreateDate());
		leaveRestrictionImpl.setModifiedDate(getModifiedDate());
		leaveRestrictionImpl.setUserId(getUserId());
		leaveRestrictionImpl.setLeaveTypeId(getLeaveTypeId());
		leaveRestrictionImpl.setCannotExceedBalance(getCannotExceedBalance());
		leaveRestrictionImpl.setCannotApplyForPartialDay(getCannotApplyForPartialDay());
		leaveRestrictionImpl.setIfATermsQuestion(getIfATermsQuestion());
		leaveRestrictionImpl.setTermsQuestion(getTermsQuestion());
		leaveRestrictionImpl.setErrorTextIfTermsDeclined(getErrorTextIfTermsDeclined());
		leaveRestrictionImpl.setIsMinimumServicePeriodApplicable(getIsMinimumServicePeriodApplicable());
		leaveRestrictionImpl.setMinimumServicePeriod(getMinimumServicePeriod());
		leaveRestrictionImpl.setIsMaxConsecutiveLeavesApplicable(getIsMaxConsecutiveLeavesApplicable());
		leaveRestrictionImpl.setMaxConsecutiveLeaves(getMaxConsecutiveLeaves());
		leaveRestrictionImpl.setIsSmallChildCriterionApplicable(getIsSmallChildCriterionApplicable());
		leaveRestrictionImpl.setMaxSmallChildAgeApplicable(getMaxSmallChildAgeApplicable());

		leaveRestrictionImpl.resetOriginalValues();

		return leaveRestrictionImpl;
	}

	@Override
	public int compareTo(LeaveRestriction leaveRestriction) {
		long primaryKey = leaveRestriction.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LeaveRestriction)) {
			return false;
		}

		LeaveRestriction leaveRestriction = (LeaveRestriction)obj;

		long primaryKey = leaveRestriction.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		LeaveRestrictionModelImpl leaveRestrictionModelImpl = this;

		leaveRestrictionModelImpl._originalGroupId = leaveRestrictionModelImpl._groupId;

		leaveRestrictionModelImpl._setOriginalGroupId = false;

		leaveRestrictionModelImpl._originalLeaveTypeId = leaveRestrictionModelImpl._leaveTypeId;

		leaveRestrictionModelImpl._setOriginalLeaveTypeId = false;

		leaveRestrictionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveRestriction> toCacheModel() {
		LeaveRestrictionCacheModel leaveRestrictionCacheModel = new LeaveRestrictionCacheModel();

		leaveRestrictionCacheModel.leaveRestrictionId = getLeaveRestrictionId();

		leaveRestrictionCacheModel.companyId = getCompanyId();

		leaveRestrictionCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveRestrictionCacheModel.createDate = createDate.getTime();
		}
		else {
			leaveRestrictionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveRestrictionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leaveRestrictionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leaveRestrictionCacheModel.userId = getUserId();

		leaveRestrictionCacheModel.leaveTypeId = getLeaveTypeId();

		leaveRestrictionCacheModel.cannotExceedBalance = getCannotExceedBalance();

		leaveRestrictionCacheModel.cannotApplyForPartialDay = getCannotApplyForPartialDay();

		leaveRestrictionCacheModel.ifATermsQuestion = getIfATermsQuestion();

		leaveRestrictionCacheModel.termsQuestion = getTermsQuestion();

		String termsQuestion = leaveRestrictionCacheModel.termsQuestion;

		if ((termsQuestion != null) && (termsQuestion.length() == 0)) {
			leaveRestrictionCacheModel.termsQuestion = null;
		}

		leaveRestrictionCacheModel.errorTextIfTermsDeclined = getErrorTextIfTermsDeclined();

		String errorTextIfTermsDeclined = leaveRestrictionCacheModel.errorTextIfTermsDeclined;

		if ((errorTextIfTermsDeclined != null) &&
				(errorTextIfTermsDeclined.length() == 0)) {
			leaveRestrictionCacheModel.errorTextIfTermsDeclined = null;
		}

		leaveRestrictionCacheModel.isMinimumServicePeriodApplicable = getIsMinimumServicePeriodApplicable();

		leaveRestrictionCacheModel.minimumServicePeriod = getMinimumServicePeriod();

		String minimumServicePeriod = leaveRestrictionCacheModel.minimumServicePeriod;

		if ((minimumServicePeriod != null) &&
				(minimumServicePeriod.length() == 0)) {
			leaveRestrictionCacheModel.minimumServicePeriod = null;
		}

		leaveRestrictionCacheModel.isMaxConsecutiveLeavesApplicable = getIsMaxConsecutiveLeavesApplicable();

		leaveRestrictionCacheModel.maxConsecutiveLeaves = getMaxConsecutiveLeaves();

		String maxConsecutiveLeaves = leaveRestrictionCacheModel.maxConsecutiveLeaves;

		if ((maxConsecutiveLeaves != null) &&
				(maxConsecutiveLeaves.length() == 0)) {
			leaveRestrictionCacheModel.maxConsecutiveLeaves = null;
		}

		leaveRestrictionCacheModel.isSmallChildCriterionApplicable = getIsSmallChildCriterionApplicable();

		leaveRestrictionCacheModel.maxSmallChildAgeApplicable = getMaxSmallChildAgeApplicable();

		String maxSmallChildAgeApplicable = leaveRestrictionCacheModel.maxSmallChildAgeApplicable;

		if ((maxSmallChildAgeApplicable != null) &&
				(maxSmallChildAgeApplicable.length() == 0)) {
			leaveRestrictionCacheModel.maxSmallChildAgeApplicable = null;
		}

		return leaveRestrictionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(37);

		sb.append("{leaveRestrictionId=");
		sb.append(getLeaveRestrictionId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", leaveTypeId=");
		sb.append(getLeaveTypeId());
		sb.append(", cannotExceedBalance=");
		sb.append(getCannotExceedBalance());
		sb.append(", cannotApplyForPartialDay=");
		sb.append(getCannotApplyForPartialDay());
		sb.append(", ifATermsQuestion=");
		sb.append(getIfATermsQuestion());
		sb.append(", termsQuestion=");
		sb.append(getTermsQuestion());
		sb.append(", errorTextIfTermsDeclined=");
		sb.append(getErrorTextIfTermsDeclined());
		sb.append(", isMinimumServicePeriodApplicable=");
		sb.append(getIsMinimumServicePeriodApplicable());
		sb.append(", minimumServicePeriod=");
		sb.append(getMinimumServicePeriod());
		sb.append(", isMaxConsecutiveLeavesApplicable=");
		sb.append(getIsMaxConsecutiveLeavesApplicable());
		sb.append(", maxConsecutiveLeaves=");
		sb.append(getMaxConsecutiveLeaves());
		sb.append(", isSmallChildCriterionApplicable=");
		sb.append(getIsSmallChildCriterionApplicable());
		sb.append(", maxSmallChildAgeApplicable=");
		sb.append(getMaxSmallChildAgeApplicable());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(58);

		sb.append("<model><model-name>");
		sb.append("com.rknowsys.eapp.hrm.model.LeaveRestriction");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>leaveRestrictionId</column-name><column-value><![CDATA[");
		sb.append(getLeaveRestrictionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>leaveTypeId</column-name><column-value><![CDATA[");
		sb.append(getLeaveTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cannotExceedBalance</column-name><column-value><![CDATA[");
		sb.append(getCannotExceedBalance());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cannotApplyForPartialDay</column-name><column-value><![CDATA[");
		sb.append(getCannotApplyForPartialDay());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ifATermsQuestion</column-name><column-value><![CDATA[");
		sb.append(getIfATermsQuestion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>termsQuestion</column-name><column-value><![CDATA[");
		sb.append(getTermsQuestion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>errorTextIfTermsDeclined</column-name><column-value><![CDATA[");
		sb.append(getErrorTextIfTermsDeclined());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isMinimumServicePeriodApplicable</column-name><column-value><![CDATA[");
		sb.append(getIsMinimumServicePeriodApplicable());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>minimumServicePeriod</column-name><column-value><![CDATA[");
		sb.append(getMinimumServicePeriod());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isMaxConsecutiveLeavesApplicable</column-name><column-value><![CDATA[");
		sb.append(getIsMaxConsecutiveLeavesApplicable());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maxConsecutiveLeaves</column-name><column-value><![CDATA[");
		sb.append(getMaxConsecutiveLeaves());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isSmallChildCriterionApplicable</column-name><column-value><![CDATA[");
		sb.append(getIsSmallChildCriterionApplicable());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maxSmallChildAgeApplicable</column-name><column-value><![CDATA[");
		sb.append(getMaxSmallChildAgeApplicable());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LeaveRestriction.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			LeaveRestriction.class
		};
	private long _leaveRestrictionId;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private Date _createDate;
	private Date _modifiedDate;
	private long _userId;
	private String _userUuid;
	private long _leaveTypeId;
	private long _originalLeaveTypeId;
	private boolean _setOriginalLeaveTypeId;
	private boolean _cannotExceedBalance;
	private boolean _cannotApplyForPartialDay;
	private boolean _ifATermsQuestion;
	private String _termsQuestion;
	private String _errorTextIfTermsDeclined;
	private boolean _isMinimumServicePeriodApplicable;
	private String _minimumServicePeriod;
	private boolean _isMaxConsecutiveLeavesApplicable;
	private String _maxConsecutiveLeaves;
	private boolean _isSmallChildCriterionApplicable;
	private String _maxSmallChildAgeApplicable;
	private long _columnBitmask;
	private LeaveRestriction _escapedModel;
}