/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rknowsys.eapp.hrm.model.LeaveType;
import com.rknowsys.eapp.hrm.model.LeaveTypeModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LeaveType service. Represents a row in the &quot;leave_type&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rknowsys.eapp.hrm.model.LeaveTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LeaveTypeImpl}.
 * </p>
 *
 * @author rknowsys
 * @see LeaveTypeImpl
 * @see com.rknowsys.eapp.hrm.model.LeaveType
 * @see com.rknowsys.eapp.hrm.model.LeaveTypeModel
 * @generated
 */
public class LeaveTypeModelImpl extends BaseModelImpl<LeaveType>
	implements LeaveTypeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a leave type model instance should use the {@link com.rknowsys.eapp.hrm.model.LeaveType} interface instead.
	 */
	public static final String TABLE_NAME = "leave_type";
	public static final Object[][] TABLE_COLUMNS = {
			{ "leaveTypeId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "userId", Types.BIGINT },
			{ "nationalityId", Types.BIGINT },
			{ "leaveTypeName", Types.VARCHAR },
			{ "isSituational", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table leave_type (leaveTypeId LONG not null primary key,companyId LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,userId LONG,nationalityId LONG,leaveTypeName VARCHAR(75) null,isSituational BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table leave_type";
	public static final String ORDER_BY_JPQL = " ORDER BY leaveType.leaveTypeId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY leave_type.leaveTypeId ASC";
	public static final String DATA_SOURCE = "hrmDataSource";
	public static final String SESSION_FACTORY = "hrmSessionFactory";
	public static final String TX_MANAGER = "hrmTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rknowsys.eapp.hrm.model.LeaveType"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rknowsys.eapp.hrm.model.LeaveType"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rknowsys.eapp.hrm.model.LeaveType"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long NATIONALITYID_COLUMN_BITMASK = 2L;
	public static long LEAVETYPEID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rknowsys.eapp.hrm.model.LeaveType"));

	public LeaveTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _leaveTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLeaveTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _leaveTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LeaveType.class;
	}

	@Override
	public String getModelClassName() {
		return LeaveType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("leaveTypeId", getLeaveTypeId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("userId", getUserId());
		attributes.put("nationalityId", getNationalityId());
		attributes.put("leaveTypeName", getLeaveTypeName());
		attributes.put("isSituational", getIsSituational());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long leaveTypeId = (Long)attributes.get("leaveTypeId");

		if (leaveTypeId != null) {
			setLeaveTypeId(leaveTypeId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long nationalityId = (Long)attributes.get("nationalityId");

		if (nationalityId != null) {
			setNationalityId(nationalityId);
		}

		String leaveTypeName = (String)attributes.get("leaveTypeName");

		if (leaveTypeName != null) {
			setLeaveTypeName(leaveTypeName);
		}

		Boolean isSituational = (Boolean)attributes.get("isSituational");

		if (isSituational != null) {
			setIsSituational(isSituational);
		}
	}

	@Override
	public long getLeaveTypeId() {
		return _leaveTypeId;
	}

	@Override
	public void setLeaveTypeId(long leaveTypeId) {
		_leaveTypeId = leaveTypeId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public long getNationalityId() {
		return _nationalityId;
	}

	@Override
	public void setNationalityId(long nationalityId) {
		_columnBitmask |= NATIONALITYID_COLUMN_BITMASK;

		if (!_setOriginalNationalityId) {
			_setOriginalNationalityId = true;

			_originalNationalityId = _nationalityId;
		}

		_nationalityId = nationalityId;
	}

	public long getOriginalNationalityId() {
		return _originalNationalityId;
	}

	@Override
	public String getLeaveTypeName() {
		if (_leaveTypeName == null) {
			return StringPool.BLANK;
		}
		else {
			return _leaveTypeName;
		}
	}

	@Override
	public void setLeaveTypeName(String leaveTypeName) {
		_leaveTypeName = leaveTypeName;
	}

	@Override
	public boolean getIsSituational() {
		return _isSituational;
	}

	@Override
	public boolean isIsSituational() {
		return _isSituational;
	}

	@Override
	public void setIsSituational(boolean isSituational) {
		_isSituational = isSituational;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			LeaveType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LeaveType toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LeaveType)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LeaveTypeImpl leaveTypeImpl = new LeaveTypeImpl();

		leaveTypeImpl.setLeaveTypeId(getLeaveTypeId());
		leaveTypeImpl.setCompanyId(getCompanyId());
		leaveTypeImpl.setGroupId(getGroupId());
		leaveTypeImpl.setCreateDate(getCreateDate());
		leaveTypeImpl.setModifiedDate(getModifiedDate());
		leaveTypeImpl.setUserId(getUserId());
		leaveTypeImpl.setNationalityId(getNationalityId());
		leaveTypeImpl.setLeaveTypeName(getLeaveTypeName());
		leaveTypeImpl.setIsSituational(getIsSituational());

		leaveTypeImpl.resetOriginalValues();

		return leaveTypeImpl;
	}

	@Override
	public int compareTo(LeaveType leaveType) {
		long primaryKey = leaveType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LeaveType)) {
			return false;
		}

		LeaveType leaveType = (LeaveType)obj;

		long primaryKey = leaveType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		LeaveTypeModelImpl leaveTypeModelImpl = this;

		leaveTypeModelImpl._originalGroupId = leaveTypeModelImpl._groupId;

		leaveTypeModelImpl._setOriginalGroupId = false;

		leaveTypeModelImpl._originalNationalityId = leaveTypeModelImpl._nationalityId;

		leaveTypeModelImpl._setOriginalNationalityId = false;

		leaveTypeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LeaveType> toCacheModel() {
		LeaveTypeCacheModel leaveTypeCacheModel = new LeaveTypeCacheModel();

		leaveTypeCacheModel.leaveTypeId = getLeaveTypeId();

		leaveTypeCacheModel.companyId = getCompanyId();

		leaveTypeCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			leaveTypeCacheModel.createDate = createDate.getTime();
		}
		else {
			leaveTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			leaveTypeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			leaveTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		leaveTypeCacheModel.userId = getUserId();

		leaveTypeCacheModel.nationalityId = getNationalityId();

		leaveTypeCacheModel.leaveTypeName = getLeaveTypeName();

		String leaveTypeName = leaveTypeCacheModel.leaveTypeName;

		if ((leaveTypeName != null) && (leaveTypeName.length() == 0)) {
			leaveTypeCacheModel.leaveTypeName = null;
		}

		leaveTypeCacheModel.isSituational = getIsSituational();

		return leaveTypeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{leaveTypeId=");
		sb.append(getLeaveTypeId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", nationalityId=");
		sb.append(getNationalityId());
		sb.append(", leaveTypeName=");
		sb.append(getLeaveTypeName());
		sb.append(", isSituational=");
		sb.append(getIsSituational());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.rknowsys.eapp.hrm.model.LeaveType");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>leaveTypeId</column-name><column-value><![CDATA[");
		sb.append(getLeaveTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nationalityId</column-name><column-value><![CDATA[");
		sb.append(getNationalityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>leaveTypeName</column-name><column-value><![CDATA[");
		sb.append(getLeaveTypeName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isSituational</column-name><column-value><![CDATA[");
		sb.append(getIsSituational());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LeaveType.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			LeaveType.class
		};
	private long _leaveTypeId;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private Date _createDate;
	private Date _modifiedDate;
	private long _userId;
	private String _userUuid;
	private long _nationalityId;
	private long _originalNationalityId;
	private boolean _setOriginalNationalityId;
	private String _leaveTypeName;
	private boolean _isSituational;
	private long _columnBitmask;
	private LeaveType _escapedModel;
}