/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rknowsys.eapp.hrm.model.SalaryComponent;
import com.rknowsys.eapp.hrm.model.SalaryComponentModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the SalaryComponent service. Represents a row in the &quot;salary_component&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rknowsys.eapp.hrm.model.SalaryComponentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SalaryComponentImpl}.
 * </p>
 *
 * @author rknowsys
 * @see SalaryComponentImpl
 * @see com.rknowsys.eapp.hrm.model.SalaryComponent
 * @see com.rknowsys.eapp.hrm.model.SalaryComponentModel
 * @generated
 */
public class SalaryComponentModelImpl extends BaseModelImpl<SalaryComponent>
	implements SalaryComponentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a salary component model instance should use the {@link com.rknowsys.eapp.hrm.model.SalaryComponent} interface instead.
	 */
	public static final String TABLE_NAME = "salary_component";
	public static final Object[][] TABLE_COLUMNS = {
			{ "salaryComponentId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "userId", Types.BIGINT },
			{ "componentName", Types.VARCHAR },
			{ "type_", Types.BOOLEAN },
			{ "onlyCTC", Types.BOOLEAN },
			{ "valueType", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table salary_component (salaryComponentId LONG not null primary key,companyId LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,userId LONG,componentName VARCHAR(75) null,type_ BOOLEAN,onlyCTC BOOLEAN,valueType VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table salary_component";
	public static final String ORDER_BY_JPQL = " ORDER BY salaryComponent.salaryComponentId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY salary_component.salaryComponentId ASC";
	public static final String DATA_SOURCE = "hrmDataSource";
	public static final String SESSION_FACTORY = "hrmSessionFactory";
	public static final String TX_MANAGER = "hrmTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rknowsys.eapp.hrm.model.SalaryComponent"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rknowsys.eapp.hrm.model.SalaryComponent"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rknowsys.eapp.hrm.model.SalaryComponent"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long SALARYCOMPONENTID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rknowsys.eapp.hrm.model.SalaryComponent"));

	public SalaryComponentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _salaryComponentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSalaryComponentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _salaryComponentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SalaryComponent.class;
	}

	@Override
	public String getModelClassName() {
		return SalaryComponent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("salaryComponentId", getSalaryComponentId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("userId", getUserId());
		attributes.put("componentName", getComponentName());
		attributes.put("type", getType());
		attributes.put("onlyCTC", getOnlyCTC());
		attributes.put("valueType", getValueType());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long salaryComponentId = (Long)attributes.get("salaryComponentId");

		if (salaryComponentId != null) {
			setSalaryComponentId(salaryComponentId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String componentName = (String)attributes.get("componentName");

		if (componentName != null) {
			setComponentName(componentName);
		}

		Boolean type = (Boolean)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		Boolean onlyCTC = (Boolean)attributes.get("onlyCTC");

		if (onlyCTC != null) {
			setOnlyCTC(onlyCTC);
		}

		String valueType = (String)attributes.get("valueType");

		if (valueType != null) {
			setValueType(valueType);
		}
	}

	@Override
	public long getSalaryComponentId() {
		return _salaryComponentId;
	}

	@Override
	public void setSalaryComponentId(long salaryComponentId) {
		_columnBitmask |= SALARYCOMPONENTID_COLUMN_BITMASK;

		if (!_setOriginalSalaryComponentId) {
			_setOriginalSalaryComponentId = true;

			_originalSalaryComponentId = _salaryComponentId;
		}

		_salaryComponentId = salaryComponentId;
	}

	public long getOriginalSalaryComponentId() {
		return _originalSalaryComponentId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getComponentName() {
		if (_componentName == null) {
			return StringPool.BLANK;
		}
		else {
			return _componentName;
		}
	}

	@Override
	public void setComponentName(String componentName) {
		_componentName = componentName;
	}

	@Override
	public boolean getType() {
		return _type;
	}

	@Override
	public boolean isType() {
		return _type;
	}

	@Override
	public void setType(boolean type) {
		_type = type;
	}

	@Override
	public boolean getOnlyCTC() {
		return _onlyCTC;
	}

	@Override
	public boolean isOnlyCTC() {
		return _onlyCTC;
	}

	@Override
	public void setOnlyCTC(boolean onlyCTC) {
		_onlyCTC = onlyCTC;
	}

	@Override
	public String getValueType() {
		if (_valueType == null) {
			return StringPool.BLANK;
		}
		else {
			return _valueType;
		}
	}

	@Override
	public void setValueType(String valueType) {
		_valueType = valueType;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			SalaryComponent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SalaryComponent toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SalaryComponent)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SalaryComponentImpl salaryComponentImpl = new SalaryComponentImpl();

		salaryComponentImpl.setSalaryComponentId(getSalaryComponentId());
		salaryComponentImpl.setCompanyId(getCompanyId());
		salaryComponentImpl.setGroupId(getGroupId());
		salaryComponentImpl.setCreateDate(getCreateDate());
		salaryComponentImpl.setModifiedDate(getModifiedDate());
		salaryComponentImpl.setUserId(getUserId());
		salaryComponentImpl.setComponentName(getComponentName());
		salaryComponentImpl.setType(getType());
		salaryComponentImpl.setOnlyCTC(getOnlyCTC());
		salaryComponentImpl.setValueType(getValueType());

		salaryComponentImpl.resetOriginalValues();

		return salaryComponentImpl;
	}

	@Override
	public int compareTo(SalaryComponent salaryComponent) {
		long primaryKey = salaryComponent.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SalaryComponent)) {
			return false;
		}

		SalaryComponent salaryComponent = (SalaryComponent)obj;

		long primaryKey = salaryComponent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SalaryComponentModelImpl salaryComponentModelImpl = this;

		salaryComponentModelImpl._originalSalaryComponentId = salaryComponentModelImpl._salaryComponentId;

		salaryComponentModelImpl._setOriginalSalaryComponentId = false;

		salaryComponentModelImpl._originalGroupId = salaryComponentModelImpl._groupId;

		salaryComponentModelImpl._setOriginalGroupId = false;

		salaryComponentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SalaryComponent> toCacheModel() {
		SalaryComponentCacheModel salaryComponentCacheModel = new SalaryComponentCacheModel();

		salaryComponentCacheModel.salaryComponentId = getSalaryComponentId();

		salaryComponentCacheModel.companyId = getCompanyId();

		salaryComponentCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			salaryComponentCacheModel.createDate = createDate.getTime();
		}
		else {
			salaryComponentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			salaryComponentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			salaryComponentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		salaryComponentCacheModel.userId = getUserId();

		salaryComponentCacheModel.componentName = getComponentName();

		String componentName = salaryComponentCacheModel.componentName;

		if ((componentName != null) && (componentName.length() == 0)) {
			salaryComponentCacheModel.componentName = null;
		}

		salaryComponentCacheModel.type = getType();

		salaryComponentCacheModel.onlyCTC = getOnlyCTC();

		salaryComponentCacheModel.valueType = getValueType();

		String valueType = salaryComponentCacheModel.valueType;

		if ((valueType != null) && (valueType.length() == 0)) {
			salaryComponentCacheModel.valueType = null;
		}

		return salaryComponentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{salaryComponentId=");
		sb.append(getSalaryComponentId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", componentName=");
		sb.append(getComponentName());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", onlyCTC=");
		sb.append(getOnlyCTC());
		sb.append(", valueType=");
		sb.append(getValueType());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.rknowsys.eapp.hrm.model.SalaryComponent");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>salaryComponentId</column-name><column-value><![CDATA[");
		sb.append(getSalaryComponentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>componentName</column-name><column-value><![CDATA[");
		sb.append(getComponentName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>onlyCTC</column-name><column-value><![CDATA[");
		sb.append(getOnlyCTC());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>valueType</column-name><column-value><![CDATA[");
		sb.append(getValueType());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SalaryComponent.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			SalaryComponent.class
		};
	private long _salaryComponentId;
	private long _originalSalaryComponentId;
	private boolean _setOriginalSalaryComponentId;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private Date _createDate;
	private Date _modifiedDate;
	private long _userId;
	private String _userUuid;
	private String _componentName;
	private boolean _type;
	private boolean _onlyCTC;
	private String _valueType;
	private long _columnBitmask;
	private SalaryComponent _escapedModel;
}