/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rknowsys.eapp.hrm.model.WorkShiftUser;
import com.rknowsys.eapp.hrm.model.WorkShiftUserModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the WorkShiftUser service. Represents a row in the &quot;work_shift_user&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rknowsys.eapp.hrm.model.WorkShiftUserModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WorkShiftUserImpl}.
 * </p>
 *
 * @author rknowsys
 * @see WorkShiftUserImpl
 * @see com.rknowsys.eapp.hrm.model.WorkShiftUser
 * @see com.rknowsys.eapp.hrm.model.WorkShiftUserModel
 * @generated
 */
public class WorkShiftUserModelImpl extends BaseModelImpl<WorkShiftUser>
	implements WorkShiftUserModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a work shift user model instance should use the {@link com.rknowsys.eapp.hrm.model.WorkShiftUser} interface instead.
	 */
	public static final String TABLE_NAME = "work_shift_user";
	public static final Object[][] TABLE_COLUMNS = {
			{ "workShiftUserId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "userId", Types.BIGINT },
			{ "empId", Types.BIGINT },
			{ "shiftId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table work_shift_user (workShiftUserId LONG not null primary key,companyId LONG,groupId LONG,createDate DATE null,modifiedDate DATE null,userId LONG,empId LONG,shiftId LONG)";
	public static final String TABLE_SQL_DROP = "drop table work_shift_user";
	public static final String ORDER_BY_JPQL = " ORDER BY workShiftUser.workShiftUserId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY work_shift_user.workShiftUserId ASC";
	public static final String DATA_SOURCE = "anotherDataSource";
	public static final String SESSION_FACTORY = "anotherSessionFactory";
	public static final String TX_MANAGER = "anotherTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rknowsys.eapp.hrm.model.WorkShiftUser"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rknowsys.eapp.hrm.model.WorkShiftUser"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rknowsys.eapp.hrm.model.WorkShiftUser"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long WORKSHIFTUSERID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rknowsys.eapp.hrm.model.WorkShiftUser"));

	public WorkShiftUserModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _workShiftUserId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWorkShiftUserId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _workShiftUserId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WorkShiftUser.class;
	}

	@Override
	public String getModelClassName() {
		return WorkShiftUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("workShiftUserId", getWorkShiftUserId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("userId", getUserId());
		attributes.put("empId", getEmpId());
		attributes.put("shiftId", getShiftId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long workShiftUserId = (Long)attributes.get("workShiftUserId");

		if (workShiftUserId != null) {
			setWorkShiftUserId(workShiftUserId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long empId = (Long)attributes.get("empId");

		if (empId != null) {
			setEmpId(empId);
		}

		Long shiftId = (Long)attributes.get("shiftId");

		if (shiftId != null) {
			setShiftId(shiftId);
		}
	}

	@Override
	public long getWorkShiftUserId() {
		return _workShiftUserId;
	}

	@Override
	public void setWorkShiftUserId(long workShiftUserId) {
		_workShiftUserId = workShiftUserId;
	}

	@Override
	public String getWorkShiftUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getWorkShiftUserId(), "uuid",
			_workShiftUserUuid);
	}

	@Override
	public void setWorkShiftUserUuid(String workShiftUserUuid) {
		_workShiftUserUuid = workShiftUserUuid;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public long getEmpId() {
		return _empId;
	}

	@Override
	public void setEmpId(long empId) {
		_empId = empId;
	}

	@Override
	public long getShiftId() {
		return _shiftId;
	}

	@Override
	public void setShiftId(long shiftId) {
		_shiftId = shiftId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			WorkShiftUser.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WorkShiftUser toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (WorkShiftUser)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WorkShiftUserImpl workShiftUserImpl = new WorkShiftUserImpl();

		workShiftUserImpl.setWorkShiftUserId(getWorkShiftUserId());
		workShiftUserImpl.setCompanyId(getCompanyId());
		workShiftUserImpl.setGroupId(getGroupId());
		workShiftUserImpl.setCreateDate(getCreateDate());
		workShiftUserImpl.setModifiedDate(getModifiedDate());
		workShiftUserImpl.setUserId(getUserId());
		workShiftUserImpl.setEmpId(getEmpId());
		workShiftUserImpl.setShiftId(getShiftId());

		workShiftUserImpl.resetOriginalValues();

		return workShiftUserImpl;
	}

	@Override
	public int compareTo(WorkShiftUser workShiftUser) {
		long primaryKey = workShiftUser.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof WorkShiftUser)) {
			return false;
		}

		WorkShiftUser workShiftUser = (WorkShiftUser)obj;

		long primaryKey = workShiftUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		WorkShiftUserModelImpl workShiftUserModelImpl = this;

		workShiftUserModelImpl._originalGroupId = workShiftUserModelImpl._groupId;

		workShiftUserModelImpl._setOriginalGroupId = false;

		workShiftUserModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<WorkShiftUser> toCacheModel() {
		WorkShiftUserCacheModel workShiftUserCacheModel = new WorkShiftUserCacheModel();

		workShiftUserCacheModel.workShiftUserId = getWorkShiftUserId();

		workShiftUserCacheModel.companyId = getCompanyId();

		workShiftUserCacheModel.groupId = getGroupId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			workShiftUserCacheModel.createDate = createDate.getTime();
		}
		else {
			workShiftUserCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			workShiftUserCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			workShiftUserCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		workShiftUserCacheModel.userId = getUserId();

		workShiftUserCacheModel.empId = getEmpId();

		workShiftUserCacheModel.shiftId = getShiftId();

		return workShiftUserCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{workShiftUserId=");
		sb.append(getWorkShiftUserId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", empId=");
		sb.append(getEmpId());
		sb.append(", shiftId=");
		sb.append(getShiftId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.rknowsys.eapp.hrm.model.WorkShiftUser");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>workShiftUserId</column-name><column-value><![CDATA[");
		sb.append(getWorkShiftUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>empId</column-name><column-value><![CDATA[");
		sb.append(getEmpId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shiftId</column-name><column-value><![CDATA[");
		sb.append(getShiftId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = WorkShiftUser.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			WorkShiftUser.class
		};
	private long _workShiftUserId;
	private String _workShiftUserUuid;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private Date _createDate;
	private Date _modifiedDate;
	private long _userId;
	private String _userUuid;
	private long _empId;
	private long _shiftId;
	private long _columnBitmask;
	private WorkShiftUser _escapedModel;
}