/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rknowsys.eapp.hrm.model.WorkWeek;
import com.rknowsys.eapp.hrm.model.WorkWeekModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the WorkWeek service. Represents a row in the &quot;workweek&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rknowsys.eapp.hrm.model.WorkWeekModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WorkWeekImpl}.
 * </p>
 *
 * @author rknowsys
 * @see WorkWeekImpl
 * @see com.rknowsys.eapp.hrm.model.WorkWeek
 * @see com.rknowsys.eapp.hrm.model.WorkWeekModel
 * @generated
 */
public class WorkWeekModelImpl extends BaseModelImpl<WorkWeek>
	implements WorkWeekModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a WorkWeek model instance should use the {@link com.rknowsys.eapp.hrm.model.WorkWeek} interface instead.
	 */
	public static final String TABLE_NAME = "workweek";
	public static final Object[][] TABLE_COLUMNS = {
			{ "workWeekId", Types.BIGINT },
			{ "nationalityId", Types.BIGINT },
			{ "mondayWorkSchedule", Types.INTEGER },
			{ "tuesdayWorkSchedule", Types.INTEGER },
			{ "wednesdayWorkSchedule", Types.INTEGER },
			{ "thursdayWorkSchedule", Types.INTEGER },
			{ "fridayWorkSchedule", Types.INTEGER },
			{ "saturdayWorkSchedule", Types.INTEGER },
			{ "sundayWorkSchedule", Types.INTEGER },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table workweek (workWeekId LONG not null primary key,nationalityId LONG,mondayWorkSchedule INTEGER,tuesdayWorkSchedule INTEGER,wednesdayWorkSchedule INTEGER,thursdayWorkSchedule INTEGER,fridayWorkSchedule INTEGER,saturdayWorkSchedule INTEGER,sundayWorkSchedule INTEGER,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table workweek";
	public static final String ORDER_BY_JPQL = " ORDER BY workWeek.workWeekId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY workweek.workWeekId ASC";
	public static final String DATA_SOURCE = "hrmDataSource";
	public static final String SESSION_FACTORY = "hrmSessionFactory";
	public static final String TX_MANAGER = "hrmTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rknowsys.eapp.hrm.model.WorkWeek"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rknowsys.eapp.hrm.model.WorkWeek"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rknowsys.eapp.hrm.model.WorkWeek"),
			true);
	public static long NATIONALITYID_COLUMN_BITMASK = 1L;
	public static long WORKWEEKID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rknowsys.eapp.hrm.model.WorkWeek"));

	public WorkWeekModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _workWeekId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWorkWeekId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _workWeekId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WorkWeek.class;
	}

	@Override
	public String getModelClassName() {
		return WorkWeek.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("workWeekId", getWorkWeekId());
		attributes.put("nationalityId", getNationalityId());
		attributes.put("mondayWorkSchedule", getMondayWorkSchedule());
		attributes.put("tuesdayWorkSchedule", getTuesdayWorkSchedule());
		attributes.put("wednesdayWorkSchedule", getWednesdayWorkSchedule());
		attributes.put("thursdayWorkSchedule", getThursdayWorkSchedule());
		attributes.put("fridayWorkSchedule", getFridayWorkSchedule());
		attributes.put("saturdayWorkSchedule", getSaturdayWorkSchedule());
		attributes.put("sundayWorkSchedule", getSundayWorkSchedule());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long workWeekId = (Long)attributes.get("workWeekId");

		if (workWeekId != null) {
			setWorkWeekId(workWeekId);
		}

		Long nationalityId = (Long)attributes.get("nationalityId");

		if (nationalityId != null) {
			setNationalityId(nationalityId);
		}

		Integer mondayWorkSchedule = (Integer)attributes.get(
				"mondayWorkSchedule");

		if (mondayWorkSchedule != null) {
			setMondayWorkSchedule(mondayWorkSchedule);
		}

		Integer tuesdayWorkSchedule = (Integer)attributes.get(
				"tuesdayWorkSchedule");

		if (tuesdayWorkSchedule != null) {
			setTuesdayWorkSchedule(tuesdayWorkSchedule);
		}

		Integer wednesdayWorkSchedule = (Integer)attributes.get(
				"wednesdayWorkSchedule");

		if (wednesdayWorkSchedule != null) {
			setWednesdayWorkSchedule(wednesdayWorkSchedule);
		}

		Integer thursdayWorkSchedule = (Integer)attributes.get(
				"thursdayWorkSchedule");

		if (thursdayWorkSchedule != null) {
			setThursdayWorkSchedule(thursdayWorkSchedule);
		}

		Integer fridayWorkSchedule = (Integer)attributes.get(
				"fridayWorkSchedule");

		if (fridayWorkSchedule != null) {
			setFridayWorkSchedule(fridayWorkSchedule);
		}

		Integer saturdayWorkSchedule = (Integer)attributes.get(
				"saturdayWorkSchedule");

		if (saturdayWorkSchedule != null) {
			setSaturdayWorkSchedule(saturdayWorkSchedule);
		}

		Integer sundayWorkSchedule = (Integer)attributes.get(
				"sundayWorkSchedule");

		if (sundayWorkSchedule != null) {
			setSundayWorkSchedule(sundayWorkSchedule);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@Override
	public long getWorkWeekId() {
		return _workWeekId;
	}

	@Override
	public void setWorkWeekId(long workWeekId) {
		_workWeekId = workWeekId;
	}

	@Override
	public long getNationalityId() {
		return _nationalityId;
	}

	@Override
	public void setNationalityId(long nationalityId) {
		_columnBitmask |= NATIONALITYID_COLUMN_BITMASK;

		if (!_setOriginalNationalityId) {
			_setOriginalNationalityId = true;

			_originalNationalityId = _nationalityId;
		}

		_nationalityId = nationalityId;
	}

	public long getOriginalNationalityId() {
		return _originalNationalityId;
	}

	@Override
	public int getMondayWorkSchedule() {
		return _mondayWorkSchedule;
	}

	@Override
	public void setMondayWorkSchedule(int mondayWorkSchedule) {
		_mondayWorkSchedule = mondayWorkSchedule;
	}

	@Override
	public int getTuesdayWorkSchedule() {
		return _tuesdayWorkSchedule;
	}

	@Override
	public void setTuesdayWorkSchedule(int tuesdayWorkSchedule) {
		_tuesdayWorkSchedule = tuesdayWorkSchedule;
	}

	@Override
	public int getWednesdayWorkSchedule() {
		return _wednesdayWorkSchedule;
	}

	@Override
	public void setWednesdayWorkSchedule(int wednesdayWorkSchedule) {
		_wednesdayWorkSchedule = wednesdayWorkSchedule;
	}

	@Override
	public int getThursdayWorkSchedule() {
		return _thursdayWorkSchedule;
	}

	@Override
	public void setThursdayWorkSchedule(int thursdayWorkSchedule) {
		_thursdayWorkSchedule = thursdayWorkSchedule;
	}

	@Override
	public int getFridayWorkSchedule() {
		return _fridayWorkSchedule;
	}

	@Override
	public void setFridayWorkSchedule(int fridayWorkSchedule) {
		_fridayWorkSchedule = fridayWorkSchedule;
	}

	@Override
	public int getSaturdayWorkSchedule() {
		return _saturdayWorkSchedule;
	}

	@Override
	public void setSaturdayWorkSchedule(int saturdayWorkSchedule) {
		_saturdayWorkSchedule = saturdayWorkSchedule;
	}

	@Override
	public int getSundayWorkSchedule() {
		return _sundayWorkSchedule;
	}

	@Override
	public void setSundayWorkSchedule(int sundayWorkSchedule) {
		_sundayWorkSchedule = sundayWorkSchedule;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			WorkWeek.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WorkWeek toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (WorkWeek)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WorkWeekImpl workWeekImpl = new WorkWeekImpl();

		workWeekImpl.setWorkWeekId(getWorkWeekId());
		workWeekImpl.setNationalityId(getNationalityId());
		workWeekImpl.setMondayWorkSchedule(getMondayWorkSchedule());
		workWeekImpl.setTuesdayWorkSchedule(getTuesdayWorkSchedule());
		workWeekImpl.setWednesdayWorkSchedule(getWednesdayWorkSchedule());
		workWeekImpl.setThursdayWorkSchedule(getThursdayWorkSchedule());
		workWeekImpl.setFridayWorkSchedule(getFridayWorkSchedule());
		workWeekImpl.setSaturdayWorkSchedule(getSaturdayWorkSchedule());
		workWeekImpl.setSundayWorkSchedule(getSundayWorkSchedule());
		workWeekImpl.setGroupId(getGroupId());
		workWeekImpl.setCompanyId(getCompanyId());
		workWeekImpl.setUserId(getUserId());
		workWeekImpl.setUserName(getUserName());
		workWeekImpl.setCreateDate(getCreateDate());
		workWeekImpl.setModifiedDate(getModifiedDate());

		workWeekImpl.resetOriginalValues();

		return workWeekImpl;
	}

	@Override
	public int compareTo(WorkWeek workWeek) {
		long primaryKey = workWeek.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof WorkWeek)) {
			return false;
		}

		WorkWeek workWeek = (WorkWeek)obj;

		long primaryKey = workWeek.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		WorkWeekModelImpl workWeekModelImpl = this;

		workWeekModelImpl._originalNationalityId = workWeekModelImpl._nationalityId;

		workWeekModelImpl._setOriginalNationalityId = false;

		workWeekModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<WorkWeek> toCacheModel() {
		WorkWeekCacheModel workWeekCacheModel = new WorkWeekCacheModel();

		workWeekCacheModel.workWeekId = getWorkWeekId();

		workWeekCacheModel.nationalityId = getNationalityId();

		workWeekCacheModel.mondayWorkSchedule = getMondayWorkSchedule();

		workWeekCacheModel.tuesdayWorkSchedule = getTuesdayWorkSchedule();

		workWeekCacheModel.wednesdayWorkSchedule = getWednesdayWorkSchedule();

		workWeekCacheModel.thursdayWorkSchedule = getThursdayWorkSchedule();

		workWeekCacheModel.fridayWorkSchedule = getFridayWorkSchedule();

		workWeekCacheModel.saturdayWorkSchedule = getSaturdayWorkSchedule();

		workWeekCacheModel.sundayWorkSchedule = getSundayWorkSchedule();

		workWeekCacheModel.groupId = getGroupId();

		workWeekCacheModel.companyId = getCompanyId();

		workWeekCacheModel.userId = getUserId();

		workWeekCacheModel.userName = getUserName();

		String userName = workWeekCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			workWeekCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			workWeekCacheModel.createDate = createDate.getTime();
		}
		else {
			workWeekCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			workWeekCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			workWeekCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return workWeekCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{workWeekId=");
		sb.append(getWorkWeekId());
		sb.append(", nationalityId=");
		sb.append(getNationalityId());
		sb.append(", mondayWorkSchedule=");
		sb.append(getMondayWorkSchedule());
		sb.append(", tuesdayWorkSchedule=");
		sb.append(getTuesdayWorkSchedule());
		sb.append(", wednesdayWorkSchedule=");
		sb.append(getWednesdayWorkSchedule());
		sb.append(", thursdayWorkSchedule=");
		sb.append(getThursdayWorkSchedule());
		sb.append(", fridayWorkSchedule=");
		sb.append(getFridayWorkSchedule());
		sb.append(", saturdayWorkSchedule=");
		sb.append(getSaturdayWorkSchedule());
		sb.append(", sundayWorkSchedule=");
		sb.append(getSundayWorkSchedule());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("com.rknowsys.eapp.hrm.model.WorkWeek");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>workWeekId</column-name><column-value><![CDATA[");
		sb.append(getWorkWeekId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nationalityId</column-name><column-value><![CDATA[");
		sb.append(getNationalityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mondayWorkSchedule</column-name><column-value><![CDATA[");
		sb.append(getMondayWorkSchedule());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tuesdayWorkSchedule</column-name><column-value><![CDATA[");
		sb.append(getTuesdayWorkSchedule());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wednesdayWorkSchedule</column-name><column-value><![CDATA[");
		sb.append(getWednesdayWorkSchedule());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thursdayWorkSchedule</column-name><column-value><![CDATA[");
		sb.append(getThursdayWorkSchedule());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fridayWorkSchedule</column-name><column-value><![CDATA[");
		sb.append(getFridayWorkSchedule());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>saturdayWorkSchedule</column-name><column-value><![CDATA[");
		sb.append(getSaturdayWorkSchedule());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sundayWorkSchedule</column-name><column-value><![CDATA[");
		sb.append(getSundayWorkSchedule());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = WorkWeek.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			WorkWeek.class
		};
	private long _workWeekId;
	private long _nationalityId;
	private long _originalNationalityId;
	private boolean _setOriginalNationalityId;
	private int _mondayWorkSchedule;
	private int _tuesdayWorkSchedule;
	private int _wednesdayWorkSchedule;
	private int _thursdayWorkSchedule;
	private int _fridayWorkSchedule;
	private int _saturdayWorkSchedule;
	private int _sundayWorkSchedule;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _columnBitmask;
	private WorkWeek _escapedModel;
}