/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import com.rknowsys.eapp.hrm.model.EmploymentStatus;
import com.rknowsys.eapp.hrm.service.EmploymentStatusLocalService;
import com.rknowsys.eapp.hrm.service.persistence.AttachmentPersistence;
import com.rknowsys.eapp.hrm.service.persistence.ContactDetailsPersistence;
import com.rknowsys.eapp.hrm.service.persistence.DependentPersistence;
import com.rknowsys.eapp.hrm.service.persistence.DocCategoryPersistence;
import com.rknowsys.eapp.hrm.service.persistence.EducationPersistence;
import com.rknowsys.eapp.hrm.service.persistence.EmergencyContactPersistence;
import com.rknowsys.eapp.hrm.service.persistence.EmployeePersistence;
import com.rknowsys.eapp.hrm.service.persistence.EmploymentStatusPersistence;
import com.rknowsys.eapp.hrm.service.persistence.ImmigrationDocumentPersistence;
import com.rknowsys.eapp.hrm.service.persistence.InterviewPersistence;
import com.rknowsys.eapp.hrm.service.persistence.JobCategoryPersistence;
import com.rknowsys.eapp.hrm.service.persistence.JobPersistence;
import com.rknowsys.eapp.hrm.service.persistence.JobTitlePersistence;
import com.rknowsys.eapp.hrm.service.persistence.LanguagePersistence;
import com.rknowsys.eapp.hrm.service.persistence.LicensePersistence;
import com.rknowsys.eapp.hrm.service.persistence.LocationPersistence;
import com.rknowsys.eapp.hrm.service.persistence.MembershipPersistence;
import com.rknowsys.eapp.hrm.service.persistence.NationalityPersistence;
import com.rknowsys.eapp.hrm.service.persistence.NewsPersistence;
import com.rknowsys.eapp.hrm.service.persistence.OrganizationPersistence;
import com.rknowsys.eapp.hrm.service.persistence.PayGradeCurrencyPersistence;
import com.rknowsys.eapp.hrm.service.persistence.PayGradePersistence;
import com.rknowsys.eapp.hrm.service.persistence.SalaryComponentPersistence;
import com.rknowsys.eapp.hrm.service.persistence.SkillPersistence;
import com.rknowsys.eapp.hrm.service.persistence.SubUnitPersistence;
import com.rknowsys.eapp.hrm.service.persistence.SupervisorPersistence;
import com.rknowsys.eapp.hrm.service.persistence.WorkExpCompanyPersistence;
import com.rknowsys.eapp.hrm.service.persistence.WorkshiftPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the employment status local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.rknowsys.eapp.hrm.service.impl.EmploymentStatusLocalServiceImpl}.
 * </p>
 *
 * @author rknowsys
 * @see com.rknowsys.eapp.hrm.service.impl.EmploymentStatusLocalServiceImpl
 * @see com.rknowsys.eapp.hrm.service.EmploymentStatusLocalServiceUtil
 * @generated
 */
public abstract class EmploymentStatusLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements EmploymentStatusLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.rknowsys.eapp.hrm.service.EmploymentStatusLocalServiceUtil} to access the employment status local service.
	 */

	/**
	 * Adds the employment status to the database. Also notifies the appropriate model listeners.
	 *
	 * @param employmentStatus the employment status
	 * @return the employment status that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EmploymentStatus addEmploymentStatus(
		EmploymentStatus employmentStatus) throws SystemException {
		employmentStatus.setNew(true);

		return employmentStatusPersistence.update(employmentStatus);
	}

	/**
	 * Creates a new employment status with the primary key. Does not add the employment status to the database.
	 *
	 * @param employmentStatusId the primary key for the new employment status
	 * @return the new employment status
	 */
	@Override
	public EmploymentStatus createEmploymentStatus(long employmentStatusId) {
		return employmentStatusPersistence.create(employmentStatusId);
	}

	/**
	 * Deletes the employment status with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param employmentStatusId the primary key of the employment status
	 * @return the employment status that was removed
	 * @throws PortalException if a employment status with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EmploymentStatus deleteEmploymentStatus(long employmentStatusId)
		throws PortalException, SystemException {
		return employmentStatusPersistence.remove(employmentStatusId);
	}

	/**
	 * Deletes the employment status from the database. Also notifies the appropriate model listeners.
	 *
	 * @param employmentStatus the employment status
	 * @return the employment status that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EmploymentStatus deleteEmploymentStatus(
		EmploymentStatus employmentStatus) throws SystemException {
		return employmentStatusPersistence.remove(employmentStatus);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(EmploymentStatus.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return employmentStatusPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rknowsys.eapp.hrm.model.impl.EmploymentStatusModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return employmentStatusPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rknowsys.eapp.hrm.model.impl.EmploymentStatusModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return employmentStatusPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return employmentStatusPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return employmentStatusPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public EmploymentStatus fetchEmploymentStatus(long employmentStatusId)
		throws SystemException {
		return employmentStatusPersistence.fetchByPrimaryKey(employmentStatusId);
	}

	/**
	 * Returns the employment status with the primary key.
	 *
	 * @param employmentStatusId the primary key of the employment status
	 * @return the employment status
	 * @throws PortalException if a employment status with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public EmploymentStatus getEmploymentStatus(long employmentStatusId)
		throws PortalException, SystemException {
		return employmentStatusPersistence.findByPrimaryKey(employmentStatusId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return employmentStatusPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the employment statuses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rknowsys.eapp.hrm.model.impl.EmploymentStatusModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of employment statuses
	 * @param end the upper bound of the range of employment statuses (not inclusive)
	 * @return the range of employment statuses
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<EmploymentStatus> getEmploymentStatuses(int start, int end)
		throws SystemException {
		return employmentStatusPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of employment statuses.
	 *
	 * @return the number of employment statuses
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getEmploymentStatusesCount() throws SystemException {
		return employmentStatusPersistence.countAll();
	}

	/**
	 * Updates the employment status in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param employmentStatus the employment status
	 * @return the employment status that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EmploymentStatus updateEmploymentStatus(
		EmploymentStatus employmentStatus) throws SystemException {
		return employmentStatusPersistence.update(employmentStatus);
	}

	/**
	 * Returns the attachment local service.
	 *
	 * @return the attachment local service
	 */
	public com.rknowsys.eapp.hrm.service.AttachmentLocalService getAttachmentLocalService() {
		return attachmentLocalService;
	}

	/**
	 * Sets the attachment local service.
	 *
	 * @param attachmentLocalService the attachment local service
	 */
	public void setAttachmentLocalService(
		com.rknowsys.eapp.hrm.service.AttachmentLocalService attachmentLocalService) {
		this.attachmentLocalService = attachmentLocalService;
	}

	/**
	 * Returns the attachment persistence.
	 *
	 * @return the attachment persistence
	 */
	public AttachmentPersistence getAttachmentPersistence() {
		return attachmentPersistence;
	}

	/**
	 * Sets the attachment persistence.
	 *
	 * @param attachmentPersistence the attachment persistence
	 */
	public void setAttachmentPersistence(
		AttachmentPersistence attachmentPersistence) {
		this.attachmentPersistence = attachmentPersistence;
	}

	/**
	 * Returns the ContactDetails local service.
	 *
	 * @return the ContactDetails local service
	 */
	public com.rknowsys.eapp.hrm.service.ContactDetailsLocalService getContactDetailsLocalService() {
		return contactDetailsLocalService;
	}

	/**
	 * Sets the ContactDetails local service.
	 *
	 * @param contactDetailsLocalService the ContactDetails local service
	 */
	public void setContactDetailsLocalService(
		com.rknowsys.eapp.hrm.service.ContactDetailsLocalService contactDetailsLocalService) {
		this.contactDetailsLocalService = contactDetailsLocalService;
	}

	/**
	 * Returns the ContactDetails persistence.
	 *
	 * @return the ContactDetails persistence
	 */
	public ContactDetailsPersistence getContactDetailsPersistence() {
		return contactDetailsPersistence;
	}

	/**
	 * Sets the ContactDetails persistence.
	 *
	 * @param contactDetailsPersistence the ContactDetails persistence
	 */
	public void setContactDetailsPersistence(
		ContactDetailsPersistence contactDetailsPersistence) {
		this.contactDetailsPersistence = contactDetailsPersistence;
	}

	/**
	 * Returns the dependent local service.
	 *
	 * @return the dependent local service
	 */
	public com.rknowsys.eapp.hrm.service.DependentLocalService getDependentLocalService() {
		return dependentLocalService;
	}

	/**
	 * Sets the dependent local service.
	 *
	 * @param dependentLocalService the dependent local service
	 */
	public void setDependentLocalService(
		com.rknowsys.eapp.hrm.service.DependentLocalService dependentLocalService) {
		this.dependentLocalService = dependentLocalService;
	}

	/**
	 * Returns the dependent persistence.
	 *
	 * @return the dependent persistence
	 */
	public DependentPersistence getDependentPersistence() {
		return dependentPersistence;
	}

	/**
	 * Sets the dependent persistence.
	 *
	 * @param dependentPersistence the dependent persistence
	 */
	public void setDependentPersistence(
		DependentPersistence dependentPersistence) {
		this.dependentPersistence = dependentPersistence;
	}

	/**
	 * Returns the doc category local service.
	 *
	 * @return the doc category local service
	 */
	public com.rknowsys.eapp.hrm.service.DocCategoryLocalService getDocCategoryLocalService() {
		return docCategoryLocalService;
	}

	/**
	 * Sets the doc category local service.
	 *
	 * @param docCategoryLocalService the doc category local service
	 */
	public void setDocCategoryLocalService(
		com.rknowsys.eapp.hrm.service.DocCategoryLocalService docCategoryLocalService) {
		this.docCategoryLocalService = docCategoryLocalService;
	}

	/**
	 * Returns the doc category persistence.
	 *
	 * @return the doc category persistence
	 */
	public DocCategoryPersistence getDocCategoryPersistence() {
		return docCategoryPersistence;
	}

	/**
	 * Sets the doc category persistence.
	 *
	 * @param docCategoryPersistence the doc category persistence
	 */
	public void setDocCategoryPersistence(
		DocCategoryPersistence docCategoryPersistence) {
		this.docCategoryPersistence = docCategoryPersistence;
	}

	/**
	 * Returns the education local service.
	 *
	 * @return the education local service
	 */
	public com.rknowsys.eapp.hrm.service.EducationLocalService getEducationLocalService() {
		return educationLocalService;
	}

	/**
	 * Sets the education local service.
	 *
	 * @param educationLocalService the education local service
	 */
	public void setEducationLocalService(
		com.rknowsys.eapp.hrm.service.EducationLocalService educationLocalService) {
		this.educationLocalService = educationLocalService;
	}

	/**
	 * Returns the education persistence.
	 *
	 * @return the education persistence
	 */
	public EducationPersistence getEducationPersistence() {
		return educationPersistence;
	}

	/**
	 * Sets the education persistence.
	 *
	 * @param educationPersistence the education persistence
	 */
	public void setEducationPersistence(
		EducationPersistence educationPersistence) {
		this.educationPersistence = educationPersistence;
	}

	/**
	 * Returns the EmergencyContact local service.
	 *
	 * @return the EmergencyContact local service
	 */
	public com.rknowsys.eapp.hrm.service.EmergencyContactLocalService getEmergencyContactLocalService() {
		return emergencyContactLocalService;
	}

	/**
	 * Sets the EmergencyContact local service.
	 *
	 * @param emergencyContactLocalService the EmergencyContact local service
	 */
	public void setEmergencyContactLocalService(
		com.rknowsys.eapp.hrm.service.EmergencyContactLocalService emergencyContactLocalService) {
		this.emergencyContactLocalService = emergencyContactLocalService;
	}

	/**
	 * Returns the EmergencyContact persistence.
	 *
	 * @return the EmergencyContact persistence
	 */
	public EmergencyContactPersistence getEmergencyContactPersistence() {
		return emergencyContactPersistence;
	}

	/**
	 * Sets the EmergencyContact persistence.
	 *
	 * @param emergencyContactPersistence the EmergencyContact persistence
	 */
	public void setEmergencyContactPersistence(
		EmergencyContactPersistence emergencyContactPersistence) {
		this.emergencyContactPersistence = emergencyContactPersistence;
	}

	/**
	 * Returns the Employee local service.
	 *
	 * @return the Employee local service
	 */
	public com.rknowsys.eapp.hrm.service.EmployeeLocalService getEmployeeLocalService() {
		return employeeLocalService;
	}

	/**
	 * Sets the Employee local service.
	 *
	 * @param employeeLocalService the Employee local service
	 */
	public void setEmployeeLocalService(
		com.rknowsys.eapp.hrm.service.EmployeeLocalService employeeLocalService) {
		this.employeeLocalService = employeeLocalService;
	}

	/**
	 * Returns the Employee persistence.
	 *
	 * @return the Employee persistence
	 */
	public EmployeePersistence getEmployeePersistence() {
		return employeePersistence;
	}

	/**
	 * Sets the Employee persistence.
	 *
	 * @param employeePersistence the Employee persistence
	 */
	public void setEmployeePersistence(EmployeePersistence employeePersistence) {
		this.employeePersistence = employeePersistence;
	}

	/**
	 * Returns the employment status local service.
	 *
	 * @return the employment status local service
	 */
	public com.rknowsys.eapp.hrm.service.EmploymentStatusLocalService getEmploymentStatusLocalService() {
		return employmentStatusLocalService;
	}

	/**
	 * Sets the employment status local service.
	 *
	 * @param employmentStatusLocalService the employment status local service
	 */
	public void setEmploymentStatusLocalService(
		com.rknowsys.eapp.hrm.service.EmploymentStatusLocalService employmentStatusLocalService) {
		this.employmentStatusLocalService = employmentStatusLocalService;
	}

	/**
	 * Returns the employment status persistence.
	 *
	 * @return the employment status persistence
	 */
	public EmploymentStatusPersistence getEmploymentStatusPersistence() {
		return employmentStatusPersistence;
	}

	/**
	 * Sets the employment status persistence.
	 *
	 * @param employmentStatusPersistence the employment status persistence
	 */
	public void setEmploymentStatusPersistence(
		EmploymentStatusPersistence employmentStatusPersistence) {
		this.employmentStatusPersistence = employmentStatusPersistence;
	}

	/**
	 * Returns the ImmigrationDocument local service.
	 *
	 * @return the ImmigrationDocument local service
	 */
	public com.rknowsys.eapp.hrm.service.ImmigrationDocumentLocalService getImmigrationDocumentLocalService() {
		return immigrationDocumentLocalService;
	}

	/**
	 * Sets the ImmigrationDocument local service.
	 *
	 * @param immigrationDocumentLocalService the ImmigrationDocument local service
	 */
	public void setImmigrationDocumentLocalService(
		com.rknowsys.eapp.hrm.service.ImmigrationDocumentLocalService immigrationDocumentLocalService) {
		this.immigrationDocumentLocalService = immigrationDocumentLocalService;
	}

	/**
	 * Returns the ImmigrationDocument persistence.
	 *
	 * @return the ImmigrationDocument persistence
	 */
	public ImmigrationDocumentPersistence getImmigrationDocumentPersistence() {
		return immigrationDocumentPersistence;
	}

	/**
	 * Sets the ImmigrationDocument persistence.
	 *
	 * @param immigrationDocumentPersistence the ImmigrationDocument persistence
	 */
	public void setImmigrationDocumentPersistence(
		ImmigrationDocumentPersistence immigrationDocumentPersistence) {
		this.immigrationDocumentPersistence = immigrationDocumentPersistence;
	}

	/**
	 * Returns the interview local service.
	 *
	 * @return the interview local service
	 */
	public com.rknowsys.eapp.hrm.service.InterviewLocalService getInterviewLocalService() {
		return interviewLocalService;
	}

	/**
	 * Sets the interview local service.
	 *
	 * @param interviewLocalService the interview local service
	 */
	public void setInterviewLocalService(
		com.rknowsys.eapp.hrm.service.InterviewLocalService interviewLocalService) {
		this.interviewLocalService = interviewLocalService;
	}

	/**
	 * Returns the interview persistence.
	 *
	 * @return the interview persistence
	 */
	public InterviewPersistence getInterviewPersistence() {
		return interviewPersistence;
	}

	/**
	 * Sets the interview persistence.
	 *
	 * @param interviewPersistence the interview persistence
	 */
	public void setInterviewPersistence(
		InterviewPersistence interviewPersistence) {
		this.interviewPersistence = interviewPersistence;
	}

	/**
	 * Returns the job local service.
	 *
	 * @return the job local service
	 */
	public com.rknowsys.eapp.hrm.service.JobLocalService getJobLocalService() {
		return jobLocalService;
	}

	/**
	 * Sets the job local service.
	 *
	 * @param jobLocalService the job local service
	 */
	public void setJobLocalService(
		com.rknowsys.eapp.hrm.service.JobLocalService jobLocalService) {
		this.jobLocalService = jobLocalService;
	}

	/**
	 * Returns the job persistence.
	 *
	 * @return the job persistence
	 */
	public JobPersistence getJobPersistence() {
		return jobPersistence;
	}

	/**
	 * Sets the job persistence.
	 *
	 * @param jobPersistence the job persistence
	 */
	public void setJobPersistence(JobPersistence jobPersistence) {
		this.jobPersistence = jobPersistence;
	}

	/**
	 * Returns the job category local service.
	 *
	 * @return the job category local service
	 */
	public com.rknowsys.eapp.hrm.service.JobCategoryLocalService getJobCategoryLocalService() {
		return jobCategoryLocalService;
	}

	/**
	 * Sets the job category local service.
	 *
	 * @param jobCategoryLocalService the job category local service
	 */
	public void setJobCategoryLocalService(
		com.rknowsys.eapp.hrm.service.JobCategoryLocalService jobCategoryLocalService) {
		this.jobCategoryLocalService = jobCategoryLocalService;
	}

	/**
	 * Returns the job category persistence.
	 *
	 * @return the job category persistence
	 */
	public JobCategoryPersistence getJobCategoryPersistence() {
		return jobCategoryPersistence;
	}

	/**
	 * Sets the job category persistence.
	 *
	 * @param jobCategoryPersistence the job category persistence
	 */
	public void setJobCategoryPersistence(
		JobCategoryPersistence jobCategoryPersistence) {
		this.jobCategoryPersistence = jobCategoryPersistence;
	}

	/**
	 * Returns the job title local service.
	 *
	 * @return the job title local service
	 */
	public com.rknowsys.eapp.hrm.service.JobTitleLocalService getJobTitleLocalService() {
		return jobTitleLocalService;
	}

	/**
	 * Sets the job title local service.
	 *
	 * @param jobTitleLocalService the job title local service
	 */
	public void setJobTitleLocalService(
		com.rknowsys.eapp.hrm.service.JobTitleLocalService jobTitleLocalService) {
		this.jobTitleLocalService = jobTitleLocalService;
	}

	/**
	 * Returns the job title persistence.
	 *
	 * @return the job title persistence
	 */
	public JobTitlePersistence getJobTitlePersistence() {
		return jobTitlePersistence;
	}

	/**
	 * Sets the job title persistence.
	 *
	 * @param jobTitlePersistence the job title persistence
	 */
	public void setJobTitlePersistence(JobTitlePersistence jobTitlePersistence) {
		this.jobTitlePersistence = jobTitlePersistence;
	}

	/**
	 * Returns the language local service.
	 *
	 * @return the language local service
	 */
	public com.rknowsys.eapp.hrm.service.LanguageLocalService getLanguageLocalService() {
		return languageLocalService;
	}

	/**
	 * Sets the language local service.
	 *
	 * @param languageLocalService the language local service
	 */
	public void setLanguageLocalService(
		com.rknowsys.eapp.hrm.service.LanguageLocalService languageLocalService) {
		this.languageLocalService = languageLocalService;
	}

	/**
	 * Returns the language persistence.
	 *
	 * @return the language persistence
	 */
	public LanguagePersistence getLanguagePersistence() {
		return languagePersistence;
	}

	/**
	 * Sets the language persistence.
	 *
	 * @param languagePersistence the language persistence
	 */
	public void setLanguagePersistence(LanguagePersistence languagePersistence) {
		this.languagePersistence = languagePersistence;
	}

	/**
	 * Returns the license local service.
	 *
	 * @return the license local service
	 */
	public com.rknowsys.eapp.hrm.service.LicenseLocalService getLicenseLocalService() {
		return licenseLocalService;
	}

	/**
	 * Sets the license local service.
	 *
	 * @param licenseLocalService the license local service
	 */
	public void setLicenseLocalService(
		com.rknowsys.eapp.hrm.service.LicenseLocalService licenseLocalService) {
		this.licenseLocalService = licenseLocalService;
	}

	/**
	 * Returns the license persistence.
	 *
	 * @return the license persistence
	 */
	public LicensePersistence getLicensePersistence() {
		return licensePersistence;
	}

	/**
	 * Sets the license persistence.
	 *
	 * @param licensePersistence the license persistence
	 */
	public void setLicensePersistence(LicensePersistence licensePersistence) {
		this.licensePersistence = licensePersistence;
	}

	/**
	 * Returns the location local service.
	 *
	 * @return the location local service
	 */
	public com.rknowsys.eapp.hrm.service.LocationLocalService getLocationLocalService() {
		return locationLocalService;
	}

	/**
	 * Sets the location local service.
	 *
	 * @param locationLocalService the location local service
	 */
	public void setLocationLocalService(
		com.rknowsys.eapp.hrm.service.LocationLocalService locationLocalService) {
		this.locationLocalService = locationLocalService;
	}

	/**
	 * Returns the location persistence.
	 *
	 * @return the location persistence
	 */
	public LocationPersistence getLocationPersistence() {
		return locationPersistence;
	}

	/**
	 * Sets the location persistence.
	 *
	 * @param locationPersistence the location persistence
	 */
	public void setLocationPersistence(LocationPersistence locationPersistence) {
		this.locationPersistence = locationPersistence;
	}

	/**
	 * Returns the membership local service.
	 *
	 * @return the membership local service
	 */
	public com.rknowsys.eapp.hrm.service.MembershipLocalService getMembershipLocalService() {
		return membershipLocalService;
	}

	/**
	 * Sets the membership local service.
	 *
	 * @param membershipLocalService the membership local service
	 */
	public void setMembershipLocalService(
		com.rknowsys.eapp.hrm.service.MembershipLocalService membershipLocalService) {
		this.membershipLocalService = membershipLocalService;
	}

	/**
	 * Returns the membership persistence.
	 *
	 * @return the membership persistence
	 */
	public MembershipPersistence getMembershipPersistence() {
		return membershipPersistence;
	}

	/**
	 * Sets the membership persistence.
	 *
	 * @param membershipPersistence the membership persistence
	 */
	public void setMembershipPersistence(
		MembershipPersistence membershipPersistence) {
		this.membershipPersistence = membershipPersistence;
	}

	/**
	 * Returns the Nationality local service.
	 *
	 * @return the Nationality local service
	 */
	public com.rknowsys.eapp.hrm.service.NationalityLocalService getNationalityLocalService() {
		return nationalityLocalService;
	}

	/**
	 * Sets the Nationality local service.
	 *
	 * @param nationalityLocalService the Nationality local service
	 */
	public void setNationalityLocalService(
		com.rknowsys.eapp.hrm.service.NationalityLocalService nationalityLocalService) {
		this.nationalityLocalService = nationalityLocalService;
	}

	/**
	 * Returns the Nationality persistence.
	 *
	 * @return the Nationality persistence
	 */
	public NationalityPersistence getNationalityPersistence() {
		return nationalityPersistence;
	}

	/**
	 * Sets the Nationality persistence.
	 *
	 * @param nationalityPersistence the Nationality persistence
	 */
	public void setNationalityPersistence(
		NationalityPersistence nationalityPersistence) {
		this.nationalityPersistence = nationalityPersistence;
	}

	/**
	 * Returns the news local service.
	 *
	 * @return the news local service
	 */
	public com.rknowsys.eapp.hrm.service.NewsLocalService getNewsLocalService() {
		return newsLocalService;
	}

	/**
	 * Sets the news local service.
	 *
	 * @param newsLocalService the news local service
	 */
	public void setNewsLocalService(
		com.rknowsys.eapp.hrm.service.NewsLocalService newsLocalService) {
		this.newsLocalService = newsLocalService;
	}

	/**
	 * Returns the news persistence.
	 *
	 * @return the news persistence
	 */
	public NewsPersistence getNewsPersistence() {
		return newsPersistence;
	}

	/**
	 * Sets the news persistence.
	 *
	 * @param newsPersistence the news persistence
	 */
	public void setNewsPersistence(NewsPersistence newsPersistence) {
		this.newsPersistence = newsPersistence;
	}

	/**
	 * Returns the organization local service.
	 *
	 * @return the organization local service
	 */
	public com.rknowsys.eapp.hrm.service.OrganizationLocalService getOrganizationLocalService() {
		return organizationLocalService;
	}

	/**
	 * Sets the organization local service.
	 *
	 * @param organizationLocalService the organization local service
	 */
	public void setOrganizationLocalService(
		com.rknowsys.eapp.hrm.service.OrganizationLocalService organizationLocalService) {
		this.organizationLocalService = organizationLocalService;
	}

	/**
	 * Returns the organization persistence.
	 *
	 * @return the organization persistence
	 */
	public OrganizationPersistence getOrganizationPersistence() {
		return organizationPersistence;
	}

	/**
	 * Sets the organization persistence.
	 *
	 * @param organizationPersistence the organization persistence
	 */
	public void setOrganizationPersistence(
		OrganizationPersistence organizationPersistence) {
		this.organizationPersistence = organizationPersistence;
	}

	/**
	 * Returns the pay grade local service.
	 *
	 * @return the pay grade local service
	 */
	public com.rknowsys.eapp.hrm.service.PayGradeLocalService getPayGradeLocalService() {
		return payGradeLocalService;
	}

	/**
	 * Sets the pay grade local service.
	 *
	 * @param payGradeLocalService the pay grade local service
	 */
	public void setPayGradeLocalService(
		com.rknowsys.eapp.hrm.service.PayGradeLocalService payGradeLocalService) {
		this.payGradeLocalService = payGradeLocalService;
	}

	/**
	 * Returns the pay grade persistence.
	 *
	 * @return the pay grade persistence
	 */
	public PayGradePersistence getPayGradePersistence() {
		return payGradePersistence;
	}

	/**
	 * Sets the pay grade persistence.
	 *
	 * @param payGradePersistence the pay grade persistence
	 */
	public void setPayGradePersistence(PayGradePersistence payGradePersistence) {
		this.payGradePersistence = payGradePersistence;
	}

	/**
	 * Returns the pay grade currency local service.
	 *
	 * @return the pay grade currency local service
	 */
	public com.rknowsys.eapp.hrm.service.PayGradeCurrencyLocalService getPayGradeCurrencyLocalService() {
		return payGradeCurrencyLocalService;
	}

	/**
	 * Sets the pay grade currency local service.
	 *
	 * @param payGradeCurrencyLocalService the pay grade currency local service
	 */
	public void setPayGradeCurrencyLocalService(
		com.rknowsys.eapp.hrm.service.PayGradeCurrencyLocalService payGradeCurrencyLocalService) {
		this.payGradeCurrencyLocalService = payGradeCurrencyLocalService;
	}

	/**
	 * Returns the pay grade currency persistence.
	 *
	 * @return the pay grade currency persistence
	 */
	public PayGradeCurrencyPersistence getPayGradeCurrencyPersistence() {
		return payGradeCurrencyPersistence;
	}

	/**
	 * Sets the pay grade currency persistence.
	 *
	 * @param payGradeCurrencyPersistence the pay grade currency persistence
	 */
	public void setPayGradeCurrencyPersistence(
		PayGradeCurrencyPersistence payGradeCurrencyPersistence) {
		this.payGradeCurrencyPersistence = payGradeCurrencyPersistence;
	}

	/**
	 * Returns the salary component local service.
	 *
	 * @return the salary component local service
	 */
	public com.rknowsys.eapp.hrm.service.SalaryComponentLocalService getSalaryComponentLocalService() {
		return salaryComponentLocalService;
	}

	/**
	 * Sets the salary component local service.
	 *
	 * @param salaryComponentLocalService the salary component local service
	 */
	public void setSalaryComponentLocalService(
		com.rknowsys.eapp.hrm.service.SalaryComponentLocalService salaryComponentLocalService) {
		this.salaryComponentLocalService = salaryComponentLocalService;
	}

	/**
	 * Returns the salary component persistence.
	 *
	 * @return the salary component persistence
	 */
	public SalaryComponentPersistence getSalaryComponentPersistence() {
		return salaryComponentPersistence;
	}

	/**
	 * Sets the salary component persistence.
	 *
	 * @param salaryComponentPersistence the salary component persistence
	 */
	public void setSalaryComponentPersistence(
		SalaryComponentPersistence salaryComponentPersistence) {
		this.salaryComponentPersistence = salaryComponentPersistence;
	}

	/**
	 * Returns the skill local service.
	 *
	 * @return the skill local service
	 */
	public com.rknowsys.eapp.hrm.service.SkillLocalService getSkillLocalService() {
		return skillLocalService;
	}

	/**
	 * Sets the skill local service.
	 *
	 * @param skillLocalService the skill local service
	 */
	public void setSkillLocalService(
		com.rknowsys.eapp.hrm.service.SkillLocalService skillLocalService) {
		this.skillLocalService = skillLocalService;
	}

	/**
	 * Returns the skill persistence.
	 *
	 * @return the skill persistence
	 */
	public SkillPersistence getSkillPersistence() {
		return skillPersistence;
	}

	/**
	 * Sets the skill persistence.
	 *
	 * @param skillPersistence the skill persistence
	 */
	public void setSkillPersistence(SkillPersistence skillPersistence) {
		this.skillPersistence = skillPersistence;
	}

	/**
	 * Returns the SubUnit local service.
	 *
	 * @return the SubUnit local service
	 */
	public com.rknowsys.eapp.hrm.service.SubUnitLocalService getSubUnitLocalService() {
		return subUnitLocalService;
	}

	/**
	 * Sets the SubUnit local service.
	 *
	 * @param subUnitLocalService the SubUnit local service
	 */
	public void setSubUnitLocalService(
		com.rknowsys.eapp.hrm.service.SubUnitLocalService subUnitLocalService) {
		this.subUnitLocalService = subUnitLocalService;
	}

	/**
	 * Returns the SubUnit persistence.
	 *
	 * @return the SubUnit persistence
	 */
	public SubUnitPersistence getSubUnitPersistence() {
		return subUnitPersistence;
	}

	/**
	 * Sets the SubUnit persistence.
	 *
	 * @param subUnitPersistence the SubUnit persistence
	 */
	public void setSubUnitPersistence(SubUnitPersistence subUnitPersistence) {
		this.subUnitPersistence = subUnitPersistence;
	}

	/**
	 * Returns the Supervisor local service.
	 *
	 * @return the Supervisor local service
	 */
	public com.rknowsys.eapp.hrm.service.SupervisorLocalService getSupervisorLocalService() {
		return supervisorLocalService;
	}

	/**
	 * Sets the Supervisor local service.
	 *
	 * @param supervisorLocalService the Supervisor local service
	 */
	public void setSupervisorLocalService(
		com.rknowsys.eapp.hrm.service.SupervisorLocalService supervisorLocalService) {
		this.supervisorLocalService = supervisorLocalService;
	}

	/**
	 * Returns the Supervisor persistence.
	 *
	 * @return the Supervisor persistence
	 */
	public SupervisorPersistence getSupervisorPersistence() {
		return supervisorPersistence;
	}

	/**
	 * Sets the Supervisor persistence.
	 *
	 * @param supervisorPersistence the Supervisor persistence
	 */
	public void setSupervisorPersistence(
		SupervisorPersistence supervisorPersistence) {
		this.supervisorPersistence = supervisorPersistence;
	}

	/**
	 * Returns the WorkExpCompany local service.
	 *
	 * @return the WorkExpCompany local service
	 */
	public com.rknowsys.eapp.hrm.service.WorkExpCompanyLocalService getWorkExpCompanyLocalService() {
		return workExpCompanyLocalService;
	}

	/**
	 * Sets the WorkExpCompany local service.
	 *
	 * @param workExpCompanyLocalService the WorkExpCompany local service
	 */
	public void setWorkExpCompanyLocalService(
		com.rknowsys.eapp.hrm.service.WorkExpCompanyLocalService workExpCompanyLocalService) {
		this.workExpCompanyLocalService = workExpCompanyLocalService;
	}

	/**
	 * Returns the WorkExpCompany persistence.
	 *
	 * @return the WorkExpCompany persistence
	 */
	public WorkExpCompanyPersistence getWorkExpCompanyPersistence() {
		return workExpCompanyPersistence;
	}

	/**
	 * Sets the WorkExpCompany persistence.
	 *
	 * @param workExpCompanyPersistence the WorkExpCompany persistence
	 */
	public void setWorkExpCompanyPersistence(
		WorkExpCompanyPersistence workExpCompanyPersistence) {
		this.workExpCompanyPersistence = workExpCompanyPersistence;
	}

	/**
	 * Returns the workshift local service.
	 *
	 * @return the workshift local service
	 */
	public com.rknowsys.eapp.hrm.service.WorkshiftLocalService getWorkshiftLocalService() {
		return workshiftLocalService;
	}

	/**
	 * Sets the workshift local service.
	 *
	 * @param workshiftLocalService the workshift local service
	 */
	public void setWorkshiftLocalService(
		com.rknowsys.eapp.hrm.service.WorkshiftLocalService workshiftLocalService) {
		this.workshiftLocalService = workshiftLocalService;
	}

	/**
	 * Returns the workshift persistence.
	 *
	 * @return the workshift persistence
	 */
	public WorkshiftPersistence getWorkshiftPersistence() {
		return workshiftPersistence;
	}

	/**
	 * Sets the workshift persistence.
	 *
	 * @param workshiftPersistence the workshift persistence
	 */
	public void setWorkshiftPersistence(
		WorkshiftPersistence workshiftPersistence) {
		this.workshiftPersistence = workshiftPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.rknowsys.eapp.hrm.model.EmploymentStatus",
			employmentStatusLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.rknowsys.eapp.hrm.model.EmploymentStatus");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return EmploymentStatus.class;
	}

	protected String getModelClassName() {
		return EmploymentStatus.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = employmentStatusPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.rknowsys.eapp.hrm.service.AttachmentLocalService.class)
	protected com.rknowsys.eapp.hrm.service.AttachmentLocalService attachmentLocalService;
	@BeanReference(type = AttachmentPersistence.class)
	protected AttachmentPersistence attachmentPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.ContactDetailsLocalService.class)
	protected com.rknowsys.eapp.hrm.service.ContactDetailsLocalService contactDetailsLocalService;
	@BeanReference(type = ContactDetailsPersistence.class)
	protected ContactDetailsPersistence contactDetailsPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.DependentLocalService.class)
	protected com.rknowsys.eapp.hrm.service.DependentLocalService dependentLocalService;
	@BeanReference(type = DependentPersistence.class)
	protected DependentPersistence dependentPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.DocCategoryLocalService.class)
	protected com.rknowsys.eapp.hrm.service.DocCategoryLocalService docCategoryLocalService;
	@BeanReference(type = DocCategoryPersistence.class)
	protected DocCategoryPersistence docCategoryPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.EducationLocalService.class)
	protected com.rknowsys.eapp.hrm.service.EducationLocalService educationLocalService;
	@BeanReference(type = EducationPersistence.class)
	protected EducationPersistence educationPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.EmergencyContactLocalService.class)
	protected com.rknowsys.eapp.hrm.service.EmergencyContactLocalService emergencyContactLocalService;
	@BeanReference(type = EmergencyContactPersistence.class)
	protected EmergencyContactPersistence emergencyContactPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.EmployeeLocalService.class)
	protected com.rknowsys.eapp.hrm.service.EmployeeLocalService employeeLocalService;
	@BeanReference(type = EmployeePersistence.class)
	protected EmployeePersistence employeePersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.EmploymentStatusLocalService.class)
	protected com.rknowsys.eapp.hrm.service.EmploymentStatusLocalService employmentStatusLocalService;
	@BeanReference(type = EmploymentStatusPersistence.class)
	protected EmploymentStatusPersistence employmentStatusPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.ImmigrationDocumentLocalService.class)
	protected com.rknowsys.eapp.hrm.service.ImmigrationDocumentLocalService immigrationDocumentLocalService;
	@BeanReference(type = ImmigrationDocumentPersistence.class)
	protected ImmigrationDocumentPersistence immigrationDocumentPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.InterviewLocalService.class)
	protected com.rknowsys.eapp.hrm.service.InterviewLocalService interviewLocalService;
	@BeanReference(type = InterviewPersistence.class)
	protected InterviewPersistence interviewPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.JobLocalService.class)
	protected com.rknowsys.eapp.hrm.service.JobLocalService jobLocalService;
	@BeanReference(type = JobPersistence.class)
	protected JobPersistence jobPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.JobCategoryLocalService.class)
	protected com.rknowsys.eapp.hrm.service.JobCategoryLocalService jobCategoryLocalService;
	@BeanReference(type = JobCategoryPersistence.class)
	protected JobCategoryPersistence jobCategoryPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.JobTitleLocalService.class)
	protected com.rknowsys.eapp.hrm.service.JobTitleLocalService jobTitleLocalService;
	@BeanReference(type = JobTitlePersistence.class)
	protected JobTitlePersistence jobTitlePersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.LanguageLocalService.class)
	protected com.rknowsys.eapp.hrm.service.LanguageLocalService languageLocalService;
	@BeanReference(type = LanguagePersistence.class)
	protected LanguagePersistence languagePersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.LicenseLocalService.class)
	protected com.rknowsys.eapp.hrm.service.LicenseLocalService licenseLocalService;
	@BeanReference(type = LicensePersistence.class)
	protected LicensePersistence licensePersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.LocationLocalService.class)
	protected com.rknowsys.eapp.hrm.service.LocationLocalService locationLocalService;
	@BeanReference(type = LocationPersistence.class)
	protected LocationPersistence locationPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.MembershipLocalService.class)
	protected com.rknowsys.eapp.hrm.service.MembershipLocalService membershipLocalService;
	@BeanReference(type = MembershipPersistence.class)
	protected MembershipPersistence membershipPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.NationalityLocalService.class)
	protected com.rknowsys.eapp.hrm.service.NationalityLocalService nationalityLocalService;
	@BeanReference(type = NationalityPersistence.class)
	protected NationalityPersistence nationalityPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.NewsLocalService.class)
	protected com.rknowsys.eapp.hrm.service.NewsLocalService newsLocalService;
	@BeanReference(type = NewsPersistence.class)
	protected NewsPersistence newsPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.OrganizationLocalService.class)
	protected com.rknowsys.eapp.hrm.service.OrganizationLocalService organizationLocalService;
	@BeanReference(type = OrganizationPersistence.class)
	protected OrganizationPersistence organizationPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.PayGradeLocalService.class)
	protected com.rknowsys.eapp.hrm.service.PayGradeLocalService payGradeLocalService;
	@BeanReference(type = PayGradePersistence.class)
	protected PayGradePersistence payGradePersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.PayGradeCurrencyLocalService.class)
	protected com.rknowsys.eapp.hrm.service.PayGradeCurrencyLocalService payGradeCurrencyLocalService;
	@BeanReference(type = PayGradeCurrencyPersistence.class)
	protected PayGradeCurrencyPersistence payGradeCurrencyPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.SalaryComponentLocalService.class)
	protected com.rknowsys.eapp.hrm.service.SalaryComponentLocalService salaryComponentLocalService;
	@BeanReference(type = SalaryComponentPersistence.class)
	protected SalaryComponentPersistence salaryComponentPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.SkillLocalService.class)
	protected com.rknowsys.eapp.hrm.service.SkillLocalService skillLocalService;
	@BeanReference(type = SkillPersistence.class)
	protected SkillPersistence skillPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.SubUnitLocalService.class)
	protected com.rknowsys.eapp.hrm.service.SubUnitLocalService subUnitLocalService;
	@BeanReference(type = SubUnitPersistence.class)
	protected SubUnitPersistence subUnitPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.SupervisorLocalService.class)
	protected com.rknowsys.eapp.hrm.service.SupervisorLocalService supervisorLocalService;
	@BeanReference(type = SupervisorPersistence.class)
	protected SupervisorPersistence supervisorPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.WorkExpCompanyLocalService.class)
	protected com.rknowsys.eapp.hrm.service.WorkExpCompanyLocalService workExpCompanyLocalService;
	@BeanReference(type = WorkExpCompanyPersistence.class)
	protected WorkExpCompanyPersistence workExpCompanyPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.WorkshiftLocalService.class)
	protected com.rknowsys.eapp.hrm.service.WorkshiftLocalService workshiftLocalService;
	@BeanReference(type = WorkshiftPersistence.class)
	protected WorkshiftPersistence workshiftPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private EmploymentStatusLocalServiceClpInvoker _clpInvoker = new EmploymentStatusLocalServiceClpInvoker();
}