/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import com.rknowsys.eapp.hrm.model.Locations;
import com.rknowsys.eapp.hrm.service.LocationsLocalService;
import com.rknowsys.eapp.hrm.service.persistence.AttachmentPersistence;
import com.rknowsys.eapp.hrm.service.persistence.ContactDetailsPersistence;
import com.rknowsys.eapp.hrm.service.persistence.DependentPersistence;
import com.rknowsys.eapp.hrm.service.persistence.DocCategoryPersistence;
import com.rknowsys.eapp.hrm.service.persistence.DocumentPersistence;
import com.rknowsys.eapp.hrm.service.persistence.EducationPersistence;
import com.rknowsys.eapp.hrm.service.persistence.EmergencyContactPersistence;
import com.rknowsys.eapp.hrm.service.persistence.EmployeePersistence;
import com.rknowsys.eapp.hrm.service.persistence.EmploymentStatusPersistence;
import com.rknowsys.eapp.hrm.service.persistence.ImmigrationPersistence;
import com.rknowsys.eapp.hrm.service.persistence.InterviewPersistence;
import com.rknowsys.eapp.hrm.service.persistence.JobCategoryPersistence;
import com.rknowsys.eapp.hrm.service.persistence.JobTitlesPersistence;
import com.rknowsys.eapp.hrm.service.persistence.LanguagePersistence;
import com.rknowsys.eapp.hrm.service.persistence.LicensePersistence;
import com.rknowsys.eapp.hrm.service.persistence.LocationsPersistence;
import com.rknowsys.eapp.hrm.service.persistence.MembershipPersistence;
import com.rknowsys.eapp.hrm.service.persistence.NationalityPersistence;
import com.rknowsys.eapp.hrm.service.persistence.NewsPersistence;
import com.rknowsys.eapp.hrm.service.persistence.PayGradeCurrencyPersistence;
import com.rknowsys.eapp.hrm.service.persistence.PayGradePersistence;
import com.rknowsys.eapp.hrm.service.persistence.QualificationPersistence;
import com.rknowsys.eapp.hrm.service.persistence.SalaryComponentPersistence;
import com.rknowsys.eapp.hrm.service.persistence.SkillPersistence;
import com.rknowsys.eapp.hrm.service.persistence.WorkShiftUserPersistence;
import com.rknowsys.eapp.hrm.service.persistence.WorkshiftPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the locations local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.rknowsys.eapp.hrm.service.impl.LocationsLocalServiceImpl}.
 * </p>
 *
 * @author rknowsys
 * @see com.rknowsys.eapp.hrm.service.impl.LocationsLocalServiceImpl
 * @see com.rknowsys.eapp.hrm.service.LocationsLocalServiceUtil
 * @generated
 */
public abstract class LocationsLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements LocationsLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.rknowsys.eapp.hrm.service.LocationsLocalServiceUtil} to access the locations local service.
	 */

	/**
	 * Adds the locations to the database. Also notifies the appropriate model listeners.
	 *
	 * @param locations the locations
	 * @return the locations that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Locations addLocations(Locations locations)
		throws SystemException {
		locations.setNew(true);

		return locationsPersistence.update(locations);
	}

	/**
	 * Creates a new locations with the primary key. Does not add the locations to the database.
	 *
	 * @param id the primary key for the new locations
	 * @return the new locations
	 */
	@Override
	public Locations createLocations(long id) {
		return locationsPersistence.create(id);
	}

	/**
	 * Deletes the locations with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the locations
	 * @return the locations that was removed
	 * @throws PortalException if a locations with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Locations deleteLocations(long id)
		throws PortalException, SystemException {
		return locationsPersistence.remove(id);
	}

	/**
	 * Deletes the locations from the database. Also notifies the appropriate model listeners.
	 *
	 * @param locations the locations
	 * @return the locations that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Locations deleteLocations(Locations locations)
		throws SystemException {
		return locationsPersistence.remove(locations);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Locations.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return locationsPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rknowsys.eapp.hrm.model.impl.LocationsModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return locationsPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rknowsys.eapp.hrm.model.impl.LocationsModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return locationsPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return locationsPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return locationsPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public Locations fetchLocations(long id) throws SystemException {
		return locationsPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the locations with the primary key.
	 *
	 * @param id the primary key of the locations
	 * @return the locations
	 * @throws PortalException if a locations with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public Locations getLocations(long id)
		throws PortalException, SystemException {
		return locationsPersistence.findByPrimaryKey(id);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return locationsPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the locationses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rknowsys.eapp.hrm.model.impl.LocationsModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of locationses
	 * @param end the upper bound of the range of locationses (not inclusive)
	 * @return the range of locationses
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<Locations> getLocationses(int start, int end)
		throws SystemException {
		return locationsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of locationses.
	 *
	 * @return the number of locationses
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getLocationsesCount() throws SystemException {
		return locationsPersistence.countAll();
	}

	/**
	 * Updates the locations in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param locations the locations
	 * @return the locations that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Locations updateLocations(Locations locations)
		throws SystemException {
		return locationsPersistence.update(locations);
	}

	/**
	 * Returns the attachment local service.
	 *
	 * @return the attachment local service
	 */
	public com.rknowsys.eapp.hrm.service.AttachmentLocalService getAttachmentLocalService() {
		return attachmentLocalService;
	}

	/**
	 * Sets the attachment local service.
	 *
	 * @param attachmentLocalService the attachment local service
	 */
	public void setAttachmentLocalService(
		com.rknowsys.eapp.hrm.service.AttachmentLocalService attachmentLocalService) {
		this.attachmentLocalService = attachmentLocalService;
	}

	/**
	 * Returns the attachment persistence.
	 *
	 * @return the attachment persistence
	 */
	public AttachmentPersistence getAttachmentPersistence() {
		return attachmentPersistence;
	}

	/**
	 * Sets the attachment persistence.
	 *
	 * @param attachmentPersistence the attachment persistence
	 */
	public void setAttachmentPersistence(
		AttachmentPersistence attachmentPersistence) {
		this.attachmentPersistence = attachmentPersistence;
	}

	/**
	 * Returns the contact details local service.
	 *
	 * @return the contact details local service
	 */
	public com.rknowsys.eapp.hrm.service.ContactDetailsLocalService getContactDetailsLocalService() {
		return contactDetailsLocalService;
	}

	/**
	 * Sets the contact details local service.
	 *
	 * @param contactDetailsLocalService the contact details local service
	 */
	public void setContactDetailsLocalService(
		com.rknowsys.eapp.hrm.service.ContactDetailsLocalService contactDetailsLocalService) {
		this.contactDetailsLocalService = contactDetailsLocalService;
	}

	/**
	 * Returns the contact details persistence.
	 *
	 * @return the contact details persistence
	 */
	public ContactDetailsPersistence getContactDetailsPersistence() {
		return contactDetailsPersistence;
	}

	/**
	 * Sets the contact details persistence.
	 *
	 * @param contactDetailsPersistence the contact details persistence
	 */
	public void setContactDetailsPersistence(
		ContactDetailsPersistence contactDetailsPersistence) {
		this.contactDetailsPersistence = contactDetailsPersistence;
	}

	/**
	 * Returns the dependent local service.
	 *
	 * @return the dependent local service
	 */
	public com.rknowsys.eapp.hrm.service.DependentLocalService getDependentLocalService() {
		return dependentLocalService;
	}

	/**
	 * Sets the dependent local service.
	 *
	 * @param dependentLocalService the dependent local service
	 */
	public void setDependentLocalService(
		com.rknowsys.eapp.hrm.service.DependentLocalService dependentLocalService) {
		this.dependentLocalService = dependentLocalService;
	}

	/**
	 * Returns the dependent persistence.
	 *
	 * @return the dependent persistence
	 */
	public DependentPersistence getDependentPersistence() {
		return dependentPersistence;
	}

	/**
	 * Sets the dependent persistence.
	 *
	 * @param dependentPersistence the dependent persistence
	 */
	public void setDependentPersistence(
		DependentPersistence dependentPersistence) {
		this.dependentPersistence = dependentPersistence;
	}

	/**
	 * Returns the doc category local service.
	 *
	 * @return the doc category local service
	 */
	public com.rknowsys.eapp.hrm.service.DocCategoryLocalService getDocCategoryLocalService() {
		return docCategoryLocalService;
	}

	/**
	 * Sets the doc category local service.
	 *
	 * @param docCategoryLocalService the doc category local service
	 */
	public void setDocCategoryLocalService(
		com.rknowsys.eapp.hrm.service.DocCategoryLocalService docCategoryLocalService) {
		this.docCategoryLocalService = docCategoryLocalService;
	}

	/**
	 * Returns the doc category persistence.
	 *
	 * @return the doc category persistence
	 */
	public DocCategoryPersistence getDocCategoryPersistence() {
		return docCategoryPersistence;
	}

	/**
	 * Sets the doc category persistence.
	 *
	 * @param docCategoryPersistence the doc category persistence
	 */
	public void setDocCategoryPersistence(
		DocCategoryPersistence docCategoryPersistence) {
		this.docCategoryPersistence = docCategoryPersistence;
	}

	/**
	 * Returns the document local service.
	 *
	 * @return the document local service
	 */
	public com.rknowsys.eapp.hrm.service.DocumentLocalService getDocumentLocalService() {
		return documentLocalService;
	}

	/**
	 * Sets the document local service.
	 *
	 * @param documentLocalService the document local service
	 */
	public void setDocumentLocalService(
		com.rknowsys.eapp.hrm.service.DocumentLocalService documentLocalService) {
		this.documentLocalService = documentLocalService;
	}

	/**
	 * Returns the document persistence.
	 *
	 * @return the document persistence
	 */
	public DocumentPersistence getDocumentPersistence() {
		return documentPersistence;
	}

	/**
	 * Sets the document persistence.
	 *
	 * @param documentPersistence the document persistence
	 */
	public void setDocumentPersistence(DocumentPersistence documentPersistence) {
		this.documentPersistence = documentPersistence;
	}

	/**
	 * Returns the education local service.
	 *
	 * @return the education local service
	 */
	public com.rknowsys.eapp.hrm.service.EducationLocalService getEducationLocalService() {
		return educationLocalService;
	}

	/**
	 * Sets the education local service.
	 *
	 * @param educationLocalService the education local service
	 */
	public void setEducationLocalService(
		com.rknowsys.eapp.hrm.service.EducationLocalService educationLocalService) {
		this.educationLocalService = educationLocalService;
	}

	/**
	 * Returns the education persistence.
	 *
	 * @return the education persistence
	 */
	public EducationPersistence getEducationPersistence() {
		return educationPersistence;
	}

	/**
	 * Sets the education persistence.
	 *
	 * @param educationPersistence the education persistence
	 */
	public void setEducationPersistence(
		EducationPersistence educationPersistence) {
		this.educationPersistence = educationPersistence;
	}

	/**
	 * Returns the emergency contact local service.
	 *
	 * @return the emergency contact local service
	 */
	public com.rknowsys.eapp.hrm.service.EmergencyContactLocalService getEmergencyContactLocalService() {
		return emergencyContactLocalService;
	}

	/**
	 * Sets the emergency contact local service.
	 *
	 * @param emergencyContactLocalService the emergency contact local service
	 */
	public void setEmergencyContactLocalService(
		com.rknowsys.eapp.hrm.service.EmergencyContactLocalService emergencyContactLocalService) {
		this.emergencyContactLocalService = emergencyContactLocalService;
	}

	/**
	 * Returns the emergency contact persistence.
	 *
	 * @return the emergency contact persistence
	 */
	public EmergencyContactPersistence getEmergencyContactPersistence() {
		return emergencyContactPersistence;
	}

	/**
	 * Sets the emergency contact persistence.
	 *
	 * @param emergencyContactPersistence the emergency contact persistence
	 */
	public void setEmergencyContactPersistence(
		EmergencyContactPersistence emergencyContactPersistence) {
		this.emergencyContactPersistence = emergencyContactPersistence;
	}

	/**
	 * Returns the Employee local service.
	 *
	 * @return the Employee local service
	 */
	public com.rknowsys.eapp.hrm.service.EmployeeLocalService getEmployeeLocalService() {
		return employeeLocalService;
	}

	/**
	 * Sets the Employee local service.
	 *
	 * @param employeeLocalService the Employee local service
	 */
	public void setEmployeeLocalService(
		com.rknowsys.eapp.hrm.service.EmployeeLocalService employeeLocalService) {
		this.employeeLocalService = employeeLocalService;
	}

	/**
	 * Returns the Employee persistence.
	 *
	 * @return the Employee persistence
	 */
	public EmployeePersistence getEmployeePersistence() {
		return employeePersistence;
	}

	/**
	 * Sets the Employee persistence.
	 *
	 * @param employeePersistence the Employee persistence
	 */
	public void setEmployeePersistence(EmployeePersistence employeePersistence) {
		this.employeePersistence = employeePersistence;
	}

	/**
	 * Returns the employment status local service.
	 *
	 * @return the employment status local service
	 */
	public com.rknowsys.eapp.hrm.service.EmploymentStatusLocalService getEmploymentStatusLocalService() {
		return employmentStatusLocalService;
	}

	/**
	 * Sets the employment status local service.
	 *
	 * @param employmentStatusLocalService the employment status local service
	 */
	public void setEmploymentStatusLocalService(
		com.rknowsys.eapp.hrm.service.EmploymentStatusLocalService employmentStatusLocalService) {
		this.employmentStatusLocalService = employmentStatusLocalService;
	}

	/**
	 * Returns the employment status persistence.
	 *
	 * @return the employment status persistence
	 */
	public EmploymentStatusPersistence getEmploymentStatusPersistence() {
		return employmentStatusPersistence;
	}

	/**
	 * Sets the employment status persistence.
	 *
	 * @param employmentStatusPersistence the employment status persistence
	 */
	public void setEmploymentStatusPersistence(
		EmploymentStatusPersistence employmentStatusPersistence) {
		this.employmentStatusPersistence = employmentStatusPersistence;
	}

	/**
	 * Returns the immigration local service.
	 *
	 * @return the immigration local service
	 */
	public com.rknowsys.eapp.hrm.service.ImmigrationLocalService getImmigrationLocalService() {
		return immigrationLocalService;
	}

	/**
	 * Sets the immigration local service.
	 *
	 * @param immigrationLocalService the immigration local service
	 */
	public void setImmigrationLocalService(
		com.rknowsys.eapp.hrm.service.ImmigrationLocalService immigrationLocalService) {
		this.immigrationLocalService = immigrationLocalService;
	}

	/**
	 * Returns the immigration persistence.
	 *
	 * @return the immigration persistence
	 */
	public ImmigrationPersistence getImmigrationPersistence() {
		return immigrationPersistence;
	}

	/**
	 * Sets the immigration persistence.
	 *
	 * @param immigrationPersistence the immigration persistence
	 */
	public void setImmigrationPersistence(
		ImmigrationPersistence immigrationPersistence) {
		this.immigrationPersistence = immigrationPersistence;
	}

	/**
	 * Returns the interview local service.
	 *
	 * @return the interview local service
	 */
	public com.rknowsys.eapp.hrm.service.InterviewLocalService getInterviewLocalService() {
		return interviewLocalService;
	}

	/**
	 * Sets the interview local service.
	 *
	 * @param interviewLocalService the interview local service
	 */
	public void setInterviewLocalService(
		com.rknowsys.eapp.hrm.service.InterviewLocalService interviewLocalService) {
		this.interviewLocalService = interviewLocalService;
	}

	/**
	 * Returns the interview persistence.
	 *
	 * @return the interview persistence
	 */
	public InterviewPersistence getInterviewPersistence() {
		return interviewPersistence;
	}

	/**
	 * Sets the interview persistence.
	 *
	 * @param interviewPersistence the interview persistence
	 */
	public void setInterviewPersistence(
		InterviewPersistence interviewPersistence) {
		this.interviewPersistence = interviewPersistence;
	}

	/**
	 * Returns the job category local service.
	 *
	 * @return the job category local service
	 */
	public com.rknowsys.eapp.hrm.service.JobCategoryLocalService getJobCategoryLocalService() {
		return jobCategoryLocalService;
	}

	/**
	 * Sets the job category local service.
	 *
	 * @param jobCategoryLocalService the job category local service
	 */
	public void setJobCategoryLocalService(
		com.rknowsys.eapp.hrm.service.JobCategoryLocalService jobCategoryLocalService) {
		this.jobCategoryLocalService = jobCategoryLocalService;
	}

	/**
	 * Returns the job category persistence.
	 *
	 * @return the job category persistence
	 */
	public JobCategoryPersistence getJobCategoryPersistence() {
		return jobCategoryPersistence;
	}

	/**
	 * Sets the job category persistence.
	 *
	 * @param jobCategoryPersistence the job category persistence
	 */
	public void setJobCategoryPersistence(
		JobCategoryPersistence jobCategoryPersistence) {
		this.jobCategoryPersistence = jobCategoryPersistence;
	}

	/**
	 * Returns the job titles local service.
	 *
	 * @return the job titles local service
	 */
	public com.rknowsys.eapp.hrm.service.JobTitlesLocalService getJobTitlesLocalService() {
		return jobTitlesLocalService;
	}

	/**
	 * Sets the job titles local service.
	 *
	 * @param jobTitlesLocalService the job titles local service
	 */
	public void setJobTitlesLocalService(
		com.rknowsys.eapp.hrm.service.JobTitlesLocalService jobTitlesLocalService) {
		this.jobTitlesLocalService = jobTitlesLocalService;
	}

	/**
	 * Returns the job titles persistence.
	 *
	 * @return the job titles persistence
	 */
	public JobTitlesPersistence getJobTitlesPersistence() {
		return jobTitlesPersistence;
	}

	/**
	 * Sets the job titles persistence.
	 *
	 * @param jobTitlesPersistence the job titles persistence
	 */
	public void setJobTitlesPersistence(
		JobTitlesPersistence jobTitlesPersistence) {
		this.jobTitlesPersistence = jobTitlesPersistence;
	}

	/**
	 * Returns the language local service.
	 *
	 * @return the language local service
	 */
	public com.rknowsys.eapp.hrm.service.LanguageLocalService getLanguageLocalService() {
		return languageLocalService;
	}

	/**
	 * Sets the language local service.
	 *
	 * @param languageLocalService the language local service
	 */
	public void setLanguageLocalService(
		com.rknowsys.eapp.hrm.service.LanguageLocalService languageLocalService) {
		this.languageLocalService = languageLocalService;
	}

	/**
	 * Returns the language persistence.
	 *
	 * @return the language persistence
	 */
	public LanguagePersistence getLanguagePersistence() {
		return languagePersistence;
	}

	/**
	 * Sets the language persistence.
	 *
	 * @param languagePersistence the language persistence
	 */
	public void setLanguagePersistence(LanguagePersistence languagePersistence) {
		this.languagePersistence = languagePersistence;
	}

	/**
	 * Returns the license local service.
	 *
	 * @return the license local service
	 */
	public com.rknowsys.eapp.hrm.service.LicenseLocalService getLicenseLocalService() {
		return licenseLocalService;
	}

	/**
	 * Sets the license local service.
	 *
	 * @param licenseLocalService the license local service
	 */
	public void setLicenseLocalService(
		com.rknowsys.eapp.hrm.service.LicenseLocalService licenseLocalService) {
		this.licenseLocalService = licenseLocalService;
	}

	/**
	 * Returns the license persistence.
	 *
	 * @return the license persistence
	 */
	public LicensePersistence getLicensePersistence() {
		return licensePersistence;
	}

	/**
	 * Sets the license persistence.
	 *
	 * @param licensePersistence the license persistence
	 */
	public void setLicensePersistence(LicensePersistence licensePersistence) {
		this.licensePersistence = licensePersistence;
	}

	/**
	 * Returns the locations local service.
	 *
	 * @return the locations local service
	 */
	public com.rknowsys.eapp.hrm.service.LocationsLocalService getLocationsLocalService() {
		return locationsLocalService;
	}

	/**
	 * Sets the locations local service.
	 *
	 * @param locationsLocalService the locations local service
	 */
	public void setLocationsLocalService(
		com.rknowsys.eapp.hrm.service.LocationsLocalService locationsLocalService) {
		this.locationsLocalService = locationsLocalService;
	}

	/**
	 * Returns the locations persistence.
	 *
	 * @return the locations persistence
	 */
	public LocationsPersistence getLocationsPersistence() {
		return locationsPersistence;
	}

	/**
	 * Sets the locations persistence.
	 *
	 * @param locationsPersistence the locations persistence
	 */
	public void setLocationsPersistence(
		LocationsPersistence locationsPersistence) {
		this.locationsPersistence = locationsPersistence;
	}

	/**
	 * Returns the membership local service.
	 *
	 * @return the membership local service
	 */
	public com.rknowsys.eapp.hrm.service.MembershipLocalService getMembershipLocalService() {
		return membershipLocalService;
	}

	/**
	 * Sets the membership local service.
	 *
	 * @param membershipLocalService the membership local service
	 */
	public void setMembershipLocalService(
		com.rknowsys.eapp.hrm.service.MembershipLocalService membershipLocalService) {
		this.membershipLocalService = membershipLocalService;
	}

	/**
	 * Returns the membership persistence.
	 *
	 * @return the membership persistence
	 */
	public MembershipPersistence getMembershipPersistence() {
		return membershipPersistence;
	}

	/**
	 * Sets the membership persistence.
	 *
	 * @param membershipPersistence the membership persistence
	 */
	public void setMembershipPersistence(
		MembershipPersistence membershipPersistence) {
		this.membershipPersistence = membershipPersistence;
	}

	/**
	 * Returns the nationality local service.
	 *
	 * @return the nationality local service
	 */
	public com.rknowsys.eapp.hrm.service.NationalityLocalService getNationalityLocalService() {
		return nationalityLocalService;
	}

	/**
	 * Sets the nationality local service.
	 *
	 * @param nationalityLocalService the nationality local service
	 */
	public void setNationalityLocalService(
		com.rknowsys.eapp.hrm.service.NationalityLocalService nationalityLocalService) {
		this.nationalityLocalService = nationalityLocalService;
	}

	/**
	 * Returns the nationality persistence.
	 *
	 * @return the nationality persistence
	 */
	public NationalityPersistence getNationalityPersistence() {
		return nationalityPersistence;
	}

	/**
	 * Sets the nationality persistence.
	 *
	 * @param nationalityPersistence the nationality persistence
	 */
	public void setNationalityPersistence(
		NationalityPersistence nationalityPersistence) {
		this.nationalityPersistence = nationalityPersistence;
	}

	/**
	 * Returns the news local service.
	 *
	 * @return the news local service
	 */
	public com.rknowsys.eapp.hrm.service.NewsLocalService getNewsLocalService() {
		return newsLocalService;
	}

	/**
	 * Sets the news local service.
	 *
	 * @param newsLocalService the news local service
	 */
	public void setNewsLocalService(
		com.rknowsys.eapp.hrm.service.NewsLocalService newsLocalService) {
		this.newsLocalService = newsLocalService;
	}

	/**
	 * Returns the news persistence.
	 *
	 * @return the news persistence
	 */
	public NewsPersistence getNewsPersistence() {
		return newsPersistence;
	}

	/**
	 * Sets the news persistence.
	 *
	 * @param newsPersistence the news persistence
	 */
	public void setNewsPersistence(NewsPersistence newsPersistence) {
		this.newsPersistence = newsPersistence;
	}

	/**
	 * Returns the pay grade local service.
	 *
	 * @return the pay grade local service
	 */
	public com.rknowsys.eapp.hrm.service.PayGradeLocalService getPayGradeLocalService() {
		return payGradeLocalService;
	}

	/**
	 * Sets the pay grade local service.
	 *
	 * @param payGradeLocalService the pay grade local service
	 */
	public void setPayGradeLocalService(
		com.rknowsys.eapp.hrm.service.PayGradeLocalService payGradeLocalService) {
		this.payGradeLocalService = payGradeLocalService;
	}

	/**
	 * Returns the pay grade persistence.
	 *
	 * @return the pay grade persistence
	 */
	public PayGradePersistence getPayGradePersistence() {
		return payGradePersistence;
	}

	/**
	 * Sets the pay grade persistence.
	 *
	 * @param payGradePersistence the pay grade persistence
	 */
	public void setPayGradePersistence(PayGradePersistence payGradePersistence) {
		this.payGradePersistence = payGradePersistence;
	}

	/**
	 * Returns the pay grade currency local service.
	 *
	 * @return the pay grade currency local service
	 */
	public com.rknowsys.eapp.hrm.service.PayGradeCurrencyLocalService getPayGradeCurrencyLocalService() {
		return payGradeCurrencyLocalService;
	}

	/**
	 * Sets the pay grade currency local service.
	 *
	 * @param payGradeCurrencyLocalService the pay grade currency local service
	 */
	public void setPayGradeCurrencyLocalService(
		com.rknowsys.eapp.hrm.service.PayGradeCurrencyLocalService payGradeCurrencyLocalService) {
		this.payGradeCurrencyLocalService = payGradeCurrencyLocalService;
	}

	/**
	 * Returns the pay grade currency persistence.
	 *
	 * @return the pay grade currency persistence
	 */
	public PayGradeCurrencyPersistence getPayGradeCurrencyPersistence() {
		return payGradeCurrencyPersistence;
	}

	/**
	 * Sets the pay grade currency persistence.
	 *
	 * @param payGradeCurrencyPersistence the pay grade currency persistence
	 */
	public void setPayGradeCurrencyPersistence(
		PayGradeCurrencyPersistence payGradeCurrencyPersistence) {
		this.payGradeCurrencyPersistence = payGradeCurrencyPersistence;
	}

	/**
	 * Returns the qualification local service.
	 *
	 * @return the qualification local service
	 */
	public com.rknowsys.eapp.hrm.service.QualificationLocalService getQualificationLocalService() {
		return qualificationLocalService;
	}

	/**
	 * Sets the qualification local service.
	 *
	 * @param qualificationLocalService the qualification local service
	 */
	public void setQualificationLocalService(
		com.rknowsys.eapp.hrm.service.QualificationLocalService qualificationLocalService) {
		this.qualificationLocalService = qualificationLocalService;
	}

	/**
	 * Returns the qualification persistence.
	 *
	 * @return the qualification persistence
	 */
	public QualificationPersistence getQualificationPersistence() {
		return qualificationPersistence;
	}

	/**
	 * Sets the qualification persistence.
	 *
	 * @param qualificationPersistence the qualification persistence
	 */
	public void setQualificationPersistence(
		QualificationPersistence qualificationPersistence) {
		this.qualificationPersistence = qualificationPersistence;
	}

	/**
	 * Returns the salary component local service.
	 *
	 * @return the salary component local service
	 */
	public com.rknowsys.eapp.hrm.service.SalaryComponentLocalService getSalaryComponentLocalService() {
		return salaryComponentLocalService;
	}

	/**
	 * Sets the salary component local service.
	 *
	 * @param salaryComponentLocalService the salary component local service
	 */
	public void setSalaryComponentLocalService(
		com.rknowsys.eapp.hrm.service.SalaryComponentLocalService salaryComponentLocalService) {
		this.salaryComponentLocalService = salaryComponentLocalService;
	}

	/**
	 * Returns the salary component persistence.
	 *
	 * @return the salary component persistence
	 */
	public SalaryComponentPersistence getSalaryComponentPersistence() {
		return salaryComponentPersistence;
	}

	/**
	 * Sets the salary component persistence.
	 *
	 * @param salaryComponentPersistence the salary component persistence
	 */
	public void setSalaryComponentPersistence(
		SalaryComponentPersistence salaryComponentPersistence) {
		this.salaryComponentPersistence = salaryComponentPersistence;
	}

	/**
	 * Returns the skill local service.
	 *
	 * @return the skill local service
	 */
	public com.rknowsys.eapp.hrm.service.SkillLocalService getSkillLocalService() {
		return skillLocalService;
	}

	/**
	 * Sets the skill local service.
	 *
	 * @param skillLocalService the skill local service
	 */
	public void setSkillLocalService(
		com.rknowsys.eapp.hrm.service.SkillLocalService skillLocalService) {
		this.skillLocalService = skillLocalService;
	}

	/**
	 * Returns the skill persistence.
	 *
	 * @return the skill persistence
	 */
	public SkillPersistence getSkillPersistence() {
		return skillPersistence;
	}

	/**
	 * Sets the skill persistence.
	 *
	 * @param skillPersistence the skill persistence
	 */
	public void setSkillPersistence(SkillPersistence skillPersistence) {
		this.skillPersistence = skillPersistence;
	}

	/**
	 * Returns the workshift local service.
	 *
	 * @return the workshift local service
	 */
	public com.rknowsys.eapp.hrm.service.WorkshiftLocalService getWorkshiftLocalService() {
		return workshiftLocalService;
	}

	/**
	 * Sets the workshift local service.
	 *
	 * @param workshiftLocalService the workshift local service
	 */
	public void setWorkshiftLocalService(
		com.rknowsys.eapp.hrm.service.WorkshiftLocalService workshiftLocalService) {
		this.workshiftLocalService = workshiftLocalService;
	}

	/**
	 * Returns the workshift persistence.
	 *
	 * @return the workshift persistence
	 */
	public WorkshiftPersistence getWorkshiftPersistence() {
		return workshiftPersistence;
	}

	/**
	 * Sets the workshift persistence.
	 *
	 * @param workshiftPersistence the workshift persistence
	 */
	public void setWorkshiftPersistence(
		WorkshiftPersistence workshiftPersistence) {
		this.workshiftPersistence = workshiftPersistence;
	}

	/**
	 * Returns the work shift user local service.
	 *
	 * @return the work shift user local service
	 */
	public com.rknowsys.eapp.hrm.service.WorkShiftUserLocalService getWorkShiftUserLocalService() {
		return workShiftUserLocalService;
	}

	/**
	 * Sets the work shift user local service.
	 *
	 * @param workShiftUserLocalService the work shift user local service
	 */
	public void setWorkShiftUserLocalService(
		com.rknowsys.eapp.hrm.service.WorkShiftUserLocalService workShiftUserLocalService) {
		this.workShiftUserLocalService = workShiftUserLocalService;
	}

	/**
	 * Returns the work shift user persistence.
	 *
	 * @return the work shift user persistence
	 */
	public WorkShiftUserPersistence getWorkShiftUserPersistence() {
		return workShiftUserPersistence;
	}

	/**
	 * Sets the work shift user persistence.
	 *
	 * @param workShiftUserPersistence the work shift user persistence
	 */
	public void setWorkShiftUserPersistence(
		WorkShiftUserPersistence workShiftUserPersistence) {
		this.workShiftUserPersistence = workShiftUserPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.rknowsys.eapp.hrm.model.Locations",
			locationsLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.rknowsys.eapp.hrm.model.Locations");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Locations.class;
	}

	protected String getModelClassName() {
		return Locations.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = locationsPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.rknowsys.eapp.hrm.service.AttachmentLocalService.class)
	protected com.rknowsys.eapp.hrm.service.AttachmentLocalService attachmentLocalService;
	@BeanReference(type = AttachmentPersistence.class)
	protected AttachmentPersistence attachmentPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.ContactDetailsLocalService.class)
	protected com.rknowsys.eapp.hrm.service.ContactDetailsLocalService contactDetailsLocalService;
	@BeanReference(type = ContactDetailsPersistence.class)
	protected ContactDetailsPersistence contactDetailsPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.DependentLocalService.class)
	protected com.rknowsys.eapp.hrm.service.DependentLocalService dependentLocalService;
	@BeanReference(type = DependentPersistence.class)
	protected DependentPersistence dependentPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.DocCategoryLocalService.class)
	protected com.rknowsys.eapp.hrm.service.DocCategoryLocalService docCategoryLocalService;
	@BeanReference(type = DocCategoryPersistence.class)
	protected DocCategoryPersistence docCategoryPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.DocumentLocalService.class)
	protected com.rknowsys.eapp.hrm.service.DocumentLocalService documentLocalService;
	@BeanReference(type = DocumentPersistence.class)
	protected DocumentPersistence documentPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.EducationLocalService.class)
	protected com.rknowsys.eapp.hrm.service.EducationLocalService educationLocalService;
	@BeanReference(type = EducationPersistence.class)
	protected EducationPersistence educationPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.EmergencyContactLocalService.class)
	protected com.rknowsys.eapp.hrm.service.EmergencyContactLocalService emergencyContactLocalService;
	@BeanReference(type = EmergencyContactPersistence.class)
	protected EmergencyContactPersistence emergencyContactPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.EmployeeLocalService.class)
	protected com.rknowsys.eapp.hrm.service.EmployeeLocalService employeeLocalService;
	@BeanReference(type = EmployeePersistence.class)
	protected EmployeePersistence employeePersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.EmploymentStatusLocalService.class)
	protected com.rknowsys.eapp.hrm.service.EmploymentStatusLocalService employmentStatusLocalService;
	@BeanReference(type = EmploymentStatusPersistence.class)
	protected EmploymentStatusPersistence employmentStatusPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.ImmigrationLocalService.class)
	protected com.rknowsys.eapp.hrm.service.ImmigrationLocalService immigrationLocalService;
	@BeanReference(type = ImmigrationPersistence.class)
	protected ImmigrationPersistence immigrationPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.InterviewLocalService.class)
	protected com.rknowsys.eapp.hrm.service.InterviewLocalService interviewLocalService;
	@BeanReference(type = InterviewPersistence.class)
	protected InterviewPersistence interviewPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.JobCategoryLocalService.class)
	protected com.rknowsys.eapp.hrm.service.JobCategoryLocalService jobCategoryLocalService;
	@BeanReference(type = JobCategoryPersistence.class)
	protected JobCategoryPersistence jobCategoryPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.JobTitlesLocalService.class)
	protected com.rknowsys.eapp.hrm.service.JobTitlesLocalService jobTitlesLocalService;
	@BeanReference(type = JobTitlesPersistence.class)
	protected JobTitlesPersistence jobTitlesPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.LanguageLocalService.class)
	protected com.rknowsys.eapp.hrm.service.LanguageLocalService languageLocalService;
	@BeanReference(type = LanguagePersistence.class)
	protected LanguagePersistence languagePersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.LicenseLocalService.class)
	protected com.rknowsys.eapp.hrm.service.LicenseLocalService licenseLocalService;
	@BeanReference(type = LicensePersistence.class)
	protected LicensePersistence licensePersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.LocationsLocalService.class)
	protected com.rknowsys.eapp.hrm.service.LocationsLocalService locationsLocalService;
	@BeanReference(type = LocationsPersistence.class)
	protected LocationsPersistence locationsPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.MembershipLocalService.class)
	protected com.rknowsys.eapp.hrm.service.MembershipLocalService membershipLocalService;
	@BeanReference(type = MembershipPersistence.class)
	protected MembershipPersistence membershipPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.NationalityLocalService.class)
	protected com.rknowsys.eapp.hrm.service.NationalityLocalService nationalityLocalService;
	@BeanReference(type = NationalityPersistence.class)
	protected NationalityPersistence nationalityPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.NewsLocalService.class)
	protected com.rknowsys.eapp.hrm.service.NewsLocalService newsLocalService;
	@BeanReference(type = NewsPersistence.class)
	protected NewsPersistence newsPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.PayGradeLocalService.class)
	protected com.rknowsys.eapp.hrm.service.PayGradeLocalService payGradeLocalService;
	@BeanReference(type = PayGradePersistence.class)
	protected PayGradePersistence payGradePersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.PayGradeCurrencyLocalService.class)
	protected com.rknowsys.eapp.hrm.service.PayGradeCurrencyLocalService payGradeCurrencyLocalService;
	@BeanReference(type = PayGradeCurrencyPersistence.class)
	protected PayGradeCurrencyPersistence payGradeCurrencyPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.QualificationLocalService.class)
	protected com.rknowsys.eapp.hrm.service.QualificationLocalService qualificationLocalService;
	@BeanReference(type = QualificationPersistence.class)
	protected QualificationPersistence qualificationPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.SalaryComponentLocalService.class)
	protected com.rknowsys.eapp.hrm.service.SalaryComponentLocalService salaryComponentLocalService;
	@BeanReference(type = SalaryComponentPersistence.class)
	protected SalaryComponentPersistence salaryComponentPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.SkillLocalService.class)
	protected com.rknowsys.eapp.hrm.service.SkillLocalService skillLocalService;
	@BeanReference(type = SkillPersistence.class)
	protected SkillPersistence skillPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.WorkshiftLocalService.class)
	protected com.rknowsys.eapp.hrm.service.WorkshiftLocalService workshiftLocalService;
	@BeanReference(type = WorkshiftPersistence.class)
	protected WorkshiftPersistence workshiftPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.WorkShiftUserLocalService.class)
	protected com.rknowsys.eapp.hrm.service.WorkShiftUserLocalService workShiftUserLocalService;
	@BeanReference(type = WorkShiftUserPersistence.class)
	protected WorkShiftUserPersistence workShiftUserPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private LocationsLocalServiceClpInvoker _clpInvoker = new LocationsLocalServiceClpInvoker();
}