/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rknowsys.eapp.hrm.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import com.rknowsys.eapp.hrm.model.SalaryComponent;
import com.rknowsys.eapp.hrm.service.SalaryComponentLocalService;
import com.rknowsys.eapp.hrm.service.persistence.DocCategoryPersistence;
import com.rknowsys.eapp.hrm.service.persistence.DocumentPersistence;
import com.rknowsys.eapp.hrm.service.persistence.EducationPersistence;
import com.rknowsys.eapp.hrm.service.persistence.EmploymentStatusPersistence;
import com.rknowsys.eapp.hrm.service.persistence.InterviewPersistence;
import com.rknowsys.eapp.hrm.service.persistence.JobCategoryPersistence;
import com.rknowsys.eapp.hrm.service.persistence.JobTitlesPersistence;
import com.rknowsys.eapp.hrm.service.persistence.LanguagePersistence;
import com.rknowsys.eapp.hrm.service.persistence.LicensePersistence;
import com.rknowsys.eapp.hrm.service.persistence.LocationsPersistence;
import com.rknowsys.eapp.hrm.service.persistence.MembershipPersistence;
import com.rknowsys.eapp.hrm.service.persistence.NationalityPersistence;
import com.rknowsys.eapp.hrm.service.persistence.NewsPersistence;
import com.rknowsys.eapp.hrm.service.persistence.PayGradeCurrencyPersistence;
import com.rknowsys.eapp.hrm.service.persistence.PayGradePersistence;
import com.rknowsys.eapp.hrm.service.persistence.SalaryComponentPersistence;
import com.rknowsys.eapp.hrm.service.persistence.SkillPersistence;
import com.rknowsys.eapp.hrm.service.persistence.WorkShiftPersistence;
import com.rknowsys.eapp.hrm.service.persistence.WorkShiftUserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the salary component local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.rknowsys.eapp.hrm.service.impl.SalaryComponentLocalServiceImpl}.
 * </p>
 *
 * @author rknowsys
 * @see com.rknowsys.eapp.hrm.service.impl.SalaryComponentLocalServiceImpl
 * @see com.rknowsys.eapp.hrm.service.SalaryComponentLocalServiceUtil
 * @generated
 */
public abstract class SalaryComponentLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements SalaryComponentLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.rknowsys.eapp.hrm.service.SalaryComponentLocalServiceUtil} to access the salary component local service.
	 */

	/**
	 * Adds the salary component to the database. Also notifies the appropriate model listeners.
	 *
	 * @param salaryComponent the salary component
	 * @return the salary component that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SalaryComponent addSalaryComponent(SalaryComponent salaryComponent)
		throws SystemException {
		salaryComponent.setNew(true);

		return salaryComponentPersistence.update(salaryComponent);
	}

	/**
	 * Creates a new salary component with the primary key. Does not add the salary component to the database.
	 *
	 * @param id the primary key for the new salary component
	 * @return the new salary component
	 */
	@Override
	public SalaryComponent createSalaryComponent(long id) {
		return salaryComponentPersistence.create(id);
	}

	/**
	 * Deletes the salary component with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the salary component
	 * @return the salary component that was removed
	 * @throws PortalException if a salary component with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SalaryComponent deleteSalaryComponent(long id)
		throws PortalException, SystemException {
		return salaryComponentPersistence.remove(id);
	}

	/**
	 * Deletes the salary component from the database. Also notifies the appropriate model listeners.
	 *
	 * @param salaryComponent the salary component
	 * @return the salary component that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SalaryComponent deleteSalaryComponent(
		SalaryComponent salaryComponent) throws SystemException {
		return salaryComponentPersistence.remove(salaryComponent);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(SalaryComponent.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return salaryComponentPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rknowsys.eapp.hrm.model.impl.SalaryComponentModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return salaryComponentPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rknowsys.eapp.hrm.model.impl.SalaryComponentModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return salaryComponentPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return salaryComponentPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return salaryComponentPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public SalaryComponent fetchSalaryComponent(long id)
		throws SystemException {
		return salaryComponentPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the salary component with the primary key.
	 *
	 * @param id the primary key of the salary component
	 * @return the salary component
	 * @throws PortalException if a salary component with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public SalaryComponent getSalaryComponent(long id)
		throws PortalException, SystemException {
		return salaryComponentPersistence.findByPrimaryKey(id);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return salaryComponentPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the salary components.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rknowsys.eapp.hrm.model.impl.SalaryComponentModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of salary components
	 * @param end the upper bound of the range of salary components (not inclusive)
	 * @return the range of salary components
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<SalaryComponent> getSalaryComponents(int start, int end)
		throws SystemException {
		return salaryComponentPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of salary components.
	 *
	 * @return the number of salary components
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getSalaryComponentsCount() throws SystemException {
		return salaryComponentPersistence.countAll();
	}

	/**
	 * Updates the salary component in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param salaryComponent the salary component
	 * @return the salary component that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SalaryComponent updateSalaryComponent(
		SalaryComponent salaryComponent) throws SystemException {
		return salaryComponentPersistence.update(salaryComponent);
	}

	/**
	 * Returns the doc category local service.
	 *
	 * @return the doc category local service
	 */
	public com.rknowsys.eapp.hrm.service.DocCategoryLocalService getDocCategoryLocalService() {
		return docCategoryLocalService;
	}

	/**
	 * Sets the doc category local service.
	 *
	 * @param docCategoryLocalService the doc category local service
	 */
	public void setDocCategoryLocalService(
		com.rknowsys.eapp.hrm.service.DocCategoryLocalService docCategoryLocalService) {
		this.docCategoryLocalService = docCategoryLocalService;
	}

	/**
	 * Returns the doc category persistence.
	 *
	 * @return the doc category persistence
	 */
	public DocCategoryPersistence getDocCategoryPersistence() {
		return docCategoryPersistence;
	}

	/**
	 * Sets the doc category persistence.
	 *
	 * @param docCategoryPersistence the doc category persistence
	 */
	public void setDocCategoryPersistence(
		DocCategoryPersistence docCategoryPersistence) {
		this.docCategoryPersistence = docCategoryPersistence;
	}

	/**
	 * Returns the document local service.
	 *
	 * @return the document local service
	 */
	public com.rknowsys.eapp.hrm.service.DocumentLocalService getDocumentLocalService() {
		return documentLocalService;
	}

	/**
	 * Sets the document local service.
	 *
	 * @param documentLocalService the document local service
	 */
	public void setDocumentLocalService(
		com.rknowsys.eapp.hrm.service.DocumentLocalService documentLocalService) {
		this.documentLocalService = documentLocalService;
	}

	/**
	 * Returns the document persistence.
	 *
	 * @return the document persistence
	 */
	public DocumentPersistence getDocumentPersistence() {
		return documentPersistence;
	}

	/**
	 * Sets the document persistence.
	 *
	 * @param documentPersistence the document persistence
	 */
	public void setDocumentPersistence(DocumentPersistence documentPersistence) {
		this.documentPersistence = documentPersistence;
	}

	/**
	 * Returns the education local service.
	 *
	 * @return the education local service
	 */
	public com.rknowsys.eapp.hrm.service.EducationLocalService getEducationLocalService() {
		return educationLocalService;
	}

	/**
	 * Sets the education local service.
	 *
	 * @param educationLocalService the education local service
	 */
	public void setEducationLocalService(
		com.rknowsys.eapp.hrm.service.EducationLocalService educationLocalService) {
		this.educationLocalService = educationLocalService;
	}

	/**
	 * Returns the education persistence.
	 *
	 * @return the education persistence
	 */
	public EducationPersistence getEducationPersistence() {
		return educationPersistence;
	}

	/**
	 * Sets the education persistence.
	 *
	 * @param educationPersistence the education persistence
	 */
	public void setEducationPersistence(
		EducationPersistence educationPersistence) {
		this.educationPersistence = educationPersistence;
	}

	/**
	 * Returns the employment status local service.
	 *
	 * @return the employment status local service
	 */
	public com.rknowsys.eapp.hrm.service.EmploymentStatusLocalService getEmploymentStatusLocalService() {
		return employmentStatusLocalService;
	}

	/**
	 * Sets the employment status local service.
	 *
	 * @param employmentStatusLocalService the employment status local service
	 */
	public void setEmploymentStatusLocalService(
		com.rknowsys.eapp.hrm.service.EmploymentStatusLocalService employmentStatusLocalService) {
		this.employmentStatusLocalService = employmentStatusLocalService;
	}

	/**
	 * Returns the employment status persistence.
	 *
	 * @return the employment status persistence
	 */
	public EmploymentStatusPersistence getEmploymentStatusPersistence() {
		return employmentStatusPersistence;
	}

	/**
	 * Sets the employment status persistence.
	 *
	 * @param employmentStatusPersistence the employment status persistence
	 */
	public void setEmploymentStatusPersistence(
		EmploymentStatusPersistence employmentStatusPersistence) {
		this.employmentStatusPersistence = employmentStatusPersistence;
	}

	/**
	 * Returns the interview local service.
	 *
	 * @return the interview local service
	 */
	public com.rknowsys.eapp.hrm.service.InterviewLocalService getInterviewLocalService() {
		return interviewLocalService;
	}

	/**
	 * Sets the interview local service.
	 *
	 * @param interviewLocalService the interview local service
	 */
	public void setInterviewLocalService(
		com.rknowsys.eapp.hrm.service.InterviewLocalService interviewLocalService) {
		this.interviewLocalService = interviewLocalService;
	}

	/**
	 * Returns the interview persistence.
	 *
	 * @return the interview persistence
	 */
	public InterviewPersistence getInterviewPersistence() {
		return interviewPersistence;
	}

	/**
	 * Sets the interview persistence.
	 *
	 * @param interviewPersistence the interview persistence
	 */
	public void setInterviewPersistence(
		InterviewPersistence interviewPersistence) {
		this.interviewPersistence = interviewPersistence;
	}

	/**
	 * Returns the job category local service.
	 *
	 * @return the job category local service
	 */
	public com.rknowsys.eapp.hrm.service.JobCategoryLocalService getJobCategoryLocalService() {
		return jobCategoryLocalService;
	}

	/**
	 * Sets the job category local service.
	 *
	 * @param jobCategoryLocalService the job category local service
	 */
	public void setJobCategoryLocalService(
		com.rknowsys.eapp.hrm.service.JobCategoryLocalService jobCategoryLocalService) {
		this.jobCategoryLocalService = jobCategoryLocalService;
	}

	/**
	 * Returns the job category persistence.
	 *
	 * @return the job category persistence
	 */
	public JobCategoryPersistence getJobCategoryPersistence() {
		return jobCategoryPersistence;
	}

	/**
	 * Sets the job category persistence.
	 *
	 * @param jobCategoryPersistence the job category persistence
	 */
	public void setJobCategoryPersistence(
		JobCategoryPersistence jobCategoryPersistence) {
		this.jobCategoryPersistence = jobCategoryPersistence;
	}

	/**
	 * Returns the job titles local service.
	 *
	 * @return the job titles local service
	 */
	public com.rknowsys.eapp.hrm.service.JobTitlesLocalService getJobTitlesLocalService() {
		return jobTitlesLocalService;
	}

	/**
	 * Sets the job titles local service.
	 *
	 * @param jobTitlesLocalService the job titles local service
	 */
	public void setJobTitlesLocalService(
		com.rknowsys.eapp.hrm.service.JobTitlesLocalService jobTitlesLocalService) {
		this.jobTitlesLocalService = jobTitlesLocalService;
	}

	/**
	 * Returns the job titles persistence.
	 *
	 * @return the job titles persistence
	 */
	public JobTitlesPersistence getJobTitlesPersistence() {
		return jobTitlesPersistence;
	}

	/**
	 * Sets the job titles persistence.
	 *
	 * @param jobTitlesPersistence the job titles persistence
	 */
	public void setJobTitlesPersistence(
		JobTitlesPersistence jobTitlesPersistence) {
		this.jobTitlesPersistence = jobTitlesPersistence;
	}

	/**
	 * Returns the language local service.
	 *
	 * @return the language local service
	 */
	public com.rknowsys.eapp.hrm.service.LanguageLocalService getLanguageLocalService() {
		return languageLocalService;
	}

	/**
	 * Sets the language local service.
	 *
	 * @param languageLocalService the language local service
	 */
	public void setLanguageLocalService(
		com.rknowsys.eapp.hrm.service.LanguageLocalService languageLocalService) {
		this.languageLocalService = languageLocalService;
	}

	/**
	 * Returns the language persistence.
	 *
	 * @return the language persistence
	 */
	public LanguagePersistence getLanguagePersistence() {
		return languagePersistence;
	}

	/**
	 * Sets the language persistence.
	 *
	 * @param languagePersistence the language persistence
	 */
	public void setLanguagePersistence(LanguagePersistence languagePersistence) {
		this.languagePersistence = languagePersistence;
	}

	/**
	 * Returns the license local service.
	 *
	 * @return the license local service
	 */
	public com.rknowsys.eapp.hrm.service.LicenseLocalService getLicenseLocalService() {
		return licenseLocalService;
	}

	/**
	 * Sets the license local service.
	 *
	 * @param licenseLocalService the license local service
	 */
	public void setLicenseLocalService(
		com.rknowsys.eapp.hrm.service.LicenseLocalService licenseLocalService) {
		this.licenseLocalService = licenseLocalService;
	}

	/**
	 * Returns the license persistence.
	 *
	 * @return the license persistence
	 */
	public LicensePersistence getLicensePersistence() {
		return licensePersistence;
	}

	/**
	 * Sets the license persistence.
	 *
	 * @param licensePersistence the license persistence
	 */
	public void setLicensePersistence(LicensePersistence licensePersistence) {
		this.licensePersistence = licensePersistence;
	}

	/**
	 * Returns the locations local service.
	 *
	 * @return the locations local service
	 */
	public com.rknowsys.eapp.hrm.service.LocationsLocalService getLocationsLocalService() {
		return locationsLocalService;
	}

	/**
	 * Sets the locations local service.
	 *
	 * @param locationsLocalService the locations local service
	 */
	public void setLocationsLocalService(
		com.rknowsys.eapp.hrm.service.LocationsLocalService locationsLocalService) {
		this.locationsLocalService = locationsLocalService;
	}

	/**
	 * Returns the locations persistence.
	 *
	 * @return the locations persistence
	 */
	public LocationsPersistence getLocationsPersistence() {
		return locationsPersistence;
	}

	/**
	 * Sets the locations persistence.
	 *
	 * @param locationsPersistence the locations persistence
	 */
	public void setLocationsPersistence(
		LocationsPersistence locationsPersistence) {
		this.locationsPersistence = locationsPersistence;
	}

	/**
	 * Returns the membership local service.
	 *
	 * @return the membership local service
	 */
	public com.rknowsys.eapp.hrm.service.MembershipLocalService getMembershipLocalService() {
		return membershipLocalService;
	}

	/**
	 * Sets the membership local service.
	 *
	 * @param membershipLocalService the membership local service
	 */
	public void setMembershipLocalService(
		com.rknowsys.eapp.hrm.service.MembershipLocalService membershipLocalService) {
		this.membershipLocalService = membershipLocalService;
	}

	/**
	 * Returns the membership persistence.
	 *
	 * @return the membership persistence
	 */
	public MembershipPersistence getMembershipPersistence() {
		return membershipPersistence;
	}

	/**
	 * Sets the membership persistence.
	 *
	 * @param membershipPersistence the membership persistence
	 */
	public void setMembershipPersistence(
		MembershipPersistence membershipPersistence) {
		this.membershipPersistence = membershipPersistence;
	}

	/**
	 * Returns the nationality local service.
	 *
	 * @return the nationality local service
	 */
	public com.rknowsys.eapp.hrm.service.NationalityLocalService getNationalityLocalService() {
		return nationalityLocalService;
	}

	/**
	 * Sets the nationality local service.
	 *
	 * @param nationalityLocalService the nationality local service
	 */
	public void setNationalityLocalService(
		com.rknowsys.eapp.hrm.service.NationalityLocalService nationalityLocalService) {
		this.nationalityLocalService = nationalityLocalService;
	}

	/**
	 * Returns the nationality persistence.
	 *
	 * @return the nationality persistence
	 */
	public NationalityPersistence getNationalityPersistence() {
		return nationalityPersistence;
	}

	/**
	 * Sets the nationality persistence.
	 *
	 * @param nationalityPersistence the nationality persistence
	 */
	public void setNationalityPersistence(
		NationalityPersistence nationalityPersistence) {
		this.nationalityPersistence = nationalityPersistence;
	}

	/**
	 * Returns the news local service.
	 *
	 * @return the news local service
	 */
	public com.rknowsys.eapp.hrm.service.NewsLocalService getNewsLocalService() {
		return newsLocalService;
	}

	/**
	 * Sets the news local service.
	 *
	 * @param newsLocalService the news local service
	 */
	public void setNewsLocalService(
		com.rknowsys.eapp.hrm.service.NewsLocalService newsLocalService) {
		this.newsLocalService = newsLocalService;
	}

	/**
	 * Returns the news persistence.
	 *
	 * @return the news persistence
	 */
	public NewsPersistence getNewsPersistence() {
		return newsPersistence;
	}

	/**
	 * Sets the news persistence.
	 *
	 * @param newsPersistence the news persistence
	 */
	public void setNewsPersistence(NewsPersistence newsPersistence) {
		this.newsPersistence = newsPersistence;
	}

	/**
	 * Returns the pay grade local service.
	 *
	 * @return the pay grade local service
	 */
	public com.rknowsys.eapp.hrm.service.PayGradeLocalService getPayGradeLocalService() {
		return payGradeLocalService;
	}

	/**
	 * Sets the pay grade local service.
	 *
	 * @param payGradeLocalService the pay grade local service
	 */
	public void setPayGradeLocalService(
		com.rknowsys.eapp.hrm.service.PayGradeLocalService payGradeLocalService) {
		this.payGradeLocalService = payGradeLocalService;
	}

	/**
	 * Returns the pay grade persistence.
	 *
	 * @return the pay grade persistence
	 */
	public PayGradePersistence getPayGradePersistence() {
		return payGradePersistence;
	}

	/**
	 * Sets the pay grade persistence.
	 *
	 * @param payGradePersistence the pay grade persistence
	 */
	public void setPayGradePersistence(PayGradePersistence payGradePersistence) {
		this.payGradePersistence = payGradePersistence;
	}

	/**
	 * Returns the pay grade currency local service.
	 *
	 * @return the pay grade currency local service
	 */
	public com.rknowsys.eapp.hrm.service.PayGradeCurrencyLocalService getPayGradeCurrencyLocalService() {
		return payGradeCurrencyLocalService;
	}

	/**
	 * Sets the pay grade currency local service.
	 *
	 * @param payGradeCurrencyLocalService the pay grade currency local service
	 */
	public void setPayGradeCurrencyLocalService(
		com.rknowsys.eapp.hrm.service.PayGradeCurrencyLocalService payGradeCurrencyLocalService) {
		this.payGradeCurrencyLocalService = payGradeCurrencyLocalService;
	}

	/**
	 * Returns the pay grade currency persistence.
	 *
	 * @return the pay grade currency persistence
	 */
	public PayGradeCurrencyPersistence getPayGradeCurrencyPersistence() {
		return payGradeCurrencyPersistence;
	}

	/**
	 * Sets the pay grade currency persistence.
	 *
	 * @param payGradeCurrencyPersistence the pay grade currency persistence
	 */
	public void setPayGradeCurrencyPersistence(
		PayGradeCurrencyPersistence payGradeCurrencyPersistence) {
		this.payGradeCurrencyPersistence = payGradeCurrencyPersistence;
	}

	/**
	 * Returns the salary component local service.
	 *
	 * @return the salary component local service
	 */
	public com.rknowsys.eapp.hrm.service.SalaryComponentLocalService getSalaryComponentLocalService() {
		return salaryComponentLocalService;
	}

	/**
	 * Sets the salary component local service.
	 *
	 * @param salaryComponentLocalService the salary component local service
	 */
	public void setSalaryComponentLocalService(
		com.rknowsys.eapp.hrm.service.SalaryComponentLocalService salaryComponentLocalService) {
		this.salaryComponentLocalService = salaryComponentLocalService;
	}

	/**
	 * Returns the salary component persistence.
	 *
	 * @return the salary component persistence
	 */
	public SalaryComponentPersistence getSalaryComponentPersistence() {
		return salaryComponentPersistence;
	}

	/**
	 * Sets the salary component persistence.
	 *
	 * @param salaryComponentPersistence the salary component persistence
	 */
	public void setSalaryComponentPersistence(
		SalaryComponentPersistence salaryComponentPersistence) {
		this.salaryComponentPersistence = salaryComponentPersistence;
	}

	/**
	 * Returns the skill local service.
	 *
	 * @return the skill local service
	 */
	public com.rknowsys.eapp.hrm.service.SkillLocalService getSkillLocalService() {
		return skillLocalService;
	}

	/**
	 * Sets the skill local service.
	 *
	 * @param skillLocalService the skill local service
	 */
	public void setSkillLocalService(
		com.rknowsys.eapp.hrm.service.SkillLocalService skillLocalService) {
		this.skillLocalService = skillLocalService;
	}

	/**
	 * Returns the skill persistence.
	 *
	 * @return the skill persistence
	 */
	public SkillPersistence getSkillPersistence() {
		return skillPersistence;
	}

	/**
	 * Sets the skill persistence.
	 *
	 * @param skillPersistence the skill persistence
	 */
	public void setSkillPersistence(SkillPersistence skillPersistence) {
		this.skillPersistence = skillPersistence;
	}

	/**
	 * Returns the work shift local service.
	 *
	 * @return the work shift local service
	 */
	public com.rknowsys.eapp.hrm.service.WorkShiftLocalService getWorkShiftLocalService() {
		return workShiftLocalService;
	}

	/**
	 * Sets the work shift local service.
	 *
	 * @param workShiftLocalService the work shift local service
	 */
	public void setWorkShiftLocalService(
		com.rknowsys.eapp.hrm.service.WorkShiftLocalService workShiftLocalService) {
		this.workShiftLocalService = workShiftLocalService;
	}

	/**
	 * Returns the work shift persistence.
	 *
	 * @return the work shift persistence
	 */
	public WorkShiftPersistence getWorkShiftPersistence() {
		return workShiftPersistence;
	}

	/**
	 * Sets the work shift persistence.
	 *
	 * @param workShiftPersistence the work shift persistence
	 */
	public void setWorkShiftPersistence(
		WorkShiftPersistence workShiftPersistence) {
		this.workShiftPersistence = workShiftPersistence;
	}

	/**
	 * Returns the work shift user local service.
	 *
	 * @return the work shift user local service
	 */
	public com.rknowsys.eapp.hrm.service.WorkShiftUserLocalService getWorkShiftUserLocalService() {
		return workShiftUserLocalService;
	}

	/**
	 * Sets the work shift user local service.
	 *
	 * @param workShiftUserLocalService the work shift user local service
	 */
	public void setWorkShiftUserLocalService(
		com.rknowsys.eapp.hrm.service.WorkShiftUserLocalService workShiftUserLocalService) {
		this.workShiftUserLocalService = workShiftUserLocalService;
	}

	/**
	 * Returns the work shift user persistence.
	 *
	 * @return the work shift user persistence
	 */
	public WorkShiftUserPersistence getWorkShiftUserPersistence() {
		return workShiftUserPersistence;
	}

	/**
	 * Sets the work shift user persistence.
	 *
	 * @param workShiftUserPersistence the work shift user persistence
	 */
	public void setWorkShiftUserPersistence(
		WorkShiftUserPersistence workShiftUserPersistence) {
		this.workShiftUserPersistence = workShiftUserPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.rknowsys.eapp.hrm.model.SalaryComponent",
			salaryComponentLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.rknowsys.eapp.hrm.model.SalaryComponent");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return SalaryComponent.class;
	}

	protected String getModelClassName() {
		return SalaryComponent.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = salaryComponentPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.rknowsys.eapp.hrm.service.DocCategoryLocalService.class)
	protected com.rknowsys.eapp.hrm.service.DocCategoryLocalService docCategoryLocalService;
	@BeanReference(type = DocCategoryPersistence.class)
	protected DocCategoryPersistence docCategoryPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.DocumentLocalService.class)
	protected com.rknowsys.eapp.hrm.service.DocumentLocalService documentLocalService;
	@BeanReference(type = DocumentPersistence.class)
	protected DocumentPersistence documentPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.EducationLocalService.class)
	protected com.rknowsys.eapp.hrm.service.EducationLocalService educationLocalService;
	@BeanReference(type = EducationPersistence.class)
	protected EducationPersistence educationPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.EmploymentStatusLocalService.class)
	protected com.rknowsys.eapp.hrm.service.EmploymentStatusLocalService employmentStatusLocalService;
	@BeanReference(type = EmploymentStatusPersistence.class)
	protected EmploymentStatusPersistence employmentStatusPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.InterviewLocalService.class)
	protected com.rknowsys.eapp.hrm.service.InterviewLocalService interviewLocalService;
	@BeanReference(type = InterviewPersistence.class)
	protected InterviewPersistence interviewPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.JobCategoryLocalService.class)
	protected com.rknowsys.eapp.hrm.service.JobCategoryLocalService jobCategoryLocalService;
	@BeanReference(type = JobCategoryPersistence.class)
	protected JobCategoryPersistence jobCategoryPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.JobTitlesLocalService.class)
	protected com.rknowsys.eapp.hrm.service.JobTitlesLocalService jobTitlesLocalService;
	@BeanReference(type = JobTitlesPersistence.class)
	protected JobTitlesPersistence jobTitlesPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.LanguageLocalService.class)
	protected com.rknowsys.eapp.hrm.service.LanguageLocalService languageLocalService;
	@BeanReference(type = LanguagePersistence.class)
	protected LanguagePersistence languagePersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.LicenseLocalService.class)
	protected com.rknowsys.eapp.hrm.service.LicenseLocalService licenseLocalService;
	@BeanReference(type = LicensePersistence.class)
	protected LicensePersistence licensePersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.LocationsLocalService.class)
	protected com.rknowsys.eapp.hrm.service.LocationsLocalService locationsLocalService;
	@BeanReference(type = LocationsPersistence.class)
	protected LocationsPersistence locationsPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.MembershipLocalService.class)
	protected com.rknowsys.eapp.hrm.service.MembershipLocalService membershipLocalService;
	@BeanReference(type = MembershipPersistence.class)
	protected MembershipPersistence membershipPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.NationalityLocalService.class)
	protected com.rknowsys.eapp.hrm.service.NationalityLocalService nationalityLocalService;
	@BeanReference(type = NationalityPersistence.class)
	protected NationalityPersistence nationalityPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.NewsLocalService.class)
	protected com.rknowsys.eapp.hrm.service.NewsLocalService newsLocalService;
	@BeanReference(type = NewsPersistence.class)
	protected NewsPersistence newsPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.PayGradeLocalService.class)
	protected com.rknowsys.eapp.hrm.service.PayGradeLocalService payGradeLocalService;
	@BeanReference(type = PayGradePersistence.class)
	protected PayGradePersistence payGradePersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.PayGradeCurrencyLocalService.class)
	protected com.rknowsys.eapp.hrm.service.PayGradeCurrencyLocalService payGradeCurrencyLocalService;
	@BeanReference(type = PayGradeCurrencyPersistence.class)
	protected PayGradeCurrencyPersistence payGradeCurrencyPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.SalaryComponentLocalService.class)
	protected com.rknowsys.eapp.hrm.service.SalaryComponentLocalService salaryComponentLocalService;
	@BeanReference(type = SalaryComponentPersistence.class)
	protected SalaryComponentPersistence salaryComponentPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.SkillLocalService.class)
	protected com.rknowsys.eapp.hrm.service.SkillLocalService skillLocalService;
	@BeanReference(type = SkillPersistence.class)
	protected SkillPersistence skillPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.WorkShiftLocalService.class)
	protected com.rknowsys.eapp.hrm.service.WorkShiftLocalService workShiftLocalService;
	@BeanReference(type = WorkShiftPersistence.class)
	protected WorkShiftPersistence workShiftPersistence;
	@BeanReference(type = com.rknowsys.eapp.hrm.service.WorkShiftUserLocalService.class)
	protected com.rknowsys.eapp.hrm.service.WorkShiftUserLocalService workShiftUserLocalService;
	@BeanReference(type = WorkShiftUserPersistence.class)
	protected WorkShiftUserPersistence workShiftUserPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private SalaryComponentLocalServiceClpInvoker _clpInvoker = new SalaryComponentLocalServiceClpInvoker();
}